### ISSUE TITLE
Editor window sometimes loses focus ability to select objects

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1]
This is possibly related to the new physics body editing. Looking for a reliable way to reproduce the problem.

**Comment by vlidholt** [comment]
Not exactly sure when this happens, but when it happens the cursor doesn't change either. It is still possible to drag things around, but it is as if the mouse events aren't patched through correctly. Possibly a bug in Cocos2d?

**Comment by vlidholt** [comment]
Found a way to reproduce.
1. Open this project: https://drive.google.com/file/d/0BzFSRgoEwrfXQ0xNcGpMb0tjczA/edit?usp=sharing
2. Open the MainScene.ccb file
3. Select the bottom left square
4. Open the Foo.ccb file
5. Select the right square
6. Choose the physics tab on the right side
7. Modify the physics shape
8. Cmd-S, then _very quickly_ switch back to the MainScene.ccb tab
9. Deselect the current object
10. Scrolling and other things doesn't work correctly

**Comment by jtwigg** [comment]
Should be resolved now. They physics system was holding onto a mouse click flag.
