### ISSUE TITLE
"Item Templates" tooltip on wrong button.

### ISSUE THREAD

**Issue by MKGitHub** [spritebuilder/SpriteBuilder#10]
"Item Templates" tooltip on wrong button, the one to the right.

![screenshot 2013-11-05 at 22 30 32](https://f.cloud.github.com/assets/535550/1477845/68bd11d6-4662-11e3-9d24-96b15acae2f1.png)

**Comment by jtwigg** [comment]
I'll take this.

**Comment by jtwigg** [comment]
Can you clarify? 
What should the 3rd tooltip be, what should the 4th tooltip be?

**Comment by jtwigg** [comment]
I've changed the Third icons text to 'Item Physics', but what should the fourth one be?

**Comment by vlidholt** [comment]
The fourth is templates. It's a new feature that currently only works with particle systems, but could be extended to other node types as well.

**Comment by vlidholt** [comment]
Third one should be 'Item Physics' (also need a new icon).

**Comment by jtwigg** [comment]
Fixed.
