### ISSUE TITLE
Xcode plugin Project Templates are not installed

### ISSUE THREAD

**Issue by paulb777** [spritebuilder/SpriteBuilder#1002]
The directory ~/Library/Developer/Xcode/Templates/Project\ Templates/Application should be populated with the Xcode plugin's Project Templates. 

However, it is still empty after installing SpriteBuilder-1.3.0-beta.07.zip:

~/Library  $ ls ~/Library/Developer/Xcode/Templates/Project\ Templates/Application
~/Library  $

It should be :+1: 
~/Library  $ ls ~/Library/Developer/Xcode/Templates/Project\ Templates/Application
BridgeKit Application.xctemplate    BridgeKit Service.xctemplate        JNI Application.xctemplate
~/Library  $

**Comment by NickyWeber** [comment]
XCode templates are not installed any more when you install SB.
