### ISSUE TITLE
Timeline view reset on Save/Undo

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1004]
Timeline will jump back to the start upon any save/undo (possibly other actions).
Would be nice not to lose current vertical position.

**Comment by iMobCoding** [comment]
Not only jump to start, but also unwrap all nested nodes. It does the same when you change device resolution

**Comment by NoorFatima** [comment]
This issue is fixed.
Device: Mac OS X 10.9.5
SB Version: 1.4.7
