### ISSUE TITLE
Effect is still visible on child node when even when user disable its visibility in the timeline. 

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#1007]
1. Launch SBP.
2. Drag EffectNode on MainScene.ccb.
3. Drag particle system as child node of EffectNode.
4. Apply "pixelate" effect.
5. Tap eye in the timeline of CCEffectNode to disable visibility.
   
   -- Result: Effect is still visible on child node when even when user disable its visibility in the timeline. 

Video attached:
https://drive.google.com/file/d/0B2b3lCCE3OwtS1RfblZ5YkFHQmM/view?usp=sharing

**Build:** SpriteBuilder 1.3 Beta 07

MAC OS: 10.9.0
XCode: 5.0

**Comment by sana20** [comment]
This issue is still occurring.
Build: SpriteBuilder-1.3.0-rc.1
MAC OS: 10.9.0
XCode: 5.0

**Comment by Kanoot** [comment]
This issue is reoccurring.

SpriteBuilder-1.3.4-rc.1

Device A:
Mac OS X: 10.9.5
XCode: 6.0

**Comment by cocojoe** [comment]
Visibility works as expected when selecting it from property panel on the effect node so expect it to work in timeline.

**Comment by sana20** [comment]
This issue is reoccurring.

Build:SpriteBuilder-1.3.5-rc.2

Device A:
Mac OS X: 10.9.5
XCode: 6.0

**Comment by NickyWeber** [comment]
The timeline's visibility has no effect on the published project. It is meant as a helper to organize complex scenes by toggling visibility.

**Comment by khanbhai89** [comment]
We can close the ticket as it is expected.
