### ISSUE TITLE
Particle effect disappears from the stage when user drag particle system under effectNode as a child. 

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#1009]
1. Launch SBP.
2. Drag EffectNode on MainScene.ccb.
3. Drag particle system on the stage and change texture.
4. Drag particle effect under EffectNode.
   
   -- Result: Particle effect disappears from the stage when user drag particle system under effectNode as a child. 

Link to the video:
https://drive.google.com/file/d/0B2b3lCCE3OwtQWpoN09NX21HQU0/view?usp=sharing

**Build:** SpriteBuilder 1.3 Beta 07

MAC OS: 10.9.0
XCode: 5.0

**Comment by sana20** [comment]
This issue is still occurring.
Build: SpriteBuilder-1.3.0-rc.1
MAC OS: 10.9.0
XCode: 5.0

**Comment by Kanoot** [comment]
This is not a bug, as in when we drag particle system under effectNode as a child then position of particle effect adds to the current position of effectNode. We drag effect node such that it is under CCeffect area then particle effect is displayed. 

SpriteBuilder-1.3.4-rc.1

Device A:
Mac OS X: 10.9.5
XCode: 6.0
