### ISSUE TITLE
Sprite Builder crashes when the user tries to add a .wav file from resource inspector to the sound effects of any file.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1021]
1. Launch sprite builder.
2. Add sound (.wav file) to the resources.
3. Drag that file in the sound effects area of mainscene.ccb.

-- Result: The sprite builder crashes as you add the sound file to the sound effects.

**Build:** SpriteBuilderPublicBeta-sb-1.3.0-beta.10-dcf-release_3.0.0-alpha.8-1796a6195bb752e59cffb5248f53ae39ca6fe441_3c4f284919369e12.dmg
**Mac OS X:** 10.9.0.
**XCode:** 5.0.

**Comment by NickyWeber** [comment]
Please add the crash report. I am not able to reproduce this.
If possible add a link to a sample project. 
Thanks.

**Comment by Kanoot** [comment]
This issue fixed.

Build: SpriteBuilderAdHoc-sb-1.3.0-rc.1-d49d1950d11b5a27d61b6234761197522d03875a_d6d92a9f14495012

MAC OS: 10.9.0
XCode: 5.0
