### ISSUE TITLE
The audio preview options do not display in the resource inspector when an audio is added to the resources.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1022]
1. Launch sprite builder.
2. Add an audio file to the resources.
3. Tap the audio file in the resource inspector to see the preview options.
   
   -- Result: No preview options are displayed of the audio in the resource inspector.

**Build:** SpriteBuilderPublicBeta-sb-1.3.0-beta.10-dcf-release_3.0.0-alpha.8-1796a6195bb752e59cffb5248f53ae39ca6fe441_3c4f284919369e12.dmg
**Mac OS X:** 10.9.0.
**XCode:** 5.0.

**Comment by Kanoot** [comment]
This issue fixed.

Build: SpriteBuilderAdHoc-sb-1.3.0-rc.1-d49d1950d11b5a27d61b6234761197522d03875a_d6d92a9f14495012

MAC OS: 10.9.0
XCode: 5.0
