### ISSUE TITLE
Error while running Sprite builder demo app on Android device.

### ISSUE THREAD

**Issue by subinrevi** [spritebuilder/SpriteBuilder#1029]
Hi,
      I have tested the demo app shown in www.spritebuilder.com and its working fine on iOS (iphone & simulator). But when i am trying to run it on Android device its showing an error. ('CCNode.h file is not found' in Level class ). Do i need to give any path in build settings?

**Comment by ebrodzki** [comment]
Are you testing while using the beta release of SpriteBuilder? If so are you selecting the Android specific target before attempting to build? 

I am also unsure if the demo apps that are meant for the non-beta SpriteBuilder release are meant to work with the beta version.

**Comment by subinrevi** [comment]
Hi,
     Sorry for the delayed response, that issue was fixed. Earlier while creating the "Level" class I selected Flying Feathers.java also for the Targets. When i changed that i was able to run it successfully in Android device.

**Comment by cocojoe** [comment]
@subinrevi  can you confirm please this issue can be closed?

**Comment by subinrevi** [comment]
Yes its fixed. It can be closed.
