### ISSUE TITLE
Position animation is copied to joints as well when user tries to copy paste it from one node to another.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1030]
1. Launch Application.
2. Drag a CCNode under Root Node to Main Scene.ccb.
3. Drag another CCNode under Root Node.
4. Drag a Color Node under first CCNode.
5. Add Visibility and Position animation on first CCNode.
6. Copy Visibility from First CCNode.
7. Paste CCNode on second CCNode.
   
   -- Result: Animation is added to Joints as well.

This happened 3/3 times.

Found on SpriteBuilderPublicBeta-sb-1.3.0-beta.10-dcf-release_3.0.0-alpha.8-1796a6195bb752e59cffb5248f53ae39ca6fe441_3c4f284919369e12.dmg

Mac OS X: 10.9.5
XCode: 6.0.

![screen shot 2014-10-21 at 7 07 57 pm](https://cloud.githubusercontent.com/assets/7450007/4719837/c3eaee9c-592c-11e4-8412-a3990804168e.png)

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.3.0-rc.1.zip on Mac OS X: 10.9.5. and XCode: 6.0.

**Comment by Kanoot** [comment]
This issue is still occurring.

Build: SpriteBuilder-1.3.4-rc.1

Mac OS X:10.9.5
XCode: 6.0

**Comment by cocojoe** [comment]
So I'm not actually sure why do we show detail in the joint timeline? You can't actually animate it.....  

Oddly the joint timeline is only effect by the node directly above it, if you play around with the timeline the joint timeline will adjust as well.

**Comment by sana20** [comment]
As per the cocojoe comment we tested and this issue is fixed.
Build: SpriteBuilder-1.3.6.rc.1
Mac OS X: 10.9.5
XCode: 6.0
