### ISSUE TITLE
Debug builds: cocos2d logging level 2 affects performance

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#1033]
The cocos2d.xcodeproj currently has `COCOS2D_DEBUG=2` set. This causes CCLOGINFO to print out a lot of stuff, for instance every deallocation of a node. 

Node deallocations happen quite frequently when scrolling a scene for instance, thus the scrolling is noticably slow (feels like 5-10 fps). Practically all user interactions are affected, for instance physics collision shape editing. When going back to log level 1 performance is back to normal.

**Comment by NickyWeber** [comment]
Yeah noticed as well. Three different debug macroes?! 
- COCOS2D_DEBUG
- DEBUG
- CD_DEBUG

Took some time to get rid off it manually.

**Comment by NickyWeber** [comment]
On develop only Mac target was still doing level 2.

Fixed in pull request: https://github.com/cocos2d/cocos2d-swift/pull/1081
