### ISSUE TITLE
Xcode SB publish script timeout issues

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1039]
Raising this from Forum

http://forum.spritebuilder.com/t/shell-script-invocation-error-spritebuilder-got-an-error-apple-event-timed-out-solved/1402

Anyone know if script execution time can be increased in project settings?

**Comment by cocojoe** [comment]
@NickyWeber  If you have also ran into this issue and stopped using script yourself, is this script still relevant?

**Comment by NickyWeber** [comment]
@cocojoe  It's a convenience script as far as I know. If you hit run in XCode you make sure that everything is up to date in your project Sprite Builder wise. 

The most recent 1.3 beta project template disables the script.

Some issues with this script:
- If publish is set to release this can take a long time without knowing
- The script will make SB publish any project that is open even one that is not related to the current XCode project. 
- The script will also have trouble if you run more than one instance of Sprite Builder.

**Comment by NickyWeber** [comment]
Since the forum post is marked as solved, I'll clost this for the time being.
