### ISSUE TITLE
Code completion for Obj-C is broken on new projects

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1048]
Code completion doesn't work for most CC\* classes in new Obj-C projects created with SpriteBuilder.

**Comment by NickyWeber** [comment]
I cannot reproduce this. Can you profide some examples?

I scrolled through the autocompletion list starting 'CC' and I found all the cocos2d classes i recognize.

![bildschirmfoto 2014-10-23 um 11 39 10](https://cloud.githubusercontent.com/assets/5259653/4750940/7e314bae-5a98-11e4-951e-8b6eefc4db9b.png)

Can you try to invalidate XCode's cache and try again? http://stackoverflow.com/questions/5714372/how-to-empty-caches-and-clean-all-targets-xcode-4

OS: 10.10
Xcode: Version 6.1 (6A1052d)

**Comment by vlidholt** [comment]
Updated to Xcode 6.1 – it now works
