### ISSUE TITLE
Breakpoints in Swift causes Xcode to crash

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1049]
Not exactly a SpriteBuilder bug, but Xcode crashes when trying to use breakpoints with Cocos2D & Swift. We should check which versions of Xcode are affected and if this is something we can fix.

**Comment by NickyWeber** [comment]
Cannot reproduce this. Breakpoint stops as expected and can continue without Xcode saying goodbye.

OS: 10.10
Xcode: Version 6.1 (6A1052d)
