### ISSUE TITLE
A new project comes with a whole set of warnings

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1050]
Compiling a newly created SB project gives a whole bunch of warnings in Xcode. It should be nice and clean!

**Comment by NickyWeber** [comment]
After pull requests of cocos2d submodules have been merged the used revisions have to be bumped.

**Comment by NickyWeber** [comment]
Who should fix ObjectAL warnings? Origin of the fork https://github.com/kstenerud/ObjectAL-for-iPhone or us?

**Comment by vlidholt** [comment]
![screen shot 2014-10-23 at 11 19 45 am](https://cloud.githubusercontent.com/assets/1539812/4758700/41303afa-5ae1-11e4-93db-e7ee1f00d0c6.png)

Current set of warnings.. 7 to go :P

**Comment by NickyWeber** [comment]
After merging the pull requests and bumping spritebuilder's cocos2d submodule there should be only two warnings left: ObjactAL and the deprecated warnings.
