### ISSUE TITLE
Crystal project doesn't run in iOS Simulator when user tries to running it after cloning.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1053]
1. Clone the repo here:  https://github.com/spritebuilder/Crystals.spritebuilder.git; switch to branch 'android'
2. Open the project in the SB.
3. Publish the project.
   -- Observe: No errors are generated when user publishes the project. (Expected)
4. Open the Xcode project and run in iOS simulator.
   
   -- Result: PBXCp Error and Lexical or Preprocessor issue is generated in CCtiledMapLayer.h.
     This happened 3/3 times.

Build: SpriteBuilder-1.3.0-beta.07.zip
Build: SpriteBuilderPublicBeta-sb-1.3.0-beta.11-dcf-release_3.0.0-alpha.9-3a47ca428881dc6cd33d7dba07f674910c51a584_e5b24781c1aa16a5.dmg 

Mac OS X: 10.9.5.
XCode: 6.0.

![screen shot 2014-10-23 at 2 52 09 pm](https://cloud.githubusercontent.com/assets/7450007/4751118/73a45120-5a9a-11e4-84a4-7197b6de9eda.png)
![screen shot 2014-10-23 at 2 52 24 pm](https://cloud.githubusercontent.com/assets/7450007/4751119/73a9a846-5a9a-11e4-908b-cadc11c3500f.png)

**Comment by Kanoot** [comment]
This issue fixed.

Build: SpriteBuilderAdHoc-sb-1.3.0-rc.1-d49d1950d11b5a27d61b6234761197522d03875a_d6d92a9f14495012

MAC OS: 10.9.0
XCode: 5.0
