### ISSUE TITLE
Application crashes on an android device when user adds joints in the project.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1054]
1. Launch SpriteBuilder.
2. Create a new project.
3. Place Physics Pivot joint and place it between to images one static other dynamic.
4. Place Physics Distance joint in SBP and place it between to images one static other dynamic.
5. Place Physics Spring joint in SBP and place it between to images one static other dynamic
6. Open the Xcode project and run in iOS simulator.
   -- Observe: It runs fine when it runs in simulator. (Expected)
7. Attach an android device and build the project on Android device.
   
   -- Result: Build builds successfully but application crashes with ANR pop-up when user launches it on the device.
     This happened 3/3 times.

Target: 'your Appname" Android > Android Device (armv7a-neon)

Console Log: https://drive.google.com/a/werplay.com/file/d/0B5KeRaV3CWUaTk15SUoxeWEtOWc/view?usp=sharing

Build: SpriteBuilder-1.3.0-beta.07.zip

Mac OS X: 10.9.5.
XCode: 6.0.
Device: HTC One/4.1.2. and SGS4/4.4.2.

**Comment by Kanoot** [comment]
This issue is fixed, joints work perfectly fine on Android device.

Build: SpriteBuilder-1.3.0-rc.1.zip

Mac OS X: 10.9.0
XCode: 5.0
Android device: SGS4/4.4.2
