### ISSUE TITLE
Label text field converts certain characters to non-printable characters

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#1060]
If you type `...`or `" "`and `'` the text field seems to convert those to unicode (?) characters. Much like MS Word does when you enter ... and it converts it to a single three-dots character. Same problem you sometimes have when copy & pasting code from a webpage where suddenly string escape quotes "" are slightly at an angle and produce compile errors.

I noticed this when working with a bitmap font label. I can type two dots .. but as soon as I enter the third dot, all three dots disappear from the label. The same happens to the quotation characters, but instantly. So I'm unable to type something like `"Hey!"`because the quotation marks are converted to different kinds of quotation marks that aren't present in the bitmap font.

![screen shot 2014-10-23 at 18 09 24](https://cloud.githubusercontent.com/assets/214599/4756633/fb4597cc-5ace-11e4-844d-46b048b5a242.png)

**Comment by cocojoe** [comment]
Was looking into this, apparently there are some 'smart' options that get applied to the NSTextField, I disabled them to test however it turns out the checkmarks in Xcode also don't appear to do work as expected as of 10.9 so will sublcass and try it later.
