### ISSUE TITLE
Mac target does not find images in resources

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#1064]
Mac target does not find images in resources.
1. Create a project
2. Add PNG sprites to the scene
3. Build and run the Mac target

Expect: To see the placed PNG images in the scene

Result now: 
" -[CCFileUtils fullPathForFilename:contentScale:] : cocos2d: Warning: File not found: L.png"

Even in Appdelegate the file search paths are correctly set?!

**Comment by ghost** [comment]
Ok. Found out that SpriteBuilder doesn't set the Mac  file suffix things.

This might be a fix.

In CCBReader.m:

```
+ (void) configureCCFileUtils
{
   CCFileUtils *sharedFileUtils = [CCFileUtils sharedFileUtils];

    // Setup file utils for use with SpriteBuilder
    [sharedFileUtils setEnableiPhoneResourcesOniPad:NO];

    sharedFileUtils.directoriesDict =
    [[NSMutableDictionary alloc] initWithObjectsAndKeys:
     @"resources-tablet", CCFileUtilsSuffixiPad,
     @"resources-tablethd", CCFileUtilsSuffixiPadHD,
     @"resources-phone", CCFileUtilsSuffixiPhone,
     @"resources-phonehd", CCFileUtilsSuffixiPhoneHD,
     @"resources-phone", CCFileUtilsSuffixiPhone5,
     @"resources-phonehd", CCFileUtilsSuffixiPhone5HD,
     @"", CCFileUtilsSuffixDefault,
#if __CC_PLATFORM_MAC
      @"resources-phone", CCFileUtilsSuffixMac,
      @"resources-phonehd", CCFileUtilsSuffixMacHD,
#endif
     nil];
```

**Comment by collinjackson** [comment]
This looks fine to me, can you submit it as a pull request on Cocos2D?

**Comment by rkachowski** [comment]
This appears to work correctly - png files are bundled and loaded correctly - in the latest SB
