### ISSUE TITLE
Can't create iOS App Archive

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1068]
Raised in http://forum.spritebuilder.com/t/spritebuilder-1-3-beta-cant-create-archive/2139

I'm unable to confirm this right now.

Possible backstory/solution

http://stackoverflow.com/questions/10715211/cannot-generate-ios-app-archive-in-xcode

**Comment by ghost** [comment]
Can confirm. The fix is to move the SSZipArchive headers to project as mentioned in the post. Not sure if Skip Install should also be set to YES.

**Comment by NickyWeber** [comment]
First step done. I added skip install since all other externally linked projects in cocos2d set to YES.
