### ISSUE TITLE
The nodes are not displayed on the IOS simulator when user adds refraction or reflection effect to the CCeffect node .

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1072]
1. Launch Sprite Builder.
2. Make a new project.
3. Add a layer in the project.
4. Add CCEffect Node to the layer and add tower button under the cceffect node.
5. Add reflection or refraction effect to the node.
6. Add scroll view to the main scene file.
7. Add the above layer to that scroll view.
8. Publish the project.
9. Run the project through Xcode.
   
   -- Result: The nodes are not displayed on the IOS simulator when user adds refraction or reflection effect. Moreover this happened when the layer was added to scroll view.

Build: SpriteBuilder-1.3.0-rc.1
Mac OS X: 10.9.0
XCode: 5.0

**Comment by sana20** [comment]
This issue is still occurring.
Build: SpriteBuilder-1.3.4-rc.1
Mac OS X: 10.9.5
XCode: 6.0

**Comment by cocojoe** [comment]
This works for me again based upon your steps list, please provide a video or project.  Thanks

**Comment by Kanoot** [comment]
This issue is fixed.

Build: SpriteBuilder-1.3.6.rc.1

Mac OS X: 10.9.5.
XCode: 6.0.
