### ISSUE TITLE
Mac target crashes on mouse move.

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#1082]
Doesn't matter if setAcceptMouseMovedEvents is set to YES/NO crashes if you move the mouse even a bit while clicking.

![screen shot 2014-10-30 at 4 42 32 pm](https://cloud.githubusercontent.com/assets/5808253/4851770/4ed92812-6075-11e4-8bf3-3d98d324c628.png)

**Comment by NickyWeber** [comment]
Is this still relevant?

**Comment by cocojoe** [comment]
Will give it a quick test in 1.3.6

**Comment by cocojoe** [comment]
All worked fine for me with clean 1.3.6 project.
