### ISSUE TITLE
Mac target log spam

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#1084]
![screen shot 2014-10-31 at 1 52 36 pm](https://cloud.githubusercontent.com/assets/5808253/4865809/e1968558-6126-11e4-886c-a1608c409864.png)

Log is rippin' with CCLOGs when running the mac target. Confirmed that the COCOS2D_DEBUG=1 is set in the build settings, however it doesn't seem to be honored.

**Comment by cocojoe** [comment]
The cocos2d-mac target inherits the cocos2d project debug settings which sets COCOS2D_DEBUG=2

Other targets such as cocos2d-ios don't bother to inherit and manually set COCOS2D_DEBUG=1

**Comment by ghost** [comment]
Ok, not really an issue then.

**Comment by NickyWeber** [comment]
It's still highly annoying that those flags are set by default.

**Comment by cocojoe** [comment]
Oh yeah, would say default should be 1 across the board, don't generally need 2 for day to day debug.
