### ISSUE TITLE
Mac Layout Node Vertical Position as % Issue

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1087]
Setting node position as % results in vertical position error. Notice the black bar at bottom.

**SB Setup (Looks Fine)**
![layoutpercentage](https://cloud.githubusercontent.com/assets/928115/4876613/1fa3447a-62cc-11e4-8ed1-874854f8d38d.png)

**Result**
![screenpercentage](https://cloud.githubusercontent.com/assets/928115/4876617/25d846ba-62cc-11e4-84ed-514f893973e5.png)

**Comment by Shahidwerplay** [comment]
I could not reproduce the issue on my device. This is working perfectly fine on SB version 1.4.9

Mac OS X:10.10.0
XCode 6.2
