### ISSUE TITLE
"ARC Semantic issue" error is displayed on Xcode when user tries to runs an empty project for Android device.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1096]
1. Launch Sprite Builder.
2. Tap File>New>Project
3. Create empty project.
4. Publish the project.
5. Open the project in Xcode.
6. Make sure the target is set to android.
7. Plug in  the android device you want to run the project on.
8. Run the project.
   
   -- Result: "ARC Semantic issue" error is displayed on Xcode when user tries to runs an empty project for Android device.

This happened 3/3 times.

Build: SpriteBuilder-1.3.4-rc.1
Device1: SGS4/4.2.2. (i9505)
Device2: Note 2/4.1.1.
Device3: SGS4/4.2.2. (i9500)
Mac OS X:10.9.5
XCode: 6.0

![screen shot 2014-11-06 at 3 58 10 pm](https://cloud.githubusercontent.com/assets/8393830/4934795/755865b8-65a5-11e4-85e8-ed21ceda2654.png)

**Comment by cocojoe** [comment]
Actually just ran into this very issue trying out some clean android testing, commented against original commit 

@slembcke 
https://github.com/cocos2d/cocos2d-swift/commit/dc0a2a892c0f745fcf1d2a657e1d8f672107d580

**Comment by Kanoot** [comment]
This issue is reoccurring.

SpriteBuilder-1.3.4-rc.1

Device A:
Mac OS X: 10.9.5
XCode: 6.0

**Comment by NickyWeber** [comment]
Please retest this should be fixed now.

**Comment by sana20** [comment]
This issue is fixed.

Build: SpriteBuilder-1.3.6.rc.1
Mac OS X: 10.9.5
XCode: 6.0
Device: LG G3/4.4.2 , verified 3/3 times
