### ISSUE TITLE
Node instruction is a bit confusing, in the beginning...

### ISSUE THREAD

**Issue by MKGitHub** [spritebuilder/SpriteBuilder#11]
Node instruction is a bit confusing, in the beginning until you figure out what it means.

Maybe it could just say "Positions its child nodes..." instead of "Positions the children below it..." – which is saying the children/nodes in the tim line hierarchy.

![screenshot 2013-11-05 at 22 30 48](https://f.cloud.github.com/assets/535550/1477849/7e319c4e-4662-11e3-96b2-d395e4141b68.png)

**Comment by jtwigg** [comment]
I'll take this. Is this the final text?

**Comment by vlidholt** [comment]
All the texts and icons for the node types are currently drafts. Feel free to add better descriptions!
