### ISSUE TITLE
"Error updating Cocos2D" is generated when user tries to open 1.2 project in SB 1.3.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1100]
1. Launch SB 1.2.
2. Create a Empty Project.
3. Publish and Run project in XCode.
   -- Observe: Empty project runs fine in the iOS simulator. (Expected)
4. Uninstall SB 1.2.
5. Install SB 1.3 and Android Plugin.
6. Open SB project file of empty project.
   -- Observe: Update project pop-up is displayed. (Expected)
7. Click update project.
   
   -- Result: Error updating Cocos2D error message is displayed after sometime.
     This happened 3/3 times.

Build: SpriteBuilder-1.3.4-rc.1

Project: https://drive.google.com/a/werplay.com/file/d/0B5IZPBQTRkjPMGdONkowNTJkUWs/view?usp=sharing

Mac OS X: 10.10
XCode: 6.1

![screen shot 2014-11-06 at 7 43 14 pm](https://cloud.githubusercontent.com/assets/7450007/4937732/e31d6e34-65c5-11e4-97ad-eb3180ddfccc.png)

**Comment by KristenY** [comment]
Please verify whether you followed the instructions here:  http://android.spritebuilder.com/#dealing-with-spritebuilder-projects-from-spritebuilder-1-2-and-earlier.  If not, try them and let us know if the issue is resolved.

Thanks!

**Comment by khanbhai89** [comment]
I tested it on another mac and this issue is fixed when user upgrades it from 1.2 project to 1.3.

Mac OS X: 10.10.
XCode: 6.1.

You can mark it as fixed.
