### ISSUE TITLE
SB doesn't give any warnings when user insert .ccb extension two times after file name.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#1106]
1. Launch application.
2. Create a new file.
3. Insert .ccb again after filename.ccb.
4. Publish SB project.
   
   -- Result: SB doesn't give any warnings when user insert .ccb extension two times after file name.

**Important Note:** Even in the finder it is displayed with two extensions.

![screen shot 2014-11-07 at 3 30 27 pm](https://cloud.githubusercontent.com/assets/7566802/4951596/2f1a3742-6669-11e4-9313-09571ef77bdf.png)

Build: SpriteBuilder-1.3.4-rc.1

Mac OS X:10.9.5
XCode: 6.0

**Comment by cocojoe** [comment]
Xcode doesn't stop a user from using a double extension, I agree it is undesirable behaviour however it's user error.
