### ISSUE TITLE
File is displayed blur in the finder and another .ccb is appened itself when user creates a file with no name. 

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#1107]
1. Launch application.
2. Create a new file with no name.

-- Result: File is displayed blur in the finder and another .ccb is appened itself when user creates a file with no name. 

![empty ccb](https://cloud.githubusercontent.com/assets/7566802/4951696/8b5093c0-666a-11e4-85cc-02aabead92c4.png)

Build: SpriteBuilder-1.3.4-rc.1

Mac OS X:10.9.5
XCode: 6.0

**Comment by cocojoe** [comment]
File names should require a minimum number of characters.

**Comment by sana20** [comment]
This issue is still occurring.
Build: SpriteBuilder-1.3.5-rc.2
Mac OS :10.9.5
XCode: 6.0

**Comment by Kanoot** [comment]
This issue is still occurring.

Build: SpriteBuilder-1.3.6.rc.1

Mac OS: 10.9.5
XCode: 6.0

**Comment by khanbhai89** [comment]
This issue is still occurring on Build: SpriteBuilder-1.4.8-rc.0.zip

Mac OS X: 10.9.5.
XCode: 6.1.

**Comment by sana20** [comment]
This issue is still occurring on Build: SpriteBuilder-1.4.8-rc.0.zip with SBAndroidPluginStarter-9ac08c84

Mac OS X: 10.10.
XCode: 6.1.

**Comment by Shahidwerplay** [comment]
This issue is fixed

Mac OS 10.10.0
SB Version latest develop branch 2.0
XCode 6.1
