### ISSUE TITLE
SB doesn't give any warnings when user creates a file name of just a special character or blank spaces.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#1109]
1. Launch application.
2. Create a new project.
3. Create a new file and name it with special character only.
4. Publish project.
   
   -- Result: SB doesn't give any warnings when user creates a file name of just a special character or blank spaces.

**Important Note:** SB must give warning for this otherwise it would be impossible to link these file in code.

![screen shot 2014-11-07 at 4 43 38 pm](https://cloud.githubusercontent.com/assets/7566802/4952384/69b2d850-6673-11e4-9912-4c279e1f564b.png)

Build: SpriteBuilder-1.3.4-rc.1

Mac OS X:10.9.5
XCode: 6.0

**Comment by cocojoe** [comment]
Relates to #1107

**Comment by cocojoe** [comment]
So in addition to #1107 must also be standard characters.

**Comment by sana20** [comment]
This issue is still occurring.
Build: SpriteBuilder-1.3.5-rc.2
Mac OS :10.9.5
XCode: 6.0

**Comment by Kanoot** [comment]
This issue is still occurring.

Build: SpriteBuilder-1.3.6.rc.1

Mac OS: 10.9.5
XCode: 6.0

**Comment by khanbhai89** [comment]
This issue is still occurring on Build: SpriteBuilder-1.4.8-rc.0.zip

Mac OS X: 10.9.5.
XCode: 6.1.

**Comment by rkachowski** [comment]
This is not a bug, please stop testing this.

**Comment by khanbhai89** [comment]
@rkachowski Ok sure we will remove it from the testcases than.
Thanks!
