### ISSUE TITLE
Application crashes on launch when user runs a project on Android after adding blur effect to a sprite.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1127]
1. Launch SB.
2. Create an empty project.
3. Remove everything from the MainScene.ccb.
4. Add a new image on the stage.
5. Add a Blur Effect on that image.
6. Publish the project.
7. Build and Run in XCode on "Project Android > Your android phone".
8. Open application on the device.
   
   -- Result: Application crashes after displaying black screen on the launch.

Console: https://drive.google.com/a/werplay.com/file/d/0B5KeRaV3CWUaYTA1ZjNCcWtPWEk/view?usp=sharing

Build: SpriteBuilder-1.3.5-rc.2

Mac OS X: 10.9.5.
XCode: 6.0.

**Comment by Kanoot** [comment]
This issue is fixed.

Build: SpriteBuilder-1.3.6.rc.1

Mac OS X: 10.9.5.
XCode: 6.0.
Device: Nexus 4/4.3
