### ISSUE TITLE
System fonts are not displayed correctly when user ports an application to android.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1133]
1. Launch SB.
2. Open MainScene.ccb.
3. Select CCLabelTTF i.e. "Spritebuilder".
4. Select Font Name: "System Font > Courier Bold".
   -- Observe: Font is displayed correctly on to the stage. (Expected)
5. Publish the project.
6. Run and Port the build to Android (target: Project Android > Android device).
7. Open application on android device.
   
   -- Result: "Courier Bold" font is not displayed correctly on android.

Project: https://drive.google.com/a/werplay.com/file/d/0B5KeRaV3CWUad2xJNWM4MU41WWs/view?usp=sharing

This happened 3/3 times.

Mac OS X: 10.9.5.
XCode: 6.0.
Device: SGS4/4.4.2.

**Comment by NickyWeber** [comment]
Can you please attach screenshots if there is a visible difference between expected and actual results?

**Comment by khanbhai89** [comment]
This is screenshot from SpriteBuilder and actual font:

![screen shot 2014-11-18 at 10 55 58 pm](https://cloud.githubusercontent.com/assets/7450007/5093056/3fb00058-6f76-11e4-9252-0811864866e3.png)

This is the screenshot from the Device:

![game](https://cloud.githubusercontent.com/assets/7450007/5093055/36ba429c-6f76-11e4-9383-c41b56718062.png)

**Comment by khanbhai89** [comment]
This is happening with all other projects as well. Verified on 
Mac OS X: 10.9.5. 
Xcode: 6.1. 
SpriteBuilder: 1.4.9. 
AndroidPlugin: SBAndroid Indie 948d0c4e

**Comment by ebrodzki** [comment]
If you select a system font that is not available on Android, it will substitute something else, usually Roboto, that looks to be what is happening here.

**Comment by NoorFatima** [comment]
This issue is fixed.
Mac OS X: 10.9.5
XCode Version: 6.1
SB Version:  1.4.9
