### ISSUE TITLE
New version of sprite builder update weirdness

### ISSUE THREAD

**Issue by honkskillet** [spritebuilder/SpriteBuilder#1135]
Hey, I just update SB to 1.3.5. When I opened a project I had been working on with (cocos2d version 3.2.x) SB update the project. On first attempt there was an error (something about the lib folder already existing) and SB automatically rolled back the project to the last snapshot. When I opened the project again in SB, SB once again tried to up the version of cocos2d. This time it seamed to work but once in Xcode when I built the project i get this error.

In CCTiledMapLayer.h
# import "CCMathTypesAndroid.h" ----> 'CCMathTypesAndroid.h' file not found

OK, so I cleaned and built and I got a UITouch error... I did a little google-foo and found this

http://www.spritebuilder.com/update

I made the changes there and now my project builds, so that is nice.

But in cocos2d.h it says the version is

COCOS2D_VERSION 0x00030300

That's 3.3.0, right? Is cocos2d.h the definitive location for the current version? In the text file RELEASE_NOTES and CHANGELOG the versions list there are impossibly old. There is another live thread now where the poster is asked to perform File->Update_Cocos2d in SB. That option is greyed out in my project as well. So am I running 3.3.0?

**Comment by NickyWeber** [comment]
Have a look at the cocos2d-iphone folder, there should be a VERSION file. is the content more recent? At least that's the version SB processes to make assumptions about updatability.

**Comment by honkskillet** [comment]
Thanks for the reply.

The only file named version in the entire MyGame.spritebuilder folder is VERSION.txt for chipmunk.  Do you have the exact path I should check for the file?  Have the location of this file been constant since 3.2?

**Comment by honkskillet** [comment]
Ignore last comment.  It says 3.3.5.  Thanks.

Perhaps all old version info should be rooted out permanently.  

I'm still not sure why Sprite Builder failed to update the project the attempt and had to roll back, but it all looks good now.
