### ISSUE TITLE
Upgrading project causes linking problems

### ISSUE THREAD

**Issue by DonomaGames** [spritebuilder/SpriteBuilder#1148]
I had created a new project using SB 1.3.x w/ cocos2d 3.2.1. The new SB 1.3.5 prompted me to upgrade cocos2d to 3.3 automatically and I allowed SB to perform the upgrade. Opening up the project in XCode builds properly, however after I moved the project to another folder, it would no longer build. The error is "Cannot open file" for cocos2d-ios.xcodeproj. 

I manually deleted the cocos2d-ios.xcodeproj in libs folder and added the latest cocos2d, set the dependencies, and it built properly no matter where I moved the folder.

**Comment by tangogrowler** [comment]
Same issue here after switching to a new macbook. Not sure how to fix / workaround in SB136 as the proj is already converted to cocos2d-3.3 and there's no separate library download on the website. Please advise. Thanks

**Comment by DonomaGames** [comment]
I have SB1.3.5, but should be the same for SB136.

Open XCode
Find Libs folder on left navigation panel
Delete the cocos2d-ios.proj from xcode
Drag cocos2d.xcodeproj from the libs/cocos2d-iphone folder into xcode libs folder
In XCode, go to Build Phases
In Target Dependencies, add cocos2d-ios
In Link Binary with Libraries section, add libcocos2d.a
Compile and run.

**Comment by tangogrowler** [comment]
Perfect - thank you :)

**Comment by tandavas** [comment]
Same issue here but with Github repo:
1st mac updates the cocos2d via SpriteBuilder to version 3.3.6 -- work great and push to github. 2nd mac pull the updated version of the project and now have this error:

> "Cannot open file" for cocos2d-ios.xcodeproj. 

SB Version: 1.3.6
Cocos2d Version: 3.3.6

**Comment by rkachowski** [comment]
This has been resolved in the latest SB develop - ad1731b - closing as fixed.
