### ISSUE TITLE
Support for lighting effects

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1149]
Adds visual editing of lighting effects to SpriteBuilder.

**Comment by vlidholt** [comment]
Almost there, but still has some issues:
- [x] Toggling the visible property has no effect.
- [x] Add option for hiding lights (_Document > Show > Lights_)
- [x] Not exactly related to lighting, but _Document > Show Joints_ should probably go in _Document > Show > Joints_
- [x] Make it possible to animate the color properties
- [x] Exported animations don't work (needs custom actions to be added to CCBReader)
- [x] Should we add default lighting to a ccb document (a centered light, if no light has been added to a scene file)? This shouldn't be exported, and only be used if there are no other lights in the scene.

**Comment by thayerandrews** [comment]
Color properties can be animated with pull request https://github.com/spritebuilder/SpriteBuilder/pull/1198

**Comment by thayerandrews** [comment]
https://github.com/spritebuilder/SpriteBuilder/pull/1205 addresses the second and third items above: 
- Lights can now be hidden and shown via the _Document > Show > Lights_ menu item or via the visibility controls in the sequencer. 
- This also moves _Document > Show Joints_ to _Document > Show > Joints_.

**Comment by thayerandrews** [comment]
https://github.com/spritebuilder/SpriteBuilder/pull/1205 now addresses the sixth item as well:
- If there are no lights in the scene then a default light will be enabled. This light is not saved with the scene, it's only an editing convenience.

**Comment by thayerandrews** [comment]
Exported animations for light properties should work with pull request https://github.com/cocos2d/cocos2d-swift/pull/1112.
