### ISSUE TITLE
Improve effect editing

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1154]
In particular:
- Remove a selected effect by hitting the back key
- Drag and drop to re-order effects
- Fix display of selected effects to use colors that better match the Yosemite UI
- Fix display errors when an effect is selected and then deselected

**Comment by NickyWeber** [comment]
Order changes: https://github.com/spritebuilder/SpriteBuilder/issues/1051 -> will close this one.
And this one: https://github.com/spritebuilder/SpriteBuilder/issues/870

**Comment by NickyWeber** [comment]
"Fix display errors when an effect is selected and then deselected" Is this related to https://github.com/spritebuilder/SpriteBuilder/issues/1027?
