### ISSUE TITLE
Better workflow with git

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1158]
Some things doesn't work super well with git:
- When doing upgrades, backed up files should be hidden by .gitignore
- Files with changes that doesn't affect the results (e.g. folding of nodes) are saved. We could probably make this better. Especially for changes that are saved when no changes have been made (I think there are some in the project/package files).

**Comment by NickyWeber** [comment]
Can you elaborate on the last point: Should the publisher auto save if there were changes and the popup is just in the way?

**Comment by vlidholt** [comment]
Hm, for the second one... Cannot reproduce it at this very moment. Please ignore it for now, and I'll create a new more detailed ticket if I run across it again.

**Comment by vlidholt** [comment]
Ok, some more details on this one:
- intermediateFileLookup.plist shows up in git, this is a generated file and should probably go in the cache directory instead?
- When toggling image settings in SpriteBuilder, these changes doesn't show up (at least not immediately) in git. E.g. change the format of an exported file to jpg.

**Comment by NickyWeber** [comment]
**Quick solution:** add intermediateFileLookup.plist to gitignore
**Proper solution:** As you mentioned use caches folder, or remove after usage, the filelookup is always generated without caching mechanism.

The changes I make to an image for example show up immediately in sourceforge and on command line.

**Comment by vlidholt** [comment]
Seems fixed, closing this one! :) Please reopen if still an issue.
