### ISSUE TITLE
Improvements to packages

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1160]
When exporting packages:
- Settings such as smart sprite sheets are not preserved. This also happens when using SpriteBuilder with git (not sure where/why this information isn't transferred).
- It would be super useful to be able set the default scaling per package. Otherwise, resources will be screwed up when importing a package if you changed the default asset 'scale from'.

**Comment by NickyWeber** [comment]
Can you elaborate on the first point? What kind of settings are you referring to?

**Comment by vlidholt** [comment]
To reproduce:
1. Create a new project
2. Add a new folder, add a couple of images to the folder, make the folder a smart sprite sheet
3. Upload the project to Github
4. Clone the project from Github
5. The cloned project will not have the folder marked as a smart sprite sheet

**Comment by NickyWeber** [comment]
@vlidholt I cannot reproduce this bug following your instructions. When I make the default ccbResources folder a smart spritesheet git will show me this change:

![bildschirmfoto 2014-12-02 um 13 28 16](https://cloud.githubusercontent.com/assets/5259653/5262543/4665a8c4-7a27-11e4-9c27-c64c03c3f9b0.png)

Looking good after cloning.

Do you have any global .gitignore rules kicking in?
