### ISSUE TITLE
[bug] Textfield forgets contents when through saving through command-s

### ISSUE THREAD

**Issue by matthijn** [spritebuilder/SpriteBuilder#118]
Well, the title explains it a bit. When you have selected a textfield and enter content's (I think any textfield in the right pane) 

![screen shot 2013-12-23 at 10 32 19](https://f.cloud.github.com/assets/1755544/1799993/3d398e54-6bb5-11e3-9217-74da6b5ae99f.png)

and you press cmd-s to save it "forgets" it's contents. If there was nothing there before it becomes empty, else it becomes the old value.

![screen shot 2013-12-23 at 10 32 32](https://f.cloud.github.com/assets/1755544/1799996/549811a6-6bb5-11e3-887a-c463913281b3.png)

**Comment by NickyWeber** [comment]
Is this error still occuring?
