### ISSUE TITLE
Reading floats not working in CCBReader on release build

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#119]
Building for release (adhoc) crash on:

`memcpy(&f, pF, sizeof(float));`

changed to this:

`memcpy(&f, self->bytes+self->currentByte, sizeof(float));`

and it works

**Comment by cyiss** [comment]
I came across the same problem.

http://forum.spritebuilder.com/t/ccbreader-readfloat-float-casting-problem/70

**Comment by jtwigg** [comment]
I recall making this fix too in the past.

**Comment by vlidholt** [comment]
This has now been fixed and pushed to Cocos2D.
