### ISSUE TITLE
Localisation Xcode strings importer

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1190]
Look at being able to import Xcode Localizable.strings into SB Strings.ccbLang

**Comment by Rotonen** [comment]
Additionally it would be peachy if this process would also work the other way, so you can work with SpriteBuilder and export the Localizable.strings file for your translators and then back into a Strings.ccbLang.

Alternatively Spritebuilder could just use the Localizable.strings directly as its i18n backend as there are Apple-made and Apportable-made code paths (part of UIKit) for it already and that'd remove duplicated effort from the project?
