### ISSUE TITLE
Reset SpriteBuilder

### ISSUE THREAD

**Issue by MKGitHub** [spritebuilder/SpriteBuilder#12]
What custom templates and settings?

![screenshot 2013-11-05 at 22 35 15](https://f.cloud.github.com/assets/535550/1477877/02a7389e-4663-11e3-93da-268f137e3d53.png)

**Comment by jtwigg** [comment]
I'll take this.

Can you clarify. Are you saying 
a) there are no custom templates and settings, therefore the message is irrelevant?
b) What specifically are the custom templates and settings that are being undone?

**Comment by vlidholt** [comment]
The forth tab on the right side is templates. Currently only particle systems are supported for this feature, but it allows you to add your own templates. Resetting sprite builder will restore the default templates (and in the future any other custom settings).
