### ISSUE TITLE
Adding CCScrollView as CCTableView without setting content node in editor.

### ISSUE THREAD

**Issue by matthijn** [spritebuilder/SpriteBuilder#120]
I think this is a bug. I'm trying to create a tableview. In the editor itself there is no table view yet. So I thought, let's drag in a CCScrollView, since CCTableView is a direct descendant and set the custom class to CCTableView.

![cctableview](https://f.cloud.github.com/assets/1755544/1806560/17bf9f3e-6cb3-11e3-84cf-5de71ef164d9.png)

However, in the init of the CCTableView a special "contentNode" is set. However, when loading from CCB the contentNode is overwritten after the init of CCTableView by the CCBReader even when the "Content node" is set as NULL in the editor. 

![settings](https://f.cloud.github.com/assets/1755544/1806562/1eab997e-6cb3-11e3-9fe2-991ecbe1232a.png)

This overwrites the CCBTableView's content node and breaks the table view (e.g nothing get's displayed). 

I've added a screenshot with the stacktrace where it goes wrong for convenience.

![stacktrace](https://f.cloud.github.com/assets/1755544/1806565/48e61098-6cb3-11e3-831a-7a80f7ad0d6d.png)

edit: 

It looks like the setting of the content node is blocked through the constructor of CCTableView, but not through the setter itself.

**Comment by vlidholt** [comment]
Currently, the CCTableView is not supported for SpriteBuilder, I would recommend to instead build your CCTableView from code. This will be fixed in later versions of SpriteBuilder.
