### ISSUE TITLE
Adding child node for CCLabelTTF does not work

### ISSUE THREAD

**Issue by leszek-s** [spritebuilder/SpriteBuilder#121]
I have CCLabelTTF on my scene and I'm trying to add another CCLabelTTF as child of the first label but it has no effect.

**Comment by vlidholt** [comment]
Currently you cannot add child nodes to CCLabelTTF. Instead, use a CCNode that you add at a higher level and add both the CCLabelTTF and your other node to the CCNode. This should solve most of the cases where you want to add children to a label.

**Comment by leszek-s** [comment]
Thanks for the tip. For my needs I just wrote addChild in code to accomplish what I was trying to do and it works fine. The reason why I wanted to add one label as a child to other label in the first place was the abillity to set the child label position relatively to the parent label in % (100 or 0%) of parent label so later I could easily manage labels/sprites/nodes position one below other automatically when I add more text to the parent label.
