### ISSUE TITLE
"Semantic issue (Implicit declaration of function 'bridge_getEnv' is invalid in C99)" is shown when user tries to run an empty project on an android device.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1211]
1. Launch SpriteBuilder.
2. Make an empty project.
3. Publish the empty project.
4. Open the project in Xcode.
5. Select android device on the Xcode and run the project on it.
   
   -- Result: "Semantic issue (Implicit declaration of function 'bridge_getEnv' is invalid in C99)" is shown when user tries to run an empty project on an android device.

Build: SB Version: 1.3.6
Device A:
Xcode: 6.1
Mac OS X: 10.10.0
Device: Note2/4.1.1

Device B: 
Xcode: 6.1
Mac OS X: 10.9.5
Device: Note2/4.1.1

Project Link: https://drive.google.com/a/werplay.com/file/d/0B5KeRaV3CWUaZlU4RTNyTWNWVFU/view

![screen shot 2014-12-09 at 3 17 15 pm](https://cloud.githubusercontent.com/assets/8393830/5355874/ea5c4686-7fb8-11e4-8778-db386adc85e6.png)

**Comment by rkachowski** [comment]
The version of cocos2d bundled in the template with spritebuilder needs to be updated.

**Comment by sana20** [comment]
This issue was re-occurring.

Build: SB Version: 1.3.6

Device A:
Xcode: 6.1
Mac OS X: 10.10.0
Device: Nexus 6/5.0.

**Comment by jeffbaumes** [comment]
I also see this issue, SB 1.3.6, Xcode 6.1.1, Mac 10.10.1.

**Comment by rkachowski** [comment]
This no longer occurs with new projects, older projects need to be migrated to a more recent version of cocos2d
