### ISSUE TITLE
Lexical or preprocessor issue (OALSimpleAudio.h file not found) error is observed when user tries to run the headless project on an android device.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1216]
1. Launch Github.
2. Clone the project to the desktop through this link : https://github.com/cocos2d/cocos2d-swift/tree/develop
3. Open the project through finder.
4. Open cocos2d-tests-android folder and open Headless.xcodeproj in Xcode.
5. Plugin an android device and set the target for the project in Xcode as Headless>devicename.
6. Run the project on the device.
   
   -- Result: Lexical or preprocessor issue (OALSimpleAudio.h file not found) error is observed when user tries to run the headless project on an android device.

**Mac OS X:** 10.10.0
**XCode:** 6.1
**Android Device:** Nexus 5/5.0

![screen shot 2014-12-10 at 1 52 06 pm](https://cloud.githubusercontent.com/assets/8393830/5373204/078667c0-8075-11e4-84e0-a4e279624085.png)

**Comment by NickyWeber** [comment]
Did you recursively update the submodules?
`git submodule update --init --recursive`

**Comment by sana20** [comment]
@NickyWeber no i just cloned the project for the very first time on a new mac from the url given in the issue.

**Comment by NickyWeber** [comment]
The readme also suggests using: `git clone --recursive https://github.com/cocos2d/cocos2d-swift.git`
Please retry.

**Comment by sana20** [comment]
@NickyWeber i performed it just now by this git clone --recursive command and now this issue is observed when we run the project on an android device : https://github.com/spritebuilder/SpriteBuilder/issues/1211

**Comment by rkachowski** [comment]
This is resolved on latest cocos2d
