### ISSUE TITLE
Objective-C++ compile errors due to C++ keywords being used as variable names

### ISSUE THREAD

**Issue by davidtsai** [spritebuilder/SpriteBuilder#1220]
Using the SpriteBuilder Android plugin to build from xcode you are unable to compile any *.mm file that includes cocos2d.h.

In particular, the keyword "namespace" is being used as a variable name in various places in BridgeKitV3.  The fix should be relatively simple to rename the variable.

**Comment by rkachowski** [comment]
BridgeKitV3 has been removed from the latest plugin, issues resulting from it shouldn't exist anymore - please create a new issue if problems arise.
