### ISSUE TITLE
Bugs in default Xcode projects created by SB

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#124]
I noticed that xcode project generated by spritebuilder does not have OpenAL in header paths by default therefore writing #import "OALSimpleAudio.h" is not working out of the box. I suggest to add "Source/libs/cocos2d-iphone/external/ObjectAL" (recursive) to Header Search Paths for generated xcode project. Also I noticed that some paths to folders in generated xcode project are broken for example Resources group in project has a full path set by default to Examples directory which was not generated by SpriteBuilder and does not exist.

**Comment by jtwigg** [comment]
Should be resolved.
