### ISSUE TITLE
Semantic issue (No instance selector "stuff" is visible in current translation unit) and Parse issue (unexpected "@" in program) are observed when user adds the code line for bridgekit in the activity.m file 

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1243]
1. Launch sprite builder.
2. Make an empty project.
3. Publish the project.
4. Open the project in XCode.
5. Run the project on an android device.
   
   -- Observe: The project runs correctly on the android device.
6. Go to Source>Platform>Android>activity.m file in Xcode of the project.
7. Write this line in the activity.m file (@bridge stuff = stuff; )
8. Save the project.
9. Now run the project on an android device.
   
   -- Result: Semantic issue (No instance selector "stuff" is visible in current translation unit) and Parse issue (unexpected "@" in program) are observed when user adds the code line for bridgekit in the activity.m file 

Project Link: https://drive.google.com/file/d/0B23s5OMd3iivS3VtZEZweUhRNnc/view?usp=sharing
Build: 1.4.0-beta.3
Mac OS: 10.10.1
XCode version: 6.1 

![error](https://cloud.githubusercontent.com/assets/8393830/5514066/92d25082-8840-11e4-8c0e-e6a883570c3e.png)

**Comment by rkachowski** [comment]
BridgeKit has been removed from the plugin and replaced with various other frameworks. The most recent SpriteBuilder template projects don't require this anymore.
