### ISSUE TITLE
Invalid project file error is displayed when user tries to open a project in sprite builder with copy appended to its name.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1245]
1. Launch sprite builder.
2. Make a new project. (an empty one it can be)
3. Publish the project.
4. Now go to the finder where this project is present and make a copy of this project in the same directory.
5. Open the project with copy appended to its name.
   
   -- Result: Invalid project file error is displayed when user tries to open a project in sprite builder with copy appended to its name.

Video Link: https://drive.google.com/file/d/0B23s5OMd3iiva3MzS2FzVVVTcEk/view?usp=sharing
Project Link: https://drive.google.com/file/d/0B23s5OMd3iivN21yTUdOV0hvckU/view?usp=sharing
Build: 1.4.0-beta.3
Mac OS: 10.10.1
XCode version: 6.1

**Comment by KristenY** [comment]
I think this is acceptable behavior for now - they should just copy it to a different directory for this use case.
