### ISSUE TITLE
Java Jar Builder Error (Cannot find framework at path /Library/SBAndroid/Application Support/Developer/Shared/Xcode/Platforms/Android.platform/Developer/SDKs/SBAndroid.sdk/System/Library/Frameworks/System/Library/Frameworks/BridgeKitV3.framework) is displayed when user tries to run an empty project on android device.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1250]
1. Launch Sprite builder.
2. Make an empty project.
3. Publish it.
4. Open it in Xcode.
5. Run it on an android device through XCode.
   
   -- Result: Java Jar Builder Error (Cannot find framework at path /Library/SBAndroid/Application Support/Developer/Shared/Xcode/Platforms/Android.platform/Developer/SDKs/SBAndroid.sdk/System/Library/Frameworks/System/Library/Frameworks/BridgeKitV3.framework) is displayed when user tries to run an empty project on android device.

Project Link: https://drive.google.com/file/d/0B23s5OMd3iivdm1LeUZjenZ3blU/view?usp=sharing
Sprite Builder Version: 1.4.0-beta.3
Android Build: SBAndroidPlugin1-spritebuilder-bridgekit-8a276d6435a8820a6764dff65abdb6deb7f20ecd_9cf65b0044647f86
Mac OS: 10.10
XCode: 6.1

![screen](https://cloud.githubusercontent.com/assets/8393830/5534620/1bca35e2-8a87-11e4-91b6-3d1552f15b8d.png)

**Comment by sana20** [comment]
This issus also occurrs when we use the android plugin build: SBAndroidPluginDemo-spritebuilder-androidplugin-demo-8a276d6435a8820a6764dff65abdb6deb7f20ecd_c75d22626dfbd05d

**Comment by rkachowski** [comment]
This issue occurs when using a version of the SBAndroidPlugin that doesn't offer BridgeKitV3 on a project that requires it (an older cocos project / version of spritebuilder). Additionally, #1292 supercedes this issue - closing as N/A.
