### ISSUE TITLE
Can't build develop branch...

### ISSUE THREAD

**Issue by iMobCoding** [spritebuilder/SpriteBuilder#1251]
Like title says, can't build latest develop branch 84e91bd92f2be5760627897244f10dba218e81ef. Something with code signing I think. Here is the error:

```
** BUILD FAILED **

The following build commands failed:
    PhaseScriptExecution Code\ Signing build/SpriteBuilder.build/Release/SpriteBuilder.build/Script-83957E671A432C8600134002.sh
(1 failure)
Traceback (most recent call last):
  File "./build_distribution.py", line 219, in <module>
    sys.exit(build_distribution.run())
  File "./build_distribution.py", line 49, in run
    self.build_distribution(args.version, args.sku, args.mode,  version_info, args.private_key)
  File "./build_distribution.py", line 73, in build_distribution
    self.compile_project(version, product_name, mode, private_key)
  File "./build_distribution.py", line 116, in compile_project
    subprocess.check_call(build_command.format(xcconfig=product_name, private_key=private_key, sandboxed_mode_define=sandboxed_mode_define, version=version), shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/bin/xcodebuild             -target SpriteBuilder             -configuration Release             -xcconfig "SpriteBuilder.xcconfig"             SBPRO_PRIVATE_KEY="None"             SB_SANDBOXED_MODE=SB_NOT_SANDBOXED            SB_VERSION=1.4            build' returned non-zero exit status 65

```

**Comment by rkachowski** [comment]
The project builds on develop at 2eed171 - closing as fixed.

**Comment by iMobCoding** [comment]
Well, it still doesn't build for me. Tested with the latest develop 583c6d4728e8e69495931a2420aec260f40217b5.

Ok, I took some time to find the latest develop commit that builds for me and it's b059608d7426b54b012a46b717f4141e4fa5cf02. The next one 2aa603c9f9d372ab980f43a41d3c13a5b6f1b269 doesn't build. Attached image from that build attempt: 

![screen](https://cloud.githubusercontent.com/assets/1320690/5693893/3ab998c8-9935-11e4-9e98-3593893a3982.jpg)

I have to say that my directory structure includes some names with spaces and underscores, so maybe that could be a problem, don't know really.

**Comment by rkachowski** [comment]
The image you posted seems to miss why the command failed. The CI server is building develop on every push, and there is no issue with compilation.

**Comment by iMobCoding** [comment]
I am really not an expert in building process. I just know that it worked for me up to https://github.com/spritebuilder/SpriteBuilder/commit/b059608d7426b54b012a46b717f4141e4fa5cf02 and that it doesn't work from https://github.com/spritebuilder/SpriteBuilder/commit/2aa603c9f9d372ab980f43a41d3c13a5b6f1b269. I believe it works in your environment. But did you try with different directory structure? Clone the repository in something like "/Test 123/_SprBuilder/" and try again please...
