### ISSUE TITLE
Nothing happens when user adds a node under the light node and publishes it in sprite builder and runs it in XCode. 

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1253]
1. Launch Sprite Builder.
2. Make a new project.
3. Add a new node to the project and add an image to that node.
4. Now add scroll view to the mainscene.ccb and add that new node to this scroll view.
5. Add a light node to mainscene.ccb and drag the scroll view beneath the light node.
6. Publish the project and run the project in XCode.
   
   -- Result: Nothing happens when user adds a node under the light node and publishes it in sprite builder and runs it in XCode. 

Project Link: https://drive.google.com/file/d/0B23s5OMd3iivTW9DQ2xYM0x4N3M/view?usp=sharing
Video Link: https://drive.google.com/file/d/0B23s5OMd3iivaHJSLTR5cE1VNG8/view?usp=sharing
SpriteBuilder Version: 1.4.0-beta.3
XCode: 6.1
Mac OS: 10.10.1

**Comment by khanbhai89** [comment]
This issues is still occurring on SB 1.4.8-rc.0 on:

Mac OS X: 10.9.5.
XCode: 6.1.

**Comment by sana20** [comment]
This issue is still occurring. 
Mac OS X: 10.10.1
XCode: 6.1.
SBBuild: SB 1.4.8-rc.0
SBAndroid Build: SBAndroidPluginStarter-9ac08c84

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.4.9.-rc.0 on Mac OS X:10.9.5.

**Comment by Shahidwerplay** [comment]
This issue is fixed. 

Mac OS X 10.10.0
SB Version 1.4.9.
XCode 6.2
