### ISSUE TITLE
Semantic issue (Use of undeclared identifier 'UISwipeGestureRecognizer') is observed when user tries to run 2048 demo project on an android device.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1260]
1. Launch sprite builder.
2. Make 2048 part 1 and part 2 following the links below:
   https://www.makeschool.com/gamernews/384/build-your-own-2048-with-spritebuilder-and-cocos2d
   https://www.makeschool.com/gamernews/387/build-your-own-2048-with-spritebuilder-and-cocos2d?source=mgwu
3. Publish on the sprite builder.
4. Run the project in xcode.
   
   -- Observe: The project runs fine on the ios simulator.
5. Run the project on an android device.
   
   -- Result: Semantic issue (Use of undeclared identifier 'UISwipeGestureRecognizer') is observed when user tries to run 2048 demo project on an android device.

![screen shot 2014-12-30 at 2 31 12 pm](https://cloud.githubusercontent.com/assets/8393830/5577325/bfacb612-8fc3-11e4-92fb-3e13ec0387d5.png)

Project Link: https://drive.google.com/file/d/0B23s5OMd3iivbjE3b2o2S0YzeGc/view?usp=sharing
Mac OS X: 10.10.1
XCode: 6.1
Sprite Builder Version: 1.4.0-beta.3

**Comment by ebrodzki** [comment]
This is an old tutorial that has not been updated with the changes necessary when UIKit was removed as a dependency from cocos2d/when it was removed from the android side.

**Comment by sana20** [comment]
This issue is fixed.

SpriteBuilder-1.4.7 
Mac OS X: 10.10.1
XCode: 6.2.
Device Nexus 6/5.0.1

**Comment by sana20** [comment]
As this issue is duplicate of https://github.com/spritebuilder/SpriteBuilder/issues/1304 issue so closing it down.
