### ISSUE TITLE
reduce friction of using CCLabelBMFont within SpriteBuilder

### ISSUE THREAD

**Issue by ginobean** [spritebuilder/SpriteBuilder#1267]
Just spent a couple hours trying to get CCLabelBMFont to work with SpriteBuilder and so far, have been unsuccessful. In contrast, I don't recall having any issues using CCLabelBMFont with CocosBuilder..

What should have taken me a couple minutes to set up (adding a CCLabelBMFont to a scene) has so far taken me a couple hours (and still no success).

I think this should be a pretty high priority as adding a bitmap label is used in pretty much _every_ non-trivial game.

**Comment by collinjackson** [comment]
I'm sorry that this has been difficult for you. Can you give more details about what you'd like to see changed?

**Comment by cocojoe** [comment]
@ginobean Please check out the video I made on the subject, if it doesn't work for you as demonstrated please let me know on the SpriteBuilder forum thanks.

http://www.spritebuilder.com/blog/adding-a-bitmap-font-with-spritebuilder

**Comment by ginobean** [comment]
Thanks, that was helpful. :). 

BTW, I've recently written a little bash script that will automatically generate the required .bmfont structure from a GlyphDesigner .GlyphProject file.

[Bash script to generate CCLabelBMFont bmfont files for use with SpriteBuilder using GlyphDesigner's command line tool](http://forum.spritebuilder.com/t/bash-script-to-generate-cclabelbmfont-bmfont-files-for-use-with-spritebuilder-using-glyphdesigners-command-line-tool/2690/1)
