### ISSUE TITLE
Integrated Graphics vs Discreet

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1269]
Interesting user request regarding heat (and power consumption) of SpriteBuilder on laptop when using discreet GPU. 

I don't feel that SpriteBuilder needs the full power of discreet GPU to render. My laptop only has integrated and just fine.

This can be simply tweaked with flag in plist
https://developer.apple.com/library/mac/qa/qa1734/_index.html

Thoughts?

**Comment by ryanbourneuk** [comment]
+1 , less heat output sounds great!

My MacBook also only has integrated graphics and it's working well, so I think the assumption that newer MacBooks would be able to handle it without discreet GPU is quite reasonable.
