### ISSUE TITLE
Copy/paste of keyframes not always working correctly

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#127]
Keyframes are not always correctly copy-pastable. The reason is likely that some property on the keyframes are not set correctly when they are created.

Keyframes can be created in a number of different ways, so some of these paths may be incorrect:
- Loading a ccb-file.
- Option clicking the timeline
- Using a menu option
- Pasting a keyframe
- Transforming an object (when there are already keyframes set for that property)

**Comment by jtwigg** [comment]
Should be fixed with latest checking.
