### ISSUE TITLE
Editing CCLightNode's "Half Radius" does not pop up "invalid value range" dialog

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#1279]
If you enter a value not in the range 0.0 to 1.0 to a light node's "Half Radius" box, the text field remains selected (and you can't press TAB to move to the next text field either). 

It seems there ought to be a message box that tells me that the value is out of range. But this dialog doesn't appear, which affects the entire UI in a strange way.

For instance, while the value is outside range I can't even select other nodes anymore, save, or do any other editing task.

Tried to check if the message box does appear but simply isn't in the foreground or on a different monitor, but couldn't confirm that so I don't think that's the case here.

**Comment by Shahidwerplay** [comment]
This issue is fixed.

Mac OS X: 10.10.0
SB Version 1.4.9
Xcode 6.2
