### ISSUE TITLE
light node shows animatable properties that can't be animated in timeline

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#1280]
Looks like all additional properties show up in timeline (by accident, or just work in progress?). One can't create keyframes for those properties, so they are not animatable:

![screen shot 2015-01-07 at 15 00 12](https://cloud.githubusercontent.com/assets/214599/5646554/f140250e-967d-11e4-9b7d-98a139a2d7e4.png)

**Comment by vlidholt** [comment]
Have you tried to option-click?

**Comment by LearnCocos2D** [comment]
Indeed, that does create keyframes.
