### ISSUE TITLE
New projects contain warnings

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1285]
Newly created project generates warnings when compiled.

![screen shot 2015-01-08 at 10 24 37 am](https://cloud.githubusercontent.com/assets/1539812/5667965/abac72f6-9720-11e4-96f6-d0ad5e673ec1.png)

**Comment by rkachowski** [comment]
@vlidholt Should this issue be in the cocos2d project?

**Comment by Shahidwerplay** [comment]
This issue is fixed.

Mac OS X 10.10.0
SBVersion 1.4.9.
XCode 6.2
