### ISSUE TITLE
Package APK Tool Error is observed when user tries to run an empty project on an android device.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1292]
1. Launch Sprite Builder.
2. Make a new project.
3. Build the project.
4. Open the project in XCode.
5. Run the project on an android device.
   
   -- Result: Package APK Tool Error is observed when user tries to run an empty project on an android device.

Build: SpriteBuilder-1.4.0-rc.0
Android Plugin: SBAndroidPlugin1-spritebuilder-bridgekit-acbb87b27b395b9862e64b0037cb2ace488ff1ae_717d95b8bc5827bc.pkg
Project Link: https://drive.google.com/file/d/0B23s5OMd3iivbnM0MFZDZEtlMWc/view?usp=sharing

Mac OS X: 10.10.1
XCode: 6.1

![screen shot 2015-01-12 at 5 31 36 pm](https://cloud.githubusercontent.com/assets/8393830/5703007/5b2e4dfc-9a15-11e4-9680-43f7f333e3d9.png)

**Comment by rkachowski** [comment]
+1  I am also receiving this error with the same components

**Comment by sana20** [comment]
This issue is re-occurring.

Build: SpriteBuilder-1.4.0-rc.0
Android Plugin Demo: SBAndroidPluginDemo-spritebuilder-androidplugin-demo-680e6e21a31a12f6f783d13fd22ecd33866ca150_2bd593b8daaca4e0
Android Plugin Core: SBAndroidPlugin1-spritebuilder-bridgekit-680e6e21a31a12f6f783d13fd22ecd33866ca150_80d8050f41a33e60

Mac OS X: 10.10.1
XCode: 6.1

**Comment by rkachowski** [comment]
This has been resolved

**Comment by kishan28** [comment]
Hi rkachowski am also facing same issue,  will you suggest me how to resolve this
