### ISSUE TITLE
Device is not displayed when user attaches a device to the Mac.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1293]
1. Install SBAndroidPluginDemo-spritebuilder-androidplugin-demo-acbb87b27b395b9862e64b0037cb2ace488ff1ae_09f20b2681a4f933.pkg
2. Open SpriteBuilder-1.4.0-rc.0.
3. Create an Empty Project.
4. Open it in XCode.
5. Attach an Android device.
6. Check for Android device Target in XCode build option.
   
   -- Result: Device is not displayed in selecting targets when user views them.
   
   This happened 3/3 times.

Build: SpriteBuilder-1.4.0-rc.0 and SBAndroidPluginDemo-spritebuilder-androidplugin-demo-acbb87b27b395b9862e64b0037cb2ace488ff1ae_09f20b2681a4f933.pkg

Mac OS X: 10.9.5.
XCode: 6.0.

![screen shot 2015-01-12 at 5 41 34 pm](https://cloud.githubusercontent.com/assets/7450007/5703276/7503fd8c-9a86-11e4-8c73-faf45b71b000.png)

**Comment by rkachowski** [comment]
Android devices are detected with the latest plugin
