### ISSUE TITLE
"Unfortunately project has stopped" pop appears on the device when the user runs the project on Android Lollipop devices.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1296]
1. Launch SpriteBuilder.
2. Make a new angry bird project.
3. Publish the project.
4. Open the project in XCode.
5. Run the project on an android lollipop device.
   
   -- Result: "Unfortunately project has stopped" pop appears on the device when the user runs the project on Android Lollipop devices.

Project: https://drive.google.com/file/d/0B23s5OMd3iivd0J5eTBacHJRZWc/view?usp=sharing

Build: SpriteBuilder-1.4.0-beta.4
Android Plugin Enterprise : SBAndroidEnterprise
Android Plugin Demo : SBAndroidPluginDemo-spritebuilder-androidplugin-demo-6b236200a75214688ab81f9f9632af082242e26f_7886e753c85ab009
Android Plugin Core : SBAndroidPlugin1-spritebuilder-bridgekit-6b236200a75214688ab81f9f9632af082242e26f_f9c8b664a67ceb4c

Mac OS X: 10.10.1
XCode: 6.1
Device1: Nexus 5/5.0. , it happened 3/3 times.
Device2: Nexus 10/5.0.1. , it happened 3/3 times.

**Comment by khanbhai89** [comment]
This issue is fixed on SpriteBuilder-1.4.0-rc.0.1

Mac OS: 10.10.1
Xcode: 6.0.

**Comment by ghost** [comment]
When will SpriteBuilder-1.4.0-rc.0.1 be released?

**Comment by KristenY** [comment]
@appilities We submitted the latest RC to the Mac App Store, and are hoping for it to be available in the next few days.  Thanks for your patience!

Additionally, Android L should work with the latest build available on spritebuilder.com and the latest Android Plugin in the store:  https://store.spritebuilder.com/products/spritebuilder-android-plugin-starter
