### ISSUE TITLE
Keyframe context menu is disabled.

### ISSUE THREAD

**Issue by jtwigg** [spritebuilder/SpriteBuilder#13]
It never appears to be enabled, even when selecting a node for alteration.

**Comment by vlidholt** [comment]
The context menu on nodes and keyframes are not yet implemented, with the exception for clicking between keyframes to set the easing. The context menu needs to be implemented (more options may be needed as well) and possibly context menus in other places too.

**Comment by jtwigg** [comment]
I will do.

**Comment by jtwigg** [comment]
Fixed.
