### ISSUE TITLE
Fix sound import in SB

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#130]
Earlier SB used the QuickTime api to check if the imported sounds were longer than 15 seconds, but these apis have been deprecated and are no longer allowed on AppStore.

Need to find another way to check this and select caf or mp4 format appropriately. There is a warning in the code in ResourceManager.m at the point of this.

**Comment by jtwigg** [comment]
Initial screenshot of audio file preview. Needs review.

![screen shot 2014-01-06 at 10 47 05 am](https://f.cloud.github.com/assets/1237233/1852934/17336212-7703-11e3-919d-d1b849aa862e.png)

**Comment by vlidholt** [comment]
Looks good! Is the play button changing to 'Stop' when you play the sound (this may be important for longer sounds)?

Also, I think we can remove the Volume, sample rate and channels to make it a bit cleaner.

**Comment by cocojoe** [comment]
Looks great, is there a loop option? Sometimes handy for short samples.

On 6 January 2014 18:53, Viktor Lidholt notifications@github.com wrote:

> Looks good! Is the play button changing to 'Stop' when you play the sound
> (this may be important for longer sounds)?
> 
> Also, I think we can remove the Volume, sample rate and channels to make
> it a bit cleaner.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/apportable/SpriteBuilder/issues/130#issuecomment-31675246
> .

## 

Martin

**Comment by jtwigg** [comment]
needs to resize properly.

**Comment by jtwigg** [comment]
Should resize properly now
