### ISSUE TITLE
Portrait scene is not displayed properly when user runs it on iOS simulator.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1305]
1. Launch Application.
2. Create a new project.
3. Change orientation from Landscape to portrait.
4. Add gradient on whole scene.
5. Publish and Run on iOS simulator.
   
   -- Result: Gradient is displayed in Landscape mode where-as screen itself is resized as Portrait mode.
   
    This happened 3/3 times.

Found on SpriteBuilder-1.4.0-rc.0.zip on::

Mac OS X: 1.9.5.
XCode: 6.0.
Target: Project iOS simulator > iPhone 6.

**Comment by rkachowski** [comment]
![](http://puu.sh/f3tM1/7240e8a2e2.png)

The appearance is consistent between spritebuilder and the ios simulator.
