### ISSUE TITLE
JAVA JAR builder error is displayed when user builds a project with android starter plugin

### ISSUE THREAD

**Issue by shahzad12** [spritebuilder/SpriteBuilder#1306]
1. Install Starter plugin from SpriteBuilder store. 
2. Create an empty project. 
3. Build Project. 

--Result: Error: Cannot find framework at path /Library/SBAndroidStarter/Application Support/Developer/Shared/Xcode/Platforms/Android.platform/Developer/SDKs/SBAndroid.sdk/System/Library/Frameworks/System/Library/Frameworks/BridgeKitV3.framework is displayed. 

This happened 3/3 times. 

Project Link: https://drive.google.com/file/d/0BygRXwc8WV8nTEpVTWZEMGI0bGc/view?usp=sharing

Android Device: Nexus 5/5.0
Device A: 

MAC OS 10.10.1
Xcode 6.0

![screen shot 2015-01-22 at 10 07 14 pm](https://cloud.githubusercontent.com/assets/10218416/5860494/6fcc559e-a283-11e4-9ab6-f56221ad0d63.png)

**Comment by khanbhai89** [comment]
This is happening on this Mac only where as it is not happening on any other Mac.

Other Mac Details:

Device B:
Mac OS X: 10.9.5.
XCode: 6.0.
Device: SGS4/4.4.2.

Device C:
Mac OS X: 10.10.1
XCode: 6.1.
Device: Nexus 5/5.0.1.

**Comment by sana20** [comment]
This issue is happening when the user runs headless project on the following Mac.

Mac OS X: 10.10.1
XCode: 6.1.
Device: Sony Xperia Z/4.3.
Android Build: SBAndroid-Starter-a436a938 (Available on store)

**Comment by khanbhai89** [comment]
This also happens with Gameoflife project when user tries to port it on android.

Mac OS X: 10.9.5.
XCode: 6.0.
Device: SGS4/4.4.2.
Android Build: SBAndroid-Starter-a436a938 (Available on store) & SpriteBuilder-1.4.0-rc.0

Project: https://drive.google.com/file/d/0BygRXwc8WV8nbktReTI2LTJnSWs/view?usp=sharing

**Comment by mattcn** [comment]
I have also got this issue.

Mac OS X: 10.10.1
Xcode: 6.1
Device. Samsung Galaxy S4
Android Build: SBAndroid-Starter-a436a938
SB Version: 1.4.0
SB Revision: 10891b8575

**Comment by khanbhai89** [comment]
This also happens with Gameoflife project when user tries to port it on android.

Mac OS X: 10.10.1.
XCode: 6.0.
Device: HTC One/4.1.2.
Android Build: SBAndroidPluginIndie-spritebuilder-androidplugin-indie-222d70628f94220b5b06356952654feb15175329_a6c948f5bf518c48.pkg & SpriteBuilder from Mac Store 1.4.7.

**Comment by KristenY** [comment]
@khanbhai89 Could you please clarify:
1. whether this happens with an empty project,
2. whether this happens with 'Gameoflife' when it is recreated from scratch with SB 1.4.7 and the latest Android plugin we sent, and
3. whether this happens with any of the other non-empty projects you try making?
Thanks!

**Comment by shahzad12** [comment]
@KristenY  
1. whether this happens with an empty project?

Yes this happens for empty project as well as normal project. 
1. whether this happens with 'Gameoflife' when it is recreated from scratch with SB 1.4.7 and the latest Android plugin we sent. ?

This happens when you try to build an old project irrespective of the fact that it is an empty project or a normal mini game. When ever you try to build an old project this error occurs and when you create a new project this never happens. we are being able to build the project. 
1. whether this happens with any of the other non-empty projects you try making?

This happens for all the projects that are being built on some previous version and u try to build them with version. However no error is observed when you make a new project from scratch.
