### ISSUE TITLE
Node jumps when dragged 

### ISSUE THREAD

**Issue by NickyWeber** [spritebuilder/SpriteBuilder#1310]
If you start dragging a node on stage it will jump to the bottom left, maybe 0.0, 0.0.

![e7la328](https://cloud.githubusercontent.com/assets/5259653/5873476/2ab26d94-a2f7-11e4-8fae-a1fcf39fe38d.gif)

**Comment by slembcke** [comment]
Hmm... This is in the develop branch? I may have broken this yesterday when merging. I fixed an issue with the snapping due to calling a deprecated method. It worked fin in testing though.

**Comment by NickyWeber** [comment]
Yes develop now but it was on the v4 branch and is broken for a bit longer than yesterday. Didn't do a bisect yet.

**Comment by rkachowski** [comment]
Appears to be fixed in latest develop
