### ISSUE TITLE
Blank screen is displayed on device when tries to port Headless project to android device

### ISSUE THREAD

**Issue by shahzad12** [spritebuilder/SpriteBuilder#1319]
1. Clone project https://github.com/cocos2d/cocos2d-swift/tree/develop/cocos2d-tests-android/Headless.xcodeproj.
2. Open the android test suite in cocos2d-tests-android/Headless.xcodeproj, build to an android device.
3. Build and run project. 

--Observe: Project is ported to device. (Expected)
--Result: Blank screen is displayed.
This happened 3/3 times. 

Console Log: https://drive.google.com/a/werplay.com/file/d/0BygRXwc8WV8nTzdPZTVSWlJ2Qm8/view?usp=sharing. 
Device A: 
MAC OS:10.10.1
Xcode: 6.0.

**Comment by rkachowski** [comment]
This is addressed on the latest develop
