### ISSUE TITLE
"Cannot find protocol declaration for 'CCDirectorDelegate' is generated when user tries to port Cocos 2D project to android.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1321]
1. Launch Application.
2. Clone https://github.com/cocos2d/cocos2d-swift/tree/develop/cocos2d-tests-android/Headless.xcodeproj.
3. Check out the develop branch of cocos2d-swift repo.  (Same instructions as for iOS tests - do git pull to get the latest, then git submodule update --init --recursive.)
4. Open the android test suite in cocos2d-tests-android/Headless.xcodeproj, build to an android device.
   
   -- Result: "Cannot find protocol declaration for 'CCDirectorDelegate' is generated when user tries to port Cocos 2D project to android.

Device A:

Mac OS X: 10.9.5.
XCode: 6.0.

Build: SpriteBuilder-1.4.0-rc.0 with SBAndroid-Starter-a436a938(from Spritebuilder store)
![screen shot 2015-01-29 at 4 35 02 pm](https://cloud.githubusercontent.com/assets/7450007/5957284/1e519f98-a7d9-11e4-8d26-0a1ec5e6c80c.png)

**Comment by rkachowski** [comment]
This is a known issue with cocos2d android support and will be fixed in the next update.
