### ISSUE TITLE
Apportable CLang Error is displayed when user tries to run a project implementing sound in it.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1325]
1. Launch Spritebuilder.
2. Make an empty project.
3. Publish it.
4. Open it in XCode.
5. Add a new group to the resources and name it Audio.
6. Copy an audio mp3 file to that folder.
7. Add this chunk of code to the mainscene.m file
   OALSimpleAudio *audio = [OALSimpleAudio sharedInstance];
   audio playEffect:@"1156.mp3";
8. Run the project on an ios simulator or an android device.
   
   -- Result: Apportable CLang Error is displayed when user tries to run a project implementing sound in it.

SB Version: 1.4.0
Android Plugin: SBAndroid-Starter-a436a938 (Available on store)
Mac OS X: 10.10.1
XCode: 6.1.
iOS simulator: iPhone 4S
iOS version: 8.0.
Device: Sony Xperia Z/4.3.

Project Link: https://drive.google.com/file/d/0B23s5OMd3iivUXF5b0xST0J2elU/view?usp=sharing

![bug](https://cloud.githubusercontent.com/assets/8393830/5974250/dae96d14-a826-11e4-8c0e-8c81a657fac7.png)

**Comment by rkachowski** [comment]
Can you please provide the source of your `MainScene.m` file? - There may be some kind of error here.

**Comment by rkachowski** [comment]
The source file you are using is not valid objective c and the compiler can't parse it.
