### ISSUE TITLE
SB v1.4.7: sometimes keyframe properties remain grayed out despite being exactly on the keyframe

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#1334]
As you can see in the image, node is selected, cursor is exactly above a scale keyframe, but scale properties are grayed out:

![screen shot 2015-02-05 at 12 10 20](https://cloud.githubusercontent.com/assets/214599/6059291/fede445c-ad2f-11e4-82d3-f70882a15e11.png)

This seems to happen easily. Create a timeline with 3 keyframes, edit the values for at least 1-2 keyframes, play the timeline in the editor (not sure if this is important). Then select the node, try to locate a keyframe and edit its properties. Chances are good that you can't because the property is grayed out.

I have observed this mainly with scale property, slim chance this is specific to scale but I suspect it affects most if not all properties.

**Comment by cocojoe** [comment]
Yes someone reported this to me, when I tested it happens if the node has physics enabled, not sure why this has suddenly happend.  There was a pull ages ago that disabled certain properties from the timeline when physics was enabled and this all worked correctly however it's as if now this is now applied to property panel.

**Comment by cocojoe** [comment]
You should also be able create Sprite Frame keyframes with Physics Enabled however this is no longer available either hmmm.

**Comment by cocojoe** [comment]
So had a look into this, I don't believe it's related to the issue reported to me (will raise that one separately). 

In your case you can generally click on the keyframe to edit it and this then unlocks the value in the inspector panel.

**Comment by rkachowski** [comment]
I can only reproduce this issue when there are physics nodes on the timeline, nothing else seems to cause problems

**Comment by LearnCocos2D** [comment]
PS: none of the nodes in question had physics enabled, the entire project was not using physics.

**Comment by cocojoe** [comment]
So I can recreate this at least, create a rotation keyframe at say seconds 0,1 and 2.  Then simply create a scale keyframe at any position other than 0.  It will then disable rotation inspector field.  However if you 'save' it will enable the field again.

**Comment by cocojoe** [comment]
Got to the bottom of this now, it's related to PR #1261 
This introduced a nice improvement to timeline rendering however what's happening is inspector value panel is no longer refreshed when moved.  

In the above when I create a scale keyframe, the inspector panel is refreshed correctly and it is correct to disable rotation as the timeline is not aligned with a rotation keyframe.  However if you move the timeline to a rotation keyframe position it remains disabled as there is no call to refresh inspector values.

Will resume this one tomorrow.
