### ISSUE TITLE
Custom class not found in ccbi

### ISSUE THREAD

**Issue by KingAndroid** [spritebuilder/SpriteBuilder#1348]
cocos2d-iphone/cocos2d-ui/CCBReader/CCBReader.m:1385
2015-02-10 10:15:23.271 Jumpy Ninja[14996:1855396] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '[CLASS] Could not create class named: "GameScene". in CCB file: "GameScene.ccbi"'
**\* First throw call stack:
(
    0   CoreFoundation                      0x00000001070bdf35 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000106d56bb7 objc_exception_throw + 45
    2   CoreFoundation                      0x00000001070bdd9a +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x00000001065345df -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
    4   Jumpy Ninja                         0x00000001039d44ab -[CCBReader readNodeGraphParent:] + 827
    5   Jumpy Ninja                         0x00000001039d7655 -[CCBReader readFileWithCleanUp:actionManagers:] + 245
    6   Jumpy Ninja                         0x00000001039d7cc1 -[CCBReader loadWithData:owner:] + 625
    7   Jumpy Ninja                         0x00000001039d82ea -[CCBReader nodeGraphFromFile:owner:parentSize:] + 330
    8   Jumpy Ninja                         0x00000001039d899f +[CCBReader load:owner:parentSize:] + 159
    9   Jumpy Ninja                         0x00000001039d8c85 +[CCBReader sceneWithNodeGraphFromFile:owner:parentSize:] + 133
    10  Jumpy Ninja                         0x00000001039d8b5f +[CCBReader loadAsScene:owner:] + 207
    11  Jumpy Ninja                         0x00000001039d8d82 +[CCBReader loadAsScene:] + 82
    12  Jumpy Ninja                         0x0000000103943538 -[AppController startScene] + 56
    13  Jumpy Ninja                         0x00000001039c8445 -[CCNavigationController directorDidReshapeProjection:] + 149
    14  Jumpy Ninja                         0x0000000103a2b4d4 -[CCDirectorIOS reshapeProjection:] + 212
    15  Jumpy Ninja                         0x0000000103a3451b -[CCGLView layoutSubviews] + 251
    16  UIKit                               0x0000000105239973 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 521
    17  QuartzCore                          0x00000001048b7de8 -[CALayer layoutSublayers] + 150
    18  QuartzCore                          0x00000001048aca0e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 380
    19  QuartzCore                          0x00000001048ac87e _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
    20  QuartzCore                          0x000000010481a63e _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 242
    21  QuartzCore                          0x000000010481b74a _ZN2CA11Transaction6commitEv + 390
    22  UIKit                               0x00000001051be54d -[UIApplication _reportMainSceneUpdateFinished:] + 44
    23  UIKit                               0x00000001051bf238 -[UIApplication _runWithMainScene:transitionContext:completion:] + 2642
    24  UIKit                               0x00000001051bdbf2 -[UIApplication workspaceDidEndTransaction:] + 179
    25  FrontBoardServices                  0x000000010a37d2a3 __31-[FBSSerialQueue performAsync:]_block_invoke + 16
    26  CoreFoundation                      0x0000000106ff353c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK** + 12
    27  CoreFoundation                      0x0000000106fe9285 __CFRunLoopDoBlocks + 341
    28  CoreFoundation                      0x0000000106fe9045 __CFRunLoopRun + 2389
    29  CoreFoundation                      0x0000000106fe8486 CFRunLoopRunSpecific + 470
    30  UIKit                               0x00000001051bd669 -[UIApplication _run] + 413
    31  UIKit                               0x00000001051c0420 UIApplicationMain + 1282
    32  Jumpy Ninja                         0x0000000103932957 main + 71
    33  libdyld.dylib                       0x0000000107c01145 start + 1
)

**Comment by KingAndroid** [comment]
This issue is issued on v1.4.7
When app has MainScene as default, this crash error issued.
I've changed class name from MainScene to GameScene, but same.

If I remove custom class from SB, then game not crash.
But can't access members and events.
Any solution?

**Comment by KingAndroid** [comment]
How can I change app bundle id on ios or package name android?
I think this issue is related with them.
I could launch app with old bundle id(org.cocos2d.~) successfully

**Comment by cocojoe** [comment]
Please raise this in the Forum http://forum.spritebuilder.com if you need some advice, I do not believe this is a bug.  Thanks

**Comment by KingAndroid** [comment]
Closed?

**Comment by KingAndroid** [comment]
any solution for crash bug then?

**Comment by cocojoe** [comment]
Please read my previous comment, mostly likely this is user error than an actual bug. Typically a class has not been added to the project correctly. Hence the Forum should be the first port of call, Git should typically be for confirmed bugs.  Thanks
