### ISSUE TITLE
"PBXCp error" is received when user tries to build and run the Crystals project on iOS simulator

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1356]
1. Launch Spritebuilder.
2. Clone the repo here:  https://github.com/spritebuilder/Crystals.spritebuilder.git; switch to branch 'android'
3. Open the project in terminal.
4. Open the XCode file.
5. Build and run the project on iOS simulator.

-- Result: "PBXCp error" is received when user tries to build and run the Crystals project on iOS simulator

Project Link: https://drive.google.com/file/d/0B23s5OMd3iivNlpwa3JTRkNtdlk/view?usp=sharing

Mac OS X: 10.10.1
XCode: 6.1.
Build: SpriteBuilder from Mac AppStore 
Android Plugin: SBAndroidPluginIndie-spritebuilder-androidplugin-indie-222d70628f94220b5b06356952654feb15175329_a6c948f5bf518c48.1

![screen shot 2015-02-16 at 12 42 32 pm](https://cloud.githubusercontent.com/assets/8393830/6208464/50c2500c-b56d-11e4-91c7-68ceb9ada476.png)

**Comment by NickyWeber** [comment]
Did you open the project in Spritebuilder and publish it?

**Comment by sana20** [comment]
@NickyWeber Did it just now and now this error is resolved now so i am closing down this ticket Thank you :)
