### ISSUE TITLE
Tree case-sensitivity with rename

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#136]
Minor issue, case sensitivity changes do not stick in the tree unless the string changes. 

e.g.

"Audio" to "audio" reverts back to "Audio"

Work around is

"Audio" to "audio_" to "audio"

Timeline renames seem to work correctly.

**Comment by vlidholt** [comment]
To clarify this happens in the project file view: 

![screen shot 2014-01-08 at 12 31 57 pm](https://f.cloud.github.com/assets/1539812/1872310/06c4ce82-78a4-11e3-97f1-cdbaa1d9314c.png)

Will move this issue up to 1.1
