### ISSUE TITLE
The joints are not working correctly when user implements them in a project and then tries to run the project on an android device or iOS simulator

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1370]
1. Launch Spritebuilder.
2. Drag and drop two bird images below the CCNode. 
3. Enable Physics of both the objects and make one static and the other dynamic.
4. Now drag and drop any type of joint under the joints section.
5. Link the joint with the objects.
6. Publish the project and open in XCode.
7. Run the project on the iOS simulator or an android device.
   
   -- Result: Both the birds stay on their place non of them falls or revolves around the other bird object hence the joints are not working correctly when user implements them in a project and then tries to run the project on an android device or iOS simulator

Project Link: https://drive.google.com/file/d/0B23s5OMd3iivd1JYUnRPMjU0aXM/view?usp=sharing

Mac OS X: 10.10.1
XCode: 6.1.
Device: Note 3/4.3.
Build: Spritebuilder 1.4.7 from Mac app store.
Build android: SBAndroidPluginStarter-sbandroid-starter-e24cb4abb394e1e8f0eac2f3e17bcb3102a55471_69ccb096d3fad9fb.pkg

**Comment by vlidholt** [comment]
The reason nothing is happening is that physics objects are only simulated if they are below a physics node in the node hierarchy. Add a physics node to the file and place the objects as its children and it should work as expected.
