### ISSUE TITLE
Can't select or move some but not all CCBFile nodes

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1378]
Creating a track level which is built from set piece nodes.

![screenshot 2015-02-25 10 38 56](https://cloud.githubusercontent.com/assets/928115/6369160/6c09a1ba-bcdb-11e4-9942-a4a582d66f3e.png)

The structure is flat, however not all nodes can be selected. Corner pieces can be if you get near the middle however long pieces can not be selected, if you manually select them in the timeline and then try to move them, they will become deselected.  

![screenshot 2015-02-25 10 39 14](https://cloud.githubusercontent.com/assets/928115/6369242/26d9678c-bcdc-11e4-9182-d70df005cbad.png)

Interestingly this my have happened after making some small changes to the straight track node if I drop a fresh piece into the track node it can be selected and moved.  

However regardless this is annoying.

**Comment by NickyWeber** [comment]
Another content size issue?

**Comment by cocojoe** [comment]
Could well be yeah.
