### ISSUE TITLE
Folder is not deleted from the finder folder even when user publishes the project again.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1382]
1. Launch Application.
2. Create a Folder A through resource View.
3. Add another Sub-Folder into Folder A named Folder B.
4. Add another Sub-Folder into Folder B named Folder C.
   -- Observe: All 3 folders are created correctly in the resource view. (Expected)
5. Publish the project.
6. Delete the folder A.
   -- Observe: It is deleted correctly in resource view when user deletes the folder. (Expected)
7. Publish the project.
   
   -- Result: Folder A is not deleted from the finder resource folder when user have already deleted it.
   
   This happened 3/3 times.

Build: SpriteBuilder-1.4.8-rc.0.zip

Mac OS X: 10.9.5.
XCode:  6.1.

**Comment by sana20** [comment]
This issue is still occurring on Build: SpriteBuilder-1.4.8-rc.0.zip with SBAndroidPluginStarter-9ac08c84

Mac OS X: 10.10.
XCode: 6.1.

**Comment by Shahidwerplay** [comment]
This issue is fixed.

SpriteBuilder-1.4.7
Mac OS X: 10.10.
XCode: 6.2.

**Comment by NoorFatima** [comment]
This issue is fixed.

SpriteBuilder-1.4.9
Mac OS X: 10.9.5

**Comment by Shahidwerplay** [comment]
This issue is fixed.

SpriteBuilder latest develop branch 2.0
Mac OS X: 10.10.0
