### ISSUE TITLE
Dragging multiple nodes BUG

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#1384]
In spritebuilder 1.4.7, when selecting multiple nodes (by holding shift), moving them causes them to move to random offscreen positions.

Lots of detail in the original SB Post:

http://forum.spritebuilder.com/t/dragging-multiple-nodes-bug-in-1-4-7/3183

**Comment by stuartcarnie** [comment]
I have seen this when looking at multiple selection too. Also, when moving multiple selected objects, keyframes are not correctly updated
