### ISSUE TITLE
Sprite Builder crashes when user download .wav sounds and drag drop it in sound's timeline section.

### ISSUE THREAD

**Issue by Shahidwerplay** [spritebuilder/SpriteBuilder#1385]
1. Launch Sprite Builder.
2. Download .wav sound from any website.
3. Drag and drop it on Sound's timeline section or tries to select multiple sound files in sound section.

--Result: Sprite Builder crashes when user download .wav sounds and drag drop it in sound's timeline section.

Build: SpriteBuilder-1.4.8-rc.0 
SB Android: SBAndroid Indie (SBAndroidPluginIndie-sbandroid-indie-704bb7c4b3507f7e).
Mac OS X: 10.10.
XCode: 6.1.
Device: Nexus 7(2013)/4.4.2.

Video Link: https://drive.google.com/file/d/0B5-RfBatv-b8SWVsaVQ5UlV0b0U/view?usp=sharing
Project link: https://drive.google.com/file/d/0B5-RfBatv-b8dGE3clpxN3pWSUk/view?usp=sharing

**Comment by stuartcarnie** [comment]
I'll push a fix for this shortly
