### ISSUE TITLE
Joints stop functioning when effects are applied on sprites.

### ISSUE THREAD

**Issue by Shahidwerplay** [spritebuilder/SpriteBuilder#1390]
1. Launch Application.
2. Make a new project.
3. Drag a physics node in the CCnode's timeline section.
4. Drag two sprites under the physics node and enable the physics of both of them, make one sprite static and the other one dynamic.
5. Choose any joint and link both the sprites to it. 
6. Click on the sprite(dynamic), click on +Adc to apply some effects, then select the Glass/Reflection/Refraction section and change normal map from null to any shape.
7. Publish the project and run on Xcode.  
8. Run the project on any android device.
   
   --Result: Joints stop functioning when effects are applied on sprites.

Spritebuilder version: 1.4.7. version of Spritebuilder 
SB Android: SBAndroidPluginStarter-9ac08c84

Device: LG G3/4.4.2.
Mac OS: 10.10
Xcode: 6.1

Project link: https://drive.google.com/file/d/0B5-RfBatv-b8RUtrRnBORjNKcms/view?usp=sharing

**Comment by sana20** [comment]
This issue is re-occurring on Build: SpriteBuilder-1.4.8-rc.0.zip with SBAndroidPluginStarter-9ac08c84 and SBAndroidPluginIndie-9ac08c84 

Mac OS X: 10.10.
XCode: 6.1.
Device:SGS5/4.4.2.

**Comment by Shahidammer** [comment]
This issue is Fixed 
SB Version: 1.4.8 rc.0
SBAndroid version: SBAndroidPluginProfessional-b8ffe603
MAC OS X: 10.10.
XCode: 6.1.

**Comment by Shahidwerplay** [comment]
This issue is fixed 

SBAndroid Version: SBAndroid Indie 948d0c4e
Spritebuilder Version: 1.4.9.
XCode: 6.1.
Device:SGS4/4.4.2.
