### ISSUE TITLE
Ruler is rendering twice

### ISSUE THREAD

**Issue by stuartcarnie** [spritebuilder/SpriteBuilder#1399]
![screen shot 2015-03-02 at 9 10 13 am](https://cloud.githubusercontent.com/assets/52852/6444610/f955761e-c0bb-11e4-958f-f472fdadc568.png)

**Comment by NickyWeber** [comment]
It´ll be fixed on develop with the next bump of cocos2d. Or is this occurring in 1.4?

**Comment by stuartcarnie** [comment]
@NickyWeber I've only built the `develop` branch, not sure about 1.4

**Comment by sana20** [comment]
This issue is fixed.

Mc OS X 10.10
SB Version: 1.4.7
XCode 6.2
