### ISSUE TITLE
Cannot Delete ruler markers.

### ISSUE THREAD

**Issue by jtwigg** [spritebuilder/SpriteBuilder#14]

**Comment by vlidholt** [comment]
Are we talking about the guides? Those can be cmd-dragged out of screen to be removed.

**Comment by jtwigg** [comment]
Okay. I never knew that. Maybe this could be improved with a context menu on the ruler to 'delete all'. I know since CocosBuilder, my artists could never figure out how to remove them and I ended up modifying the ccb's to remove them. :)
