### ISSUE TITLE
Two Physics items in 2 physics node doesn't collide with each other even when their physics is enabled.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#1422]
1. Launch Application.
2. Drag 2 physics node on the timeline.
3. Drag a color node under each physics node.
4. Enable Physics on both the nodes.
5. Build and run the project on simulator.
   
   -- Result: Color nodes doesn't collide with each other when user runs the project.

Build: SB 1.4.8-rc.0

Mac OS X: 10.9.5
XCode: 6.1.

**Comment by Shahidwerplay** [comment]
This issue is fixed.

Mac OS X 10.10.0
SB Version 1.4.9.
XCode 6.1
