### ISSUE TITLE
Angry Birds project and Empty Project displays blank screen on launch and gives an exception in terminal when user runs them on Android Lollipop devices.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1423]
1. Launch Spritebuilder.
2. Make an empty project and Angry Bird project.
3. Publish the projects.
4. Open the projects in XCode.
5. Run the project on Android Lollipop devices.
   
   -- Result: Angry Birds project and Empty Project displays blank screen on launch and gives an exception in terminal when user runs them on Android Lollipop devices.

Mac OS X: 10.10.1
XCode: 6.1.
XCode: 6.2
SB Version: 1.4.7 from Macstore
SBAndroid version: SBAndroidPluginStarter_58792478
Devices: Nexus 10/5.0.1. , Nexus 5/5.0. , Nexus 6/5.0. , Nexus 9/5.0.1.

**Comment by sana20** [comment]
@KristenY  yes this is only happening on the starter build. and this issue is also occurring on the previous build of starter which was assigned to us which is SBAndroidPluginStarter-9ac08c84.

**Comment by KristenY** [comment]
@sana20 Please comment if this was fixed with yesterday's testing? Thanks!

**Comment by sana20** [comment]
@KristenY yup this issue was fixed in yesterday's testing.
