### ISSUE TITLE
Changing the VERSION file doesn't affect the version of SB

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#1475]
At least when building locally. The about box inside SB shows another version, so does the about box in finder.

**Comment by vlidholt** [comment]
Correction. I apparently didn't use the right build command. But, still an issue with the assigned version number. It shows up correctly inside the about box, but it's not set correctly for the project. Looks like it's instead read from the build settings:

![screen shot 2015-03-31 at 2 58 11 pm](https://cloud.githubusercontent.com/assets/1539812/6930299/bb4c03bc-d7b6-11e4-9af5-b7c0e6aed09d.png)

**Comment by rkachowski** [comment]
investigating..
