### ISSUE TITLE
"Apportable Ld Error" error occurs when the user tries to run any project on an android device.

### ISSUE THREAD

**Issue by NoorFatima** [spritebuilder/SpriteBuilder#1478]
1. Launch Sprite Builder.
2. Create an empty project.
3. Open project in Xcode.
4. Attach an android device with your MAC.
5. Run project on the attached android device.
   
    --Result: "Apportable Ld Error" error occurs when the user tries to run any project on an android device. 

Sprite Builder: 1.4.9 and 1.4.7
Plugin: SBAndroidPluginProfessional-sbandroid-professional_046d84c81f2155f7.pkg
Mac OS: 10.9.5
![apportable ld error](https://cloud.githubusercontent.com/assets/11437568/6942205/63ee8448-d89f-11e4-9a3b-fc98b0b3a43e.png)
![ld error](https://cloud.githubusercontent.com/assets/11437568/6942244/b4f37bfa-d89f-11e4-9671-b9d79f6023d9.png)

**Comment by sana20** [comment]
This issue is re-occurring.

Mac OS X: 10.10.1
XCode: 6.1
SB Version: SB Version: 1.4.9 (From Macstore)
SBAndroid Version: SBAndroidPluginIndie-sbandroid-indie-4503b09f387c5595

**Comment by sana20** [comment]
We have cloned the build from the latest branch 1.4 and it is also giving the same error.

**Comment by KristenY** [comment]
This is fixed by adding -lcxx to other linking flags (http://screencast.com/t/CzXuYrbQ), and adding a couple lines to AndroidManifest.xml (http://screencast.com/t/QNTYlnEbSNQn).
