### ISSUE TITLE
Adjust Project Template 

### ISSUE THREAD

**Issue by NickyWeber** [spritebuilder/SpriteBuilder#1484]
There are several things to be altered for the project template:
- Rename Spritebuilder Resources default package, also see https://github.com/spritebuilder/SpriteBuilder/issues/1469
- Add a package.plist file to the default package
- Rename ccb files to sb
- Rename project file to sbproj
- Migrate the project file to v2 standards

**Comment by rkachowski** [comment]
This should have been addressed with #1521
