### ISSUE TITLE
Starting frame for particle systems

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#15]
It should be possible to set the starting time in a time line for particle system, this is the keyframe when the particle is inserted and started. Interface-wise, maybe the visibility keyframes could be used for this, but (for particle systems) instead of being hidden for if a first frame is set, it wouldn't be added.

**Comment by jtwigg** [comment]
Fixed.
changes to SpriteBuilder & Cocos2d
