### ISSUE TITLE
CCParticleSystem duration time is set to -1:00 initially.

### ISSUE THREAD

**Issue by NoorFatima** [spritebuilder/SpriteBuilder#1502]
1. Launch Application.
2. Create a New project.
3. Open Mainscene.ccb.
4. Drag CCParticleSystem to the stage.
5. Select CCParticleSystem in the timeline.
   
    -Result: In property inspector, under CCParticleSystemQuad, the Duration is set to -1.00, whereas a time duration can never be in minus.
   
    This happened 3/3 times.

Mac OS X: 10.9.5.
SpriteBuilder 1.4.9.rc.0.

![duration](https://cloud.githubusercontent.com/assets/11437568/7003822/8f1b4924-dc7a-11e4-802b-de54db3e3916.png)

**Comment by ryanbourneuk** [comment]
http://www.cocos2d-swift.org/docs/api/Classes/CCParticleSystemBase.html#//api/name/duration

'The default value of -1 means the emitter never stops emitting particles (runs forever).'

**Comment by NoorFatima** [comment]
As per CodeMonkeyzDevelopment comment, This issue is closed.
