### ISSUE TITLE
Crash on publish

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#152]
I'm getting a consistent crash when trying to publish. I have a project set up with 30 or so smart spritesheet folders. I was able to track it down to one in particular that was causing the crash.

I created a new project from the latest dev and added only the offending sprite sheet folder and confirmed it still crashes consistently. It seems the app also crashes when editing any of the project settings with this sprite sheet present.

The following is being printed to the console before the crash. I'll save the test project if anyone wants to take a look at it.

> SpriteBuilder[3245]: CGBitmapContextCreate: invalid data bytes/row: should be at least 1280 for 8 integer bits/component, 3 components, kCGImageAlphaPremultipliedLast.
> 
> SpriteBuilder[3245]: CGContextSaveGState: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
> 
> SpriteBuilder[3245]: CGContextRotateCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
> 
> SpriteBuilder[3245]: CGContextTranslateCTM: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
> 
> SpriteBuilder[3245]: CGContextDrawImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.
> 
> SpriteBuilder[3245]: CGBitmapContextCreateImage: invalid context 0x0. This is a serious error. This application, or a library it uses, is using an invalid context  and is thereby contributing to an overall degradation of system stability and reliability. This notice is a courtesy: please fix this problem. It will become a fatal error in an upcoming update.

**Comment by vlidholt** [comment]
Is there any chance we can get hold of your test file to easier reproduce this issue?

**Comment by ghost** [comment]
Dropbox link

https://www.dropbox.com/s/g9iib0x5iylai4s/crash.spritebuilder.zip

I removed the cocos2d lib for size.

**Comment by vlidholt** [comment]
Thanks! I will have a look at this right away.

**Comment by jtwigg** [comment]
Fixed.
