### ISSUE TITLE
Distortion in CCButton's graphics can be seen when user drag a drop a CCButton onto the stage.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1542]
1. Launch Application.
2. From the resource view, drag and drop a CCButton onto the stage. 

-- Result: Distortion in CCButton's graphics can be seen when user drag a drop a CCButton onto the stage.

Mac OS X 10.10.0
SB Version latest develop branch 2.0
XCode 6.2

![screen_shot_2015-04-14_at_12 40 43_pm](https://cloud.githubusercontent.com/assets/8393830/7174854/87c1c442-e3c2-11e4-8d07-217a1b278f8f.png)

**Comment by Shahidwerplay** [comment]
This issue is fixed.

Mac OS X 10.10.0
SB Version latest develop branch (2.0)
SB Revision 4fd68fb 
XCode 6.1
