### ISSUE TITLE
Sprites are not working when the user publishes and runs a project on iOS simulator.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1546]
1. Launch Spritebuilder.
2. Make a new project.
3. Drag and drop a few sprites to the resource browser.
4. Drag and drop a sprite on the mainscene.sb.
5. Publish the project.
6. Open the project in XCode and run on iOS simulator.
   
   -- Result: Sprites are not working as they don't show up on the screen when the user publishes and runs a project on iOS simulator.

Note: This issue is also happening with text field, button, slider and particle system.

Mac OS X: 10.10.1
XCode: 6.1.
Latest Develop branch SB Version (2.0)

**Comment by NoorFatima** [comment]
This issue is re-occurring.

Mac OS X: 10.9.5
XCode: 6.1
SB Version: 2.0.0
SB Revision: 4fd68fb2bf

**Comment by NoorFatima** [comment]
This issue is re-occurring.

Mac OS X: 10.9.5
XCode: 6.1
SB Version: 2.0.0
SB Revision: 4fd68fb2bf

**Comment by sana20** [comment]
This issue is re-occurring.

Mac OS X: 10.10.1
XCode: 6.1.
Latest Develop branch SB Version (2.0)
SB Revision: 4fd68fb2bf

**Comment by sana20** [comment]
This issue is fixed.

Mac OS X: 10.10.1
XCode: 6.1.
Latest Develop branch SB Version (2.0)
SB Revision: 02eedd13c8
