### ISSUE TITLE
Nest CCBFiles loose their timeline position when you 'undo' a another property.

### ISSUE THREAD

**Issue by jtwigg** [spritebuilder/SpriteBuilder#157]

**Comment by jtwigg** [comment]
a) Add a nested CCBFile animation into your MainScene. One that has 10 frames.
b) in MainScene, animation to frame 5, CCBFile should be on frame 5 as well.
c) Move a CCNode in MainScene from position 1 to position 2.
d) Undo the translation (Ctrl-z)
CCBFile is now on Frame 0.

**Comment by NoorFatima** [comment]
This issue is fixed.
Device: Mac OS X 10.9.5
SB Version: 1.4.7
