### ISSUE TITLE
Position of physics bodies changes when user attach both of them with a CCPhysicsDistance Joint. 

### ISSUE THREAD

**Issue by Shahidwerplay** [spritebuilder/SpriteBuilder#1570]
1. Launch Application.
2. Create a project.
3. Drag and drop a PhysicsNode.
4. Drag and drop two physics bodies under the physicsNode. Make one of them static and other one dynamic
5. Drag and drop a CCPhysics Distance joint and attach its ends with both physics bodies.
6. Publish the project and build and run it on XCode.
   
   --Result: Position of physics bodies changes when user attach both of them with a CCPhysicsDistance Joint.

SB Version: Latest Develop Branch (2.0)
SB Revision: 4fd68fb2bf
Mac OS 10.10.0
XCode 6.1 

Video Link:https://drive.google.com/file/d/0B5-RfBatv-b8WXFrQnhyT0FNZHM/view?usp=sharing

**Comment by sana20** [comment]
This issue is fixed.

Mac OS X: 10.10.1
XCode: 6.1.
Latest Develop branch SB Version (2.0)
SB Revision: 02eedd1
