### ISSUE TITLE
Code Connections: When don't assign is specified, the text box should be empty and disabled.

### ISSUE THREAD

**Issue by jtwigg** [spritebuilder/SpriteBuilder#158]

**Comment by vlidholt** [comment]
Another solution: Remove the "Don't assign" option, use "Document root" as default but only actually assign it if the member variable name is set.

**Comment by vlidholt** [comment]
Solve by: Remove the Don't assign option as mentioned above. Needs to be tested so we don't break anything.

**Comment by jtwigg** [comment]
I'll make it a UI change mostly, and the CCBReader will remain unchanged.

**Comment by jtwigg** [comment]
Should be solved by:
https://github.com/jtwigg/SpriteBuilder/commit/b7593c1e852961aa04bc815cf36252ea50135261

**Comment by vlidholt** [comment]
This needs to be fixed for selectors too, e.g. CCButton
