### ISSUE TITLE
The XCode 6.3. crashes when user tries to open any project.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#1588]
1. Launch Spritebuilder.
2. Make a new project.
3. Publish the project.
4. Open the project in Finder.
5. Now open the project.xcodeproj file.
   
   -- Result: The XCode 6.3. crashes when user tries to open any project.

SB Version: Latest Develop Branch (2.0)
SB Revision: 3c4db04
Mac OS: 10.10.1
XCode: 6.3.

Video: https://drive.google.com/file/d/0B23s5OMd3iivZ0prOVUwUndUUG8/view?usp=sharing

**Comment by ranamateen** [comment]
I have the same problem if anyone knows the solution please share it.
Thanks

**Comment by collinjackson** [comment]
Please try with the latest build of the SpriteBuilder Android Plugin
