### ISSUE TITLE
Sound playback in editor doesn't work correctly

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#16]
First sound doesn't play back and sometimes sounds are played with incorrect timing. Sound playback needs to work even though frames are skipped in playback. (This is all in the editor, playback logic works when exported)

**Comment by jtwigg** [comment]
Fixed: The problem appeared to be 
a) An effort to not play more than the current step was done by subtracting 1/FPS. This appeared to result in floating point error, causing some time steps to be missed.

b) The above was countered by capturing frames where frame times is   ( minTime <=  keyFrame.time < maxTime ). The difference being the second 'less than and not equal to'
