### ISSUE TITLE
spritebuilder may crash when saving a ccb file if open spritebuilder in a soft linked folder.

### ISSUE THREAD

**Issue by tangyiyang** [spritebuilder/SpriteBuilder#1608]
Suppose  we have a project located /A/spritebuilder.ccbproj, and we soft link this folder to /B with ln -s /A /B

if we open our project and do editing in folder B, spritebuilder would crash.

**Comment by oxeron** [comment]
Why would you do that ? :)

**Comment by tangyiyang** [comment]
That's a minor problem. I wrote a runtime for sprite-builder in Lua for cocos2d-x and customized my workflow. 

Anyway I can simple open the /A/spritebuilder.ccbproj to get everything done. 

never mind this, I will close, thank you. :)
