### ISSUE TITLE
relocatting by Dragging and Dropping multiple nodes onto a CCNode doesn't work.

### ISSUE THREAD

**Issue by jtwigg** [spritebuilder/SpriteBuilder#162]
it only moves one at a time.

**Comment by vlidholt** [comment]
Still at least one issue with this one: When nested nodes are moved in the hierarchy their selection boxes are drawn incorrectly on the stage. When changing the selection everything is drawn correctly again.

Needs more testing.

**Comment by NickyWeber** [comment]
Fixed selection issue.
