### ISSUE TITLE
Question: How can I set a custom class for a scene (CCB-File)

### ISSUE THREAD

**Issue by Ben-G** [spritebuilder/SpriteBuilder#163]
For the main scene this is done by default (the custom class is set to "MainScene"). I can set a custom class directly in the CCB-File but I haven't found a way to do this in the UI yet.

Is it possible? If yes, how?

Thanks

**Comment by jtwigg** [comment]
Are you looking for the custom class text field under the 'Code Connections' tab on the right hand side?

![screen shot 2014-01-10 at 5 26 37 pm](https://f.cloud.github.com/assets/1237233/1892921/82601a1c-7a5f-11e3-87ce-f39b0b668b61.png)

**Comment by Ben-G** [comment]
I'm aware of the 'Code Connections' tab, however I don't know how to open it for Scenes (CCB-Files).
![screen shot 2014-01-13 at 09 27 59](https://f.cloud.github.com/assets/1423068/1902851/814df2f0-7c78-11e3-88d7-4fb0f120e2d7.png)

**Comment by vlidholt** [comment]
You will need to select the root node object.

**Comment by jtwigg** [comment]
Ahh... So open up your MainScene.ccb and select the root node like in my screen shot and goto Code Connections.
This CCNode is the node returned from the call

MainScene  \* mainScene = [CCBReader load:@"MainScene"]; //Deserialize MainScene.ccb to create a rootNode object of type class MainScene : CCNode

![screen shot 2014-01-13 at 11 06 31 am](https://f.cloud.github.com/assets/1237233/1903720/fd8c20b4-7c85-11e3-8a8d-fd3b95e9e3e3.png)

**Comment by jtwigg** [comment]
if there's any further quetions, I'll re-open.

**Comment by Ben-G** [comment]
Thanks, that's it.
