### ISSUE TITLE
Large pause when the first audio sound being.

### ISSUE THREAD

**Issue by jtwigg** [spritebuilder/SpriteBuilder#164]
cocos2d runtime has a large pause when the first audio signal plays.

**Comment by cocojoe** [comment]
I don't really know if the audio boot time can be improved however for usability it's best to initialise the singleton in the appDelegate, so it's just part of the normal app load and not noticed by the user.  Any audio methods will be fine after that.

**Comment by jtwigg** [comment]
That would be my suggestion too.

**Comment by vlidholt** [comment]
Sounds like a good play to init the audio at launch time.

**Comment by NickyWeber** [comment]
Wontfix?

**Comment by cocojoe** [comment]
Audio is initialised in the AppDelegate which makes reduces noticeable lag on audio init.  However if you are loading any large audio files (or no in-game rather than caching pre-game then imagine that would cause lag.

I havn't actually looked at how/when SpriteBuilder loads/caches sound.

**Comment by vlidholt** [comment]
Let's add this to when SpriteBuilder is started, in the AppDelegate applicationDidLoad ...

**Comment by vlidholt** [comment]
Fixed
