### ISSUE TITLE
Create compile warning OR throw up popup warning when you try and enable physics bodies on nodes that are not under a CCPhysicsNode

### ISSUE THREAD

**Issue by jtwigg** [spritebuilder/SpriteBuilder#165]

**Comment by vlidholt** [comment]
Possible other solution is to allow nodes with physics bodies outside physics nodes in Cocos2d

**Comment by inolasco** [comment]
I think the warning would be good, but maybe only on ccb files that describe layers and container nodes, not on sprites or the like that would be added in code to a physics node.

For example, the penguin on this tutorial
https://www.makegameswith.us/tutorials/getting-started-with-spritebuilder/penguins-seals/

**Comment by vlidholt** [comment]
It's valid to create physics bodies in files that do not have a physics node. E.g. the loaded node graphs can be added to a physics node in run time or as a sub ccb-file. Closing this one.
