### ISSUE TITLE
Display waveforms in sound track.

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#17]
It would be nice to display the sounds' waveforms in the editor, rather than just the keyframes. Needs to be done efficiently, perhaps with caching data/images for the waveforms etc.

**Comment by jtwigg** [comment]
I've actually done this feature several times over the course of my career. 
One more time can't hurt.

**Comment by jtwigg** [comment]
This looks good and it ready for review.

**Comment by vlidholt** [comment]
Merged it, looks super good over all! Only have a few small things, but leaving this open for now.

**Comment by jtwigg** [comment]
1. The dark grey dividing line right below the sound track should have the same look and width regardless if the track is expanded or not. (see picture)
2. The lines between properties are no longer drawn (for other types than sound), it also looks odd when the expanded nodes with properties are selected. (see picture)
3. I think it may look better if the sounds are just drawn on top of each other without the use of transparency. Maybe also draw the left/right audio channel on top of each other, to make it more unified when mixing stereo and mono sounds?
4. When dragging a sound to the timeline, the little blue marker bar has a gap at the top but not at the bottom. Either have a gap both at the top and the bottom or no gap.
5. If possible make the white text when dropping drop stay black.

**Comment by jtwigg** [comment]
1) Fixed
2) Fixed
3) Fixed
4) Fixed
5) Fixed

**Comment by vlidholt** [comment]
The only issue I could find with this update is that the expanded rows for properties doesn't look correct. Not sure why this has changed but attaching an image with the correct drawing for reference.

![sequencer](https://f.cloud.github.com/assets/1539812/1760666/6abadeb2-66b7-11e3-8802-94f28422e971.png)

**Comment by vlidholt** [comment]
Also found that the expand button for the sound track is drawn slightly off center (too low down). Adding an image to clarify the issues.

![issues](https://f.cloud.github.com/assets/1539812/1760689/f0cd7ac8-66b7-11e3-890c-6e700251a05f.png)

**Comment by jtwigg** [comment]
The problem with the Sound Expand icon appearing not centrered is that the extra bold line uses up 1 pixel of the cell, making it appear slightly smaller. 

Solutions: 
1) Make the Sound Effects & callback rows slightly bigger: This is a bit finicky and I think will amplify the miss-sizing effect
2) Get the bold line to render ontop of the light gray line: At present because of draw order, the gray line gets draw after the bold line, so if they were to overlap, the gray line would win. 

![screen shot 2013-12-17 at 2 00 58 pm](https://f.cloud.github.com/assets/1237233/1768775/66afd380-6767-11e3-84b4-4fa58fe9c99e.png)

**Comment by jtwigg** [comment]
Here's what it used to look like. I'll get it back.
![screen shot 2013-12-17 at 2 43 33 pm](https://f.cloud.github.com/assets/1237233/1769186/1c855918-676e-11e3-9a95-d59d4cb362af.png)

**Comment by jtwigg** [comment]
I've fixed
1) The 1 pixel error on the sound effects expander. I just nudged it up 1 pixel.
2) I've fixed the sequencer background colouring on the keyframes rows.

**Comment by jtwigg** [comment]
Requesting Close.

**Comment by vlidholt** [comment]
This looks good now. :) Nice work, closing!
