### ISSUE TITLE
CBReader: readSoundKeyframesForSeq : readCachedString throws NSRangeException

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#170]
n is 255
stringCache.count is 75 here

``` Objective-C
- (NSString*) readCachedString
{
    int n = readIntWithSign(self, NO);
    return [stringCache objectAtIndex:n];
}
```

Let me know if you need more details.

**Comment by vlidholt** [comment]
Possibly a bug. It is possible you are using incompatible versions of Cocos2d and SpriteBuilder. Can you reproduce in latest version?

**Comment by jan-happy** [comment]
Seems to be fixed in the latest release of Cocos2d and SpriteBuilder, thank you!
