### ISSUE TITLE
Sequence of animation playback sometimes incorrect in editor

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#18]
Test case: https://github.com/apportable/SpriteBuilder-Example

It's possible to use different timelines in a single ccb-file. These can be chained to be played in a sequence and one of the sequences can be set to automatically play when the file is run. It's also possible to include ccb-files in other ccb-files, when this is done the sub-files should play back in the order specified in the individual sub-files.

E.g. An animation can have two timelines Intro and Loop. Intro is chained to Loop and Loop is chained to itself. When playing back this should be played back as Intro - Loop - Loop - Loop - ...

To reproduce, open the SpriteBuilder-Example/Example/SpriteBuilderFiles/SpriteBuilderFiles.ccbproj play back the animation in MainScene.ccb, the sub-file (MainSceneContent.ccb) incorrectly loops the intro animation, when it should move on to the loop animation.

**Comment by jtwigg** [comment]
Fixed
