### ISSUE TITLE
CCButton: When setting the Sprite frame to a custom image, it gets warped at the edges

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#180]
When I assign this image to the normal state of my button:
![pfeil_big](https://f.cloud.github.com/assets/695826/1920989/363a4008-7df3-11e3-811d-fcecd1bf2577.png)
the button looks like this:
![bildschirmfoto 2014-01-15 um 15 40 39](https://f.cloud.github.com/assets/695826/1920991/4dd6f1f2-7df3-11e3-817d-d23bc723f5ae.png)
Am I missing something or is this a 9 slice scaling bug?

**Comment by jtwigg** [comment]
It does look like 9 slice but it also looks like pvr compression. Do you have any compression settings on that image? Is it part of a sprite sheet?

**Comment by jan-happy** [comment]
No, no special settings.
Steps to reproduce:
- Drag a CCButton from the Node Library view
- Set the sprite frame of the normal state to a custom image (I used the first image in the first post)

This is how the button looks then:
![bildschirmfoto 2014-01-15 um 21 10 30](https://f.cloud.github.com/assets/695826/1924381/5719b4ec-7e21-11e3-8254-c3f53a4b40f1.png)

And those are the properties:
![bildschirmfoto 2014-01-15 um 21 10 12](https://f.cloud.github.com/assets/695826/1924383/610f2d88-7e21-11e3-90d0-8a1a932b7fa6.png)

**Comment by jtwigg** [comment]
Reading through the code, it IS using a CCSprite9Slice for the background image.
I'll look around and ask the powers that be how to create just a simple image background like you're doing. We'll put a solution in pronto if need be. 

Cheers.

**Comment by jan-happy** [comment]
Thanks a lot! A simple checkbox to disable 9 slice would be awesome!

**Comment by jtwigg** [comment]
Here's a solution:
You need to set your 'preferred size' correctly so that it matches your image. In your case is 
x=131, y=90
which I got by just dropping you image onto the stage and reading its content size.

The image button now renders correctly.

**Comment by jan-happy** [comment]
Thanks, that's a workaround!

**Comment by jtwigg** [comment]
Will open a new task to improve feature.
