### ISSUE TITLE
CCButton Background images are 9 Sliced automatically. Make UI easy to use to utilize non-9sliced images.

### ISSUE THREAD

**Issue by jtwigg** [spritebuilder/SpriteBuilder#182]

**Comment by vlidholt** [comment]
We need a strategy for how this should be implemented UI-wise before starting on this feature.

**Comment by vlidholt** [comment]
Maybe make it a menu option would be the easiest (special case for buttons)

**Comment by jtwigg** [comment]
https://github.com/spritebuilder/SpriteBuilder/pull/525
