### ISSUE TITLE
Can CCImage backgrounds support solid colors as well as images.

### ISSUE THREAD

**Issue by jtwigg** [spritebuilder/SpriteBuilder#183]

**Comment by vlidholt** [comment]
I guess we are talking about CCSprite? Currently the normal thing is to use CCNodeColor or CCNodeGradient for this purpose.

**Comment by jtwigg** [comment]
Except you can't handle selected and disabled coloring

**Comment by vlidholt** [comment]
Ok, I understand the question now! :)

The color options are for coloring the background image. For example, this allows you to use the same texture for the normal state and the down state but with a color applied to the texture of the down state. The color you set can be a gray color – which will make the down state of the button to appear darker.
