### ISSUE TITLE
Choosing .pvr as an option for a graphic results in broken published file

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#185]
With this file:
![pfeil_big](https://f.cloud.github.com/assets/695826/1930402/6b30fa50-7eab-11e3-8162-9bc5f04db31e.png)
I chose PVR RGBA4444 as output format, and all I got was this:
![bildschirmfoto 2014-01-16 um 13 41 28](https://f.cloud.github.com/assets/695826/1930405/88c39168-7eab-11e3-9e07-6ad0f5fc84fd.png)
Same with PVR RGBA8888, compressed or uncompressed.

**Comment by jtwigg** [comment]
Yup, I'm seeing it too. I'll look into it pronto.

**Comment by jtwigg** [comment]
Item of note, the image in PVR format is rotated.

**Comment by jtwigg** [comment]
Ya, I should have known. It wants square image sizes (not necessarily power of 2 however).
I resized your image to 525x525 and it came out like this in PvrTexToolGUI

![screen shot 2014-01-16 at 11 09 40 am](https://f.cloud.github.com/assets/1237233/1933844/ce9f4188-7ee1-11e3-9b52-41b717e9883e.png)

**Comment by jan-happy** [comment]
Thanks for the workaround!

**Comment by jtwigg** [comment]
Fixed in latest develop.
Additionally, you cannot select PVRTC anymore for non-power of two images.
