### ISSUE TITLE
CCButton: Label alignment properties not visible

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#192]
The label of a button should have the same alignment and size options as a CCLabelTTF.

**Comment by NickyWeber** [comment]
What size options do you mean? Font size can be set.
About the alignment options, do you expect the label to be aligned within the buttons boundaries or just what alignment does in the CCLabelTTF?

**Comment by jan-happy** [comment]
I meant "what alignment does in the CCLabelTTF".
Thanks!
