### ISSUE TITLE
Add a warning for empty ivar names.

### ISSUE THREAD

**Issue by slembcke** [spritebuilder/SpriteBuilder#193]
When loading a CCB file I was getting the error "CCBReader: Couldn't find member variable:". The problem was that I left the actual variable name blank (derp). Since it was a CCB file that loaded several other CCB files it took a bit of poking in the debugger to figure out which file CCB file I needed to look in and what I was looking for.

Adding a validation to the ivar name entry field would fix the issue.

**Comment by slembcke** [comment]
Hmm. After some additional editing, the name ended up as blank again. Not sure how to reproduce the issue yet.

**Comment by slembcke** [comment]
Aha. So if you are editing the ivar name field, and it's focused when you press cmd-s, it will revert the field's value back to it's previous value. Which in many cases is back to the empty string. So a validation would mostly fix the issue, but it seems like it should store the field when it loses focus too.

**Comment by jtwigg** [comment]
Needs a warning and a validation I thinks.

**Comment by jtwigg** [comment]
I don't think validation is going to work very well. Warnings are in though. 
Calling it complete for now. May come back to it.

**Comment by vlidholt** [comment]
Added the validation. Just hoping I didn't break anything else :P

**Comment by misterHallodri** [comment]
This is still an issue right? I'm using the latest version (#b72447c5db) and for one CCB file it's always setting 'Doc root var' for all nodes that were not assigned before. Don't know why this only happening with one file though.
