### ISSUE TITLE
AppController incorrectly attempts to load the config plist before the file utils is initialized

### ISSUE THREAD

**Issue by phausler** [spritebuilder/SpriteBuilder#194]
didFinishLaunchingWithOptions should read as
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
  {
  // Configure CCFileUtils to work with SpriteBuilder
  [CCBReader configureCCFileUtils];
  
  // Configure Cocos2d with the options set in SpriteBuilder
  NSMutableDictionary\* cocos2dSetup = [NSMutableDictionary dictionaryWithContentsOfFile:[[CCFileUtils sharedFileUtils] fullPathFromRelativePath:@"configCocos2d.plist"]];
  
  // Note: this needs to happen before configureCCFileUtils is called, because we need apportable to correctly setup the screen scale factor.
  # ifdef APPORTABLE
  
  if([cocos2dSetup[CCSetupScreenMode] isEqual:CCScreenModeFixed])
      [UIScreen mainScreen].currentMode = [UIScreenMode emulatedMode:UIScreenAspectFitEmulationMode];
  else
      [UIScreen mainScreen].currentMode = [UIScreenMode emulatedMode:UIScreenScaledAspectFitEmulationMode];
  # endif
  
  // Do any extra configuration of Cocos2d here (the example line changes the pixel format for faster rendering, but with less colors)
  //[cocos2dSetup setObject:kEAGLColorFormatRGB565 forKey:CCConfigPixelFormat];
  
  [self setupCocos2dWithOptions:cocos2dSetup];
  
  return YES;
  }

**Comment by osinoleg** [comment]
added a fix at the sprite builder level. Ideally, CCBReader should not configure the asset paths until we have a chance to set up the screen mode. 

https://github.com/apportable/SpriteBuilder/commit/b0fc6e470831a1344659b66a877cecd0edc2675a
