### ISSUE TITLE
CCNodeColor: Selected Color does not stick

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#195]
I select a color for a CCNodeColor like this:
![bildschirmfoto 2014-01-21 um 08 33 55](https://f.cloud.github.com/assets/695826/1961332/ae41441e-826e-11e3-9015-15381424868a.png)

After de-selection the CCNodeColor, selecting it again and looking at the color values, they changed to:
![bildschirmfoto 2014-01-21 um 08 34 09](https://f.cloud.github.com/assets/695826/1961338/cd364a5e-826e-11e3-939d-0c4f492d69d7.png)

Happens in the latest dev version.

**Comment by jtwigg** [comment]
I'm having trouble producing the undesired behavior. Can you
a) Test again given todays develop build confirm its still happening
b) If it still is present, lets go through a more detailed repro description

1) Create untitled.ccb
2) Add a CCSprite to the root node to provide something else to click onto.
3) Add a CCNodeColor
4) Select the CCNodeColor
5) Open color picker and Change its colour
6) Close color picker: Varients of this step :
    i ) Click on the CCSprite on the Stage to close
    ii) Click on the CCSprite text on the Animation Timeline to close
    iii) Click on the inspector window to close
7) save doc (ctrl-s)

As I said, I'm not seeing any problem with those activities. Can you provide an alternative repro list that does have a problem?

Cheers.

**Comment by jan-happy** [comment]
I've created a dummy project with the latest version from the app store. Here are the source files:
http://www.sendspace.com/file/o7z4q2

Here is a screencapture of the effect:
http://www.sendspace.com/file/josqxf

**Comment by jtwigg** [comment]
Sanity check this with me:

http://www.sendspace.com/file/6b4f01

This is my working experiment. The major difference is that when  I click on the preset color along the bottom, my color sliders snap to the new color. Yours do NOT. 

My suspicion is this is a OS bug because that color picker is the NSColorPanel written by Apple and it likely changes with versions.

A) Are you using Maverick? What OS version are you using?

**Comment by jan-happy** [comment]
There you have it! 
Look at the color values you select at 0:23
![bildschirmfoto 2014-01-23 um 09 10 03](https://f.cloud.github.com/assets/695826/1982756/e2404cb8-8405-11e3-9547-78a80a34ae89.png)

Then you deselect it and just select it again, and the values changed to:
![bildschirmfoto 2014-01-23 um 09 10 18](https://f.cloud.github.com/assets/695826/1982757/e54a59da-8405-11e3-8be6-def554a17275.png)

I would guess that there is a rounding error or something slightly off when transforming the UIColor values to the color values that are stored in the .ccb

**Comment by jtwigg** [comment]
I think I got a repro. Investigating.

**Comment by jtwigg** [comment]
Fixed. I now know more about MacOSX color programming than I'd ever like to know. 
It was a conversion between device and Calibrated. There were some inconstancies & there may still be some so I'll get this reviewed and it may be changed once more before closing.
@vlidholt  Need to review change: 
https://github.com/apportable/SpriteBuilder/commit/56e8baa05a3573df4c88271d6f0ad354b197503f
&&
https://github.com/apportable/cocos2d-iphone/commit/f72fc02c00bfe810ed82b8164574ac767b36e3e1

The device vs calibrated settings may still be incorrectly reversed.

**Comment by jan-happy** [comment]
When I set the RGB sliders to 0 / 120 / 200 it now changes to 14 / 120 / 200 with the latest develop commit.

**Comment by jtwigg** [comment]
For sure. The fix I put in only worked for certain number ranges, but with numbers hovering around Zero, they get clipped. 

I'll speak to one of our product leads about this tonight and we'll come up with the final solution.

**Comment by vlidholt** [comment]
So... using uncalibrated colors is risky as there is a chance that users may get different results with different monitor settings. This needs to be tested to make sure it works across different monitors. For instance there could be a risk that different values get exported for the same project which can cause issues, or that opening closing the color panel on different monitors will change the colors. Things like that needs to be tested before we close this issue.

**Comment by jan-happy** [comment]
It would be the best if the color values I select get stored in a way that they are exactly the same when they are loaded again. Thanks for looking at it!

**Comment by NoorFatima** [comment]
This issue is fixed.
Device: Mac OS X 10.9.5
SB Version: 1.4.7

**Comment by jan-happy** [comment]
Tested it on 10.10.3, works as well.
Thank you!
