### ISSUE TITLE
Duplicate classes when loading exporter plugins

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#201]
objc[18613]: Class ResourceManagerPreviewAudio is implemented in both Build/Products/Debug/SpriteBuilder.app/Contents/MacOS/SpriteBuilder and /Build/Products/Debug/SpriteBuilder.app/Contents/PlugIns/Cocos2D iPhone.ccbPlugExport/Contents/MacOS/Cocos2D iPhone. One of the two will be used. Which one is undefined.

The above is an example from the log. There are several instances, listing the following classes:

ResourceManagerPreviewAudio
InspectorStringSimple
WarningOutlineHandler
SequencerButtonCell
WarningOutlineView
WaveformImageCell
SoundFileImageController
WarningCell

As long as these classes are 100% the same in both source files it doesn't matter. It probably doesn't matter. 

But for completeness sake I wanted to report this, there's a potential for obscure bugs here (and I encountered them before so I'm wary of these warnings). Specifically situations where an issue with these classes (such as sudden loss of functionality) can be consistently reproduced on one system but not another, or only every n-th launch, or only today but not tomorrow.

**Comment by jtwigg** [comment]
Ya, It looks like several files were duplicately included in the Cocos2d iPhone project. I think perhaps its my fault or, to a far lesser extent, Xcodes fault for adding the files to the non-desirable projects upon creation.

I'll remove them but, as you said, they are clones of the .m's so they should behave the same, barring some aggressive [isKindOf:class] kinda programming.
