### ISSUE TITLE
Feature Request: Allow to change contentScale factor for different device types

### ISSUE THREAD

**Issue by Ben-G** [spritebuilder/SpriteBuilder#204]
**Currently SpriteBuilder always assumes a contentScale factor of 2.0 for the tablet version of a Game.** For my current example I do not want to scale the game content, but instead want to make a larger are of my Gameplay visible on tablet devices.

If I set up the tablet version to use the 1x images, the preview in SpriteBuilder looks distorted (because of contentScale 2.0):

![screen shot 2014-01-22 at 16 26 24](https://f.cloud.github.com/assets/1423068/1980637/7ce39efa-83c5-11e3-9f84-7de6a2b26661.png)

In code I can change the contentScale factor to 1.0, to get the expected result:
![ios simulator screen shot 22 jan 2014 16 30 27](https://f.cloud.github.com/assets/1423068/1980640/94abd214-83c5-11e3-9376-f8816acb0808.png)

It would be great if the contentScale could be set in SpriteBuilder. That way I would get a preview of how the game actually will look on a tablet device.

**Comment by haligalaph** [comment]
Also it would be great to have contentScale factor of 2.4.

**Comment by Ben-G** [comment]
Will be solved with #256
