### ISSUE TITLE
allowsRotation not correctly set

### ISSUE THREAD

**Issue by tanis2000** [spritebuilder/SpriteBuilder#206]
'm using SB 1.0.2 (Mac App Store release).

Loading a ccbi through CCBReader doesn't set the "allowsRotation" correctly for the physicsBody of a CCSprite.
If I set it to YES, it's reflected in the code as well.
But if I set it to NO, the code says that it's YES.

It looks like the project has the correct value but CCBReader might be reading it wrong.
Thanks!

**Comment by jtwigg** [comment]
Looking at it.

**Comment by slembcke** [comment]
Should be fixed with this: https://github.com/cocos2d/cocos2d-iphone/commit/ef6d7e700c577c119556d70c5e9a44c1e55e740c

**Comment by tanis2000** [comment]
Nice! Thanks so much!
