### ISSUE TITLE
Wrong config initialization in default project

### ISSUE THREAD

**Issue by timoinutilis** [spritebuilder/SpriteBuilder#207]
In AppDelegate.m this part...

NSMutableDictionary\* cocos2dSetup = [NSMutableDictionary dictionaryWithContentsOfFile:[[CCFileUtils sharedFileUtils] fullPathFromRelativePath:@"configCocos2d.plist"]];

... should be after...

[CCBReader configureCCFileUtils];

...otherwise file cannot be found (it's inside "Published-iOS", which is added to paths in configureCCFileUtils).

**Comment by osinoleg** [comment]
I've already fixed this in:

commit b0fc6e470831a1344659b66a877cecd0edc2675a

Author: Oleg Osin oleg@apportable.com

Date:   Tue Jan 21 14:17:03 2014 -0800

```
Made sure that the configCocos2d.plist is correctly loaded and read
```

before the CCBReader is configured (because configuring CCBReader file
utils causes incorrect resolution paths to be set).

**Comment by osinoleg** [comment]
Make sure you get the latest version of spritebuilder and run
scripts/BuildDistribution.sh to update the default project template.

**Comment by osinoleg** [comment]
note: original ticket for this issue can be found here: https://github.com/apportable/SpriteBuilder/issues/194
