### ISSUE TITLE
OS X support?

### ISSUE THREAD

**Issue by iluuu1994** [spritebuilder/SpriteBuilder#210]
Is this planned anytime soon?

**Comment by LearnCocos2D** [comment]
Technically the CCBi format can also be read by cocos2d OS X targets. If you need this right now it should be possible to get that working with some tinkering.

I don't know what the plans are for "proper" OS X support (ie generating an Xcode project with an OS X target, plus OS X specific asset exporter and settings).

**Comment by iluuu1994** [comment]
Maybe I will fork the project and add Mac OS X support at some point in the future.

Anyway, thanks for your feedback
