### ISSUE TITLE
Resource/Warnings Column is not resizable

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#214]
I can not read the warnings since the column is not resizable, the warnings should copyable via be right-mouseclick.
![bildschirmfoto 2014-01-25 um 11 23 58](https://f.cloud.github.com/assets/695826/2001437/e86ee12a-85aa-11e3-9364-bbead9f460db.png)

**Comment by jtwigg** [comment]
I'm scheduled to fix that shortly. It you mouse hover, it'll show a popup showing the whole error.

**Comment by jtwigg** [comment]
Updated. You can read the whole line now. It line wraps. SHould keep us going for awhile.

**Comment by jan-happy** [comment]
Thanks a lot!
