### ISSUE TITLE
Make it possible to update Cocos2d

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#222]
When opening a project, check the version of Cocos2d that is used. If there is a newer stable version, offer the user to update to the latest version. It should probably also ask the user to make a backup of the project beforehand. Add an update option to the File menu.

Update should be done by simply replacing the cocos2d-iphone directory. If there are any special considerations that the user needs to take into account for the update, there should be migration instructions about this too.

**Comment by cocojoe** [comment]
Should probably popup with the changelog so you can see what's new.  Most
maintenance releases should just directly replace existing files and 'just
work', imagine any point releases 3.1 etc Should have 'upgrade' notes.

On 27 January 2014 23:36, Viktor Lidholt notifications@github.com wrote:

> When opening a project, check the version of Cocos2d that is used. If
> there is a newer stable version, offer the user to update to the latest
> version. It should probably also ask the user to make a backup of the
> project beforehand. Add an update option to the File menu.
> 
> Update should be done by simply replacing the cocos2d-iphone directory. If
> there are any special considerations that the user needs to take into
> account for the update, there should be migration instructions about this
> too.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/apportable/SpriteBuilder/issues/222
> .

## 

Martin

**Comment by LearnCocos2D** [comment]
A few thoughts that run through my mind....

I think it should always make a backup and not give the user the option to skip the backup, just to save the user from him/herself. Easy enough to delete the .backup folder via Finder, terrible if the user intended or ignored to make a backup, but needs it.

Alternative: proceed with the update, build it, and show the user any generated warnings/errors (and the lines causing them) so he/she can preemptively consider whether these are easy to fix, or consult the forum for fixes before applying the upgrade. Kind of like the Refactor to ARC option in Xcode builds the project with ARC to verify there aren't any "ARC compatibility issues" and then gives you a preview of the changes. Maybe not as fancy preview, just the output of warnings/errors would suffice for now.

Food for thought:

How should breaking changes be handled? Up to the user to fix?

What about updates where user uses very old version (ie 3.0) but the latest version is 3.8 or something? Should updates happen progressively (ie 3.1 then 3.2 then 3.3) and would that make the process any smoother than doing an upgrade larger than +0.1 ?

**Comment by cocojoe** [comment]
Good point, from an ideal 'average user' experience perspective.  I would
say that the user shouldn't be able to 'auto-update' to a breaking change
release, any major update to Cocos2D would have to be checked and bundled
with an update version of SpriteBuilder.  This updated version of
SpriteBuilder would have to 'upgrade' the users CCB files (if required) and
update project.

What about custom code the user has written that is now incompatible for
whatever reason.

I would say that responsibility is with the end user to fix those errors,
however we would ensure good notes (and Forum support) this time around for
any breaking changes....

On 28 January 2014 10:58, Steffen Itterheim notifications@github.comwrote:

> A few thoughts that run through my mind....
> 
> I think it should always make a backup and not give the user the option to
> skip the backup, just to save the user from him/herself. Easy enough to
> delete the .backup folder via Finder, terrible if the user intended or
> ignored to make a backup, but needs it.
> 
> Alternative: proceed with the update, build it, and show the user any
> generated warnings/errors (and the lines causing them) so he/she can
> preemptively consider whether these are easy to fix, or consult the forum
> for fixes before applying the upgrade. Kind of like the Refactor to ARC
> option in Xcode builds the project with ARC to verify there aren't any "ARC
> compatibility issues" and then gives you a preview of the changes. Maybe
> not as fancy preview, just the output of warnings/errors would suffice for
> now.
> 
> Food for thought:
> 
> How should breaking changes be handled? Up to the user to fix?
> 
> What about updates where user uses very old version (ie 3.0) but the
> latest version is 3.8 or something? Should updates happen progressively (ie
> 3.1 then 3.2 then 3.3) and would that make the process any smoother than
> doing an upgrade larger than +0.1 ?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/apportable/SpriteBuilder/issues/222#issuecomment-33468586
> .

## 

Martin

**Comment by vlidholt** [comment]
Some more details on this:
- Good point with auto backup. Could be done by renaming the cocos2d-iphone folder to cocos2d-iphone.backup, before overwriting it.
- Need to check if cocos2d-iphone is a git sub-module (in that case just alert the user, don't perform the update)
- The version can be found in _Source/libs/cocos2d-iphone/VERSION_. SpriteBuilder 1.1 will require Cocos2d 3.1
- Latest Coocs2d version supported by SB is in the _Generated_ folder inside the default project. To get to it, it needs to be unzipped to the applications cache directory, and then copied into the currently opened project.

**Comment by vlidholt** [comment]
Almost implemented! :) Needs to point the browser to http://www.spritebuilder.com/update/ after the update is complete. This page contains additional information on how to update the project.

**Comment by vlidholt** [comment]
Fixed
