### ISSUE TITLE
BMFont has an extra file name when loaded in code which leads a crash

### ISSUE THREAD

**Issue by ryanflees** [spritebuilder/SpriteBuilder#249]
I added a bmfont in ccb file using ccbResources/ryan/font_4.fnt
It describes correctly in origin ccb file.
But after published into .ccbi file. 
In cocos2d-iphone 3.0 CCBReader reads ccb file into stringCache it gets a wrong bmfont file with an extra file name.
"ccbResources/ryan/font_4.fnt/font_4.fnt"

CCBReader has a bytes array contains properties of the ccb node. 
And it shows as following in memory watch which has a wrong bmfont name. CCBReader never modifies this, so maybe SpriteBuilder has published a wrong name.

bytes array in the CCBReader:
ibccÐanchorPointscalenamepositioncontentSizeSample TextCCNodestring
scrollView'ccbResources/ryan/font_4.fnt/font_4.fntDefault Timeline
pagingEnabled
CCLabelBMFontbounceshorizontalScrollEnabledCCScrollViewcontentNodeverticalScrollEnabled MusicMenucolorfntFile

**Comment by danielhaaser** [comment]
Just ran into this issue - SpriteBuilder published the bmfont location as something like: "BMFonts/font.fnt/font.fnt"

**Comment by NickyWeber** [comment]
To work on this bug, it would be helpful if you could provide some steps, like how to create a bmfont that produces this error. Right now I cannot repro this.
What version of SB are you referring to?

**Comment by danielhaaser** [comment]
This is SpriteBuilder release version 1.1.0.  Here's a demo project that has the error:

https://dl.dropboxusercontent.com/u/12134320/BMFontTest.spritebuilder.zip

**Comment by NickyWeber** [comment]
Thanks, I will have a look at this soon.

**Comment by NickyWeber** [comment]
Sorry it took that long, vacation and working on 1.2 RC.

The crash only happens on case sensitive partitions. The steps posted below should fix this issue.

@djh Downloaded your project. Noticed that the font used is not correctly named, although it might be working in SB. Here's how you can fix this.

**This is how it looks like when I open the project:**
![bildschirmfoto 2014-08-20 um 09 55 22](https://cloud.githubusercontent.com/assets/5259653/3977821/60e6b70e-283f-11e4-8e6d-34389f68059f.png)

This means, it is not treated as a bmfont for publishing, this results for me in an empty folder. 

**This is how it should look like in SB**
![bildschirmfoto 2014-08-20 um 09 54 33](https://cloud.githubusercontent.com/assets/5259653/3977831/88a1110e-283f-11e4-831a-a6bc39b664e7.png)

**Rename the font folder on the file system like this**
![bildschirmfoto 2014-08-20 um 09 54 54](https://cloud.githubusercontent.com/assets/5259653/3977833/953dab8e-283f-11e4-9aec-92fc66435702.png)

The naming pattern is `<fontname>.bmfont`
Where `fontname` is the same name as in the resolution subfolders of the png and fnt files without suffix.
`.bmfont` has to be all lower case, which may lead to problems on case sensitive partitions.

Please try to fix the demo project and leave a comment if there is still an issue.

**Comment by danielhaaser** [comment]
Oops, I wasn't aware of the changes in bmfont handling.  Totally works, thanks!
