### ISSUE TITLE
Project Settings option causes the app to crash when no .ccb is opened

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#253]
Hi there,

Just found a reproducible crash of the app. Repro steps:

Open a SpriteBuilder project;
Make sure no .ccb files is opened by either not open any .ccb files or close all opened .ccb files.
Open Project Settings window through the File menu.
Click Done.
The app crashes.
This happens on SpriteBuilder v1.0.3 from the App Store.

Hope this helps!

**Comment by NickyWeber** [comment]
I think I fixed it, pull request is on the way.
