### ISSUE TITLE
"Unable to checkout" with submodule cocos2d-iphone

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#257]
I tried to clone the latest commit twice, but I get this error every time:

Submodule path 'SpriteBuilder/libs/ssziparchive': checked out 'd9ea638369f5bde0b470acd9056705e0daffb031'
Unable to checkout '34a98be97df83d5c5baef2ef8e02d3a9062baea8' in submodule path 'SpriteBuilder/libs/cocos2d-iphone'
xxxx:SpriteBuilder xxx$ git submodule update --init --recursive
fatal: reference is not a tree: 34a98be97df83d5c5baef2ef8e02d3a9062baea8
Unable to checkout '34a98be97df83d5c5baef2ef8e02d3a9062baea8' in submodule path 'SpriteBuilder/libs/cocos2d-iphone'

**Comment by vlidholt** [comment]
Fixed.
