### ISSUE TITLE
Keyframes can, incorrectly, in some cases be on top of each other

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#26]
In some cases copy/paste/drag multiple keyframes can end up on top of each other. Older keyframes should be replaced when dragging or pasting on top.

**Comment by vlidholt** [comment]
Haven't verified this issues. Needs to check if this is still a bug.

**Comment by jtwigg** [comment]
Repro's and Fixed.
Fixed in the case where copy/paste was used. Add removeDuplicates code to the end of the function.
