### ISSUE TITLE
Set 'collisionType' in SpriteBuilder

### ISSUE THREAD

**Issue by Ben-G** [spritebuilder/SpriteBuilder#261]
Would be great to add some properties of CCPhysicsBody to SpriteBuilder. I often set up custom classes just to set one or two properties on a physics body.

Most importantly it would be great if the 'collisionType' could be set in SpriteBuilder.

**Comment by vlidholt** [comment]
This should definitely go in the editor! :)

**Comment by vlidholt** [comment]
Part of #224

**Comment by vlidholt** [comment]
This is fixed on develop! :)
