### ISSUE TITLE
Feature request: pngquant or OptiPNG image compression

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#266]
It would be great to have those tools available as image export options.

**Comment by NickyWeber** [comment]
OptiPNG is done but not merged yet. As for pngquant there are no plans at the moment. We want to keep it simple, pngquant can have a bad impact on visual quality without using the right settings, so a case by case situation may arise. This may overcomplicate spritebuilder. We will see how demand is.

**Comment by jan-happy** [comment]
It would be a dream to have the features of ImageOptim in the app.

**Comment by NickyWeber** [comment]
Can you describe the workflow after such an integration? I am curious where the benefits will be.

**Comment by jan-happy** [comment]
One could set the optimization-parameters for each PNG or for a group of selected PNGs.
Upon first publishing each PNG would be compressed, subsequent publishing would only compress the changed PNGs.

In my project I have a lot of PNGs which I compress after publishing with ImageOptim. Average filesize loss is 43%.
But after publishing all my nicely compressed PNGs get overridden with the bigger PNGs that SpriteBuilder produces.

Fast workaround would be a flag in the SpriteBuilder settings: "Don't override newer assets in 'Published' folder." That way my compressed files would not be overridden because they are newer than the files in the SpriteBuilder Resources folder.

**Comment by NickyWeber** [comment]
You can run ImageOptim on the command line. Write a script that does all the work for you and just run it afterwards. It would be just not feasible workwise to reimplement good and battle proven tools which are not absolutely essential for SpriteBuilder, just my humble opinion. 

Maybe a run script phase would help to incorporate post publishing steps to automate these kind of scenarios.

**Comment by jan-happy** [comment]
I agree with you, but still: To avoid the long process of re-optimizing each png after every publishing, we need an option to turn off overriding of already optimized files by SpriteBuilder.

**Comment by NickyWeber** [comment]
I will talk about this with Viktor next week. Thanks for the feedback.

**Comment by jan-happy** [comment]
Dufte!

**Comment by NoorFatima** [comment]
This feature is now added.

Sprite Builder: 2.0.0
SB Revision: 3c4db042ec

**Comment by jan-happy** [comment]
Great news, thank you!
