### ISSUE TITLE
Custom objects not released using animation manager delegate

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#270]
Just ran instruments on a project and noticed that a bunch of child objects were not being released with their parent. The cause was the CCBAnimationManager delegate retaining the custom objects.

Took a look at CCBReader and the delegate property is set to retain (strong) if i change the delegate property to weak in CCBReader everything is released correctly.

Not sure if this is by design, or if there is a better way to implement CCBAnimationManager so that it will release the delegate.

**Comment by vlidholt** [comment]
This should be changed to weak as it seems to be the more correct behavior.

**Comment by vlidholt** [comment]
It's also possible that there is some memory leak related to either loading nodes or animations. See this: http://forum.spritebuilder.com/t/memory-management-guide/577
