### ISSUE TITLE
[bug] CMD-C does nothing.

### ISSUE THREAD

**Issue by matthijn** [spritebuilder/SpriteBuilder#277]
Copy only works through the menu, CMD-C is not set as a shortcut. It's fairly annoying.

![screen shot 2014-02-24 at 11 19 21](https://f.cloud.github.com/assets/1755544/2244407/5fd04f48-9d3d-11e3-8ba6-ae24a98189c7.png)

**Comment by cocojoe** [comment]
Thanks however this functionality is available in latest source. Expect to see it soon in a new release.
