### ISSUE TITLE
[Crash] Publishing large number of images.

### ISSUE THREAD

**Issue by matthijn** [spritebuilder/SpriteBuilder#282]
When publishing with a large amount of images (252 flags of 150px bij 113px) the editor crashes every time.

I've added the crash report, perhaps that is helpful.

Thanks.

https://gist.github.com/Matthijn/9212078

**Comment by NickyWeber** [comment]
Can you please retry with a more up to date revision, we changed a few things regarding publishing.

**Comment by NoorFatima** [comment]
This issue is fixed.
Device: Mac OS X 10.9.5
SB Version: 1.4.7

**Comment by Shahidwerplay** [comment]
This issue is fixed. 

Mac OS X: 10.10.0
SB Version 1.4.9
XCode 6.1
