### ISSUE TITLE
Lock/hide nodes in editor

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#29]
There should be options for locking and hiding nodes in the editor. This would be very useful for editing more complex files.

**Comment by jtwigg** [comment]
do we:
a) Have a right click context menu on nodes in the editor.
b) Have 2 checkboxes in "Item Properties" for 'hidden' and 'locked'. 
Or Both.

**Comment by jtwigg** [comment]
Add 2 columns to SequencerOutline,.

**Comment by jtwigg** [comment]
~Mute SFX.
~Should not select in editor NOR SequencerOutlineView

**Comment by jtwigg** [comment]
![screen shot 2013-11-13 at 4 20 48 pm](https://f.cloud.github.com/assets/1237233/1537288/aa69cafa-4cc2-11e3-9d8b-69a29b371441.png)

Preview of what it will look like.

**Comment by jtwigg** [comment]
I believe it's done!
