### ISSUE TITLE
Possible to make a Visual Novel (Text Interactive Game) ?

### ISSUE THREAD

**Issue by shubhank008** [spritebuilder/SpriteBuilder#292]
Hey guys is it possible to make a Visual Novel aka text interactive scene based game with SpriteBuilder ?

Such a game usually has a graphic scene, story plays as text and at diff points in story/scene user has to make a choice (click 1 of the x number of buttons on screen) and the story changes or continues depending on his choice.

I saw the demo video of sprite builder but still confused if it supports this kind of game.

If it does, can anyone give me a hint or point me in right direction to get started ?

**Comment by vlidholt** [comment]
Hi, this is definitely possible to do with SpriteBuilder! You may want to post these kind of questions in our forum instead: forum.spritebuilder.com there will be more people there who can help you get started!
