### ISSUE TITLE
Caching is broken

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#294]
Caching of smart sprite sheets (possibly other image assets too) is broken. This causes SB to always repack the assets, even if they haven't changed. This makes publishing extremely slow for medium to large projects.

Possible updates that may have broken the publisher:
- The updated support for pvr textures (using lib instead of tool)
- Addition of .psd support
- Possibly something else

**Comment by NickyWeber** [comment]
Fixed.
