### ISSUE TITLE
Error when building : "CCPhysicsSpringJoint.ccbPlugNode: No such file or directory"

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#310]
Pulled a clean version, updated submodules, but running the build script produces this error:

xxxs-mac-pro:SpriteBuilder xxx$ cd scripts
xxxs-mac-pro:scripts xxx$ ./BuildDistribution.sh 1.x

=== GENERATING COCOS2D SB-PROJECT ===
Generating: PROJECTNAME

=== GENERATING SPRITE KIT SB-PROJECT ===
Generating: SPRITEKITPROJECTNAME

=== CLEANING PROJECT ===
*\* CLEAN SUCCEEDED **

=== BUILDING SPRITEBUILDER === (please be patient)
error: /Users/xxx/Desktop/SpriteBuilder/SpriteBuilder/build/Release/CCPhysicsSpringJoint.ccbPlugNode: No such file or directory

PBXCp build/Release/CCPhysicsPivotJoint.ccbPlugNode build/Release/SpriteBuilder.app/Contents/PlugIns/CCPhysicsPivotJoint.ccbPlugNode
    cd /Users/xxx/Desktop/SpriteBuilder/SpriteBuilder
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -strip-debug-symbols -strip-tool /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -resolve-src-symlinks /Users/xxx/Desktop/SpriteBuilder/SpriteBuilder/build/Release/CCPhysicsPivotJoint.ccbPlugNode /Users/xxx/Desktop/SpriteBuilder/SpriteBuilder/build/Release/SpriteBuilder.app/Contents/PlugIns
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -S /Users/xxx/Desktop/SpriteBuilder/SpriteBuilder/build/Release/CCPhysicsPivotJoint.ccbPlugNode/Contents/MacOS/CCPhysicsPivotJoint -o /Users/xxx/Desktop/SpriteBuilder/SpriteBuilder/build/Release/SpriteBuilder.app/Contents/PlugIns/CCPhysicsPivotJoint.ccbPlugNode/Contents/MacOS/CCPhysicsPivotJoint
*\* BUILD FAILED **

The following build commands failed:
    PBXCp build/Release/CCPhysicsSpringJoint.ccbPlugNode build/Release/SpriteBuilder.app/Contents/PlugIns/CCPhysicsSpringJoint.ccbPlugNode
(1 failure)
=== ZIPPING UP FILES ===

SpriteBuilder Distribution Build complete!
You can now open SpriteBuilder/SpriteBuilder.xcodeproj

**Comment by NickyWeber** [comment]
Did you update the submodules with --recursive? Does this error still persist?

**Comment by jan-happy** [comment]
It's fixed in the latest version, thanks!

**Comment by NickyWeber** [comment]
Sweet.
