### ISSUE TITLE
Feature request: Add "Resize CCButton to fit Sprite Image Frame"

### ISSUE THREAD

**Issue by jan-happy** [spritebuilder/SpriteBuilder#331]
Adding a CCButton that has no label, only an image, is tedious.
First you have to set the Sprite frames for all the states, but then the image ist totally distorted (9-slice scaling can't be disabled).
Then I have to look at the dimensions of the image, divide it by 4 and then I can fill the "preferred size" fields.
Only then the button with the image appears correctly.

Please add a function like "Set preferred size of button to the Normal sprite frame size".
Thank you!

**Comment by jonnyijapan** [comment]
I agree. Something like this would be helpful. A similar tedious task is when your artist hands you an updated image of a button. You just replace the image file name in SB, or even sometimes in code. The problem now is that the new image file size dimensions are different, but you fail to compare the sizes and/or update the preferred size of the ccbutton. In effect the button comes out stretched or just incorrect on device. Some kind of check (ns assert?) within cocos2d could help with this. Make sure that ccbuttons have the same size of the used ccsprite... I guess a simple solution is hard to find...

**Comment by NoorFatima** [comment]
This issue is fixed.
Device: Mac OS X 10.9.5
SB Version: 1.4.7

**Comment by jan-happy** [comment]
Great!
