### ISSUE TITLE
Make sure aligning is working correctly

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#34]
May be bugs related to aligning/distributing nodes. Needs testing (including multiple resolutions) and possibly bug fixes.

**Comment by jtwigg** [comment]
Tried all alignment options in iPhone/Tablet view. All works except for un-implemented 'Same Width'

Can you clarify any further testing that needs doing?

**Comment by vlidholt** [comment]
Ok, sounds like it's working! Closing this one.
