### ISSUE TITLE
The blend mode is reset on save

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#345]
It seems like the blend mode isn't being saved/loaded correctly. This needs to be fixed and verified with SpriteBuilder 1.1 and the new Cocos2D 3.1 blend mode class.

![output_za4pgm](https://cloud.githubusercontent.com/assets/1539812/2541718/1bfb57fc-b5e0-11e3-8398-3d864375138e.gif)

**Comment by NickyWeber** [comment]
I cannot confirm this as of commit d793e9c3294b7acc7145c434d2d6a068e9aea224. 

Something else I noticed is the blend is not applied until save is hit....That's a bug in cocos2d v3.1.
Fixed in pull request: https://github.com/cocos2d/cocos2d-iphone/pull/707
