### ISSUE TITLE
Snapping when moving objects

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#36]
Snapping for moving nodes around should be possible. There need to be an option (and hotkey) to enable disable this feature.

**Comment by vlidholt** [comment]
This should be implemented together with #335 . Someone has made an implementation of snapping, this needs to be reviewed to see if we can use it: http://forum.spritebuilder.com/t/snapping-aligning-nodes-to-other-nodes/829

Old and broken snapping code needs to be cleaned up.

**Comment by vlidholt** [comment]
Initial version sort of works a little bit, but quite a few issues remain:
- [x] Snapping to guides doesn't work.
- [x] Snapping lines and grid shouldn't be restricted to content size. Use same method as for drawing the regular guides. (Sprites instead of draw node). This will also fix a couple of the following issues.
- [x] Snapping to anchor point doesn't work.
- [x] Doesn't work with rotated objects.
- [x] Doesn't work with parent nodes being transformed.
- [x] Doesn't snap correctly to grid if the parent has moved.
- [x] Grid has inconsistent thickness depending on scale and device.
- [x] Need to be able to set grid size.
- [x] Snap lines doesn't show up for 'node' files. (Created with File > New > File... > Node)
- [x] Grid lines doesn't show up immediately when grid is turned on (you need to start manipulating objects).

**Comment by vlidholt** [comment]
- [x] Snapping guides stay on screen after an object has been deselected.
- [x] Snapping guides are off if children with a transformed parent are moved/snapped.
- [x] There needs to be a hotkey for temporarily disable snapping while dragging objects (cmd?)

**Comment by vlidholt** [comment]
- [x] Grid should fill the screen, not only the content area.
- [x] Edges and corners doesn't snap to guides.
- [x] The anchor point doesn't snap to edges of objects or to the edges of the screen.
- [x] Holding down cmd still snaps to guides and grid.
- [x] Horizontal position marker on the ruler is incorrectly colored.
- [x] Snapping to corners doesn't work correctly when an object is rotated.

**Comment by vlidholt** [comment]
- [x] Snapping lines appear when scrolling the main area and an object is selected

**Comment by vlidholt** [comment]
- [x] Menu setup:

Extras (cmd-shift-H) <- Shows/hides all extras, needs a toggle checkmark
Show
-> Guides <- needs a toggle checkmark
-> Grid <- needs a toggle checkmark
-> Sticky Notes <- needs a toggle checkmark
Edit Grid Spacing...

---

Snap (Cmd-U) <- needs a toggle checkmark
Snap To
-> Guides
-> Grid
-> Nodes

**Comment by vlidholt** [comment]
- [x] Text in grid spacing dialog is incorrect
- [x] Grid spacing needs to be saved per ccb-file

**Comment by cocojoe** [comment]
There is an issue with moving new guides on creation, you can move them when holding command, am aware just wanted to get bigger update in first.

**Comment by cocojoe** [comment]
Also made a quick video going over most of the good stuff: 

https://www.youtube.com/watch?v=cZWKnjgbZrA

**Comment by vlidholt** [comment]
Implemented
