### ISSUE TITLE
Crash on replaceScene:

### ISSUE THREAD

**Issue by the-old-one** [spritebuilder/SpriteBuilder#372]
When one scene calls:

```
- (void)openNextScene:(id)sender
{
    [[CCDirector sharedDirector] replaceScene: [CCBReader loadAsScene:@"SecondScene"]];
}
```

 second scene become loaded. Then in a few seconds we have a crash:
![mousestory__ccaction_m](https://cloud.githubusercontent.com/assets/3480944/2686699/d0714d4e-c216-11e3-8413-e2ff81628879.jpg)

![bugtest__ccaction_m](https://cloud.githubusercontent.com/assets/3480944/2686702/09f551b4-c217-11e3-9491-904c4bd06dab.jpg)

Reproducible with two clean scenes from last SpriteBuilder.

**Comment by the-old-one** [comment]
Reproducing of error with the last build.
http://youtu.be/vkEVvPeM-3Y

**Comment by cocojoe** [comment]
Thanks for this, sadly I never got any notification of this first time around.  It's been raised in #399  which I followed up on. So will close this one and continue in other.
