### ISSUE TITLE
Node stop actions does not work properly with chained timeline

### ISSUE THREAD

**Issue by carneirocarlos** [spritebuilder/SpriteBuilder#373]
1 - put a node/sprite in the stage
2 - animate it in the timeline (location, rotation, whatever)
3 - put that timeline to be chained
4 - in the code, remove all actions for that animated object

You'll see that it will stop actions in the object but when the timeline start again, the object will start animating.

**Comment by cocojoe** [comment]
So when the animation loops restarts which will then recreate the actions and restart animation, what do you think should happen?

**Comment by carneirocarlos** [comment]
I think that I said to stop the animations, it must stay stopped!
am I wrong?

**Comment by cocojoe** [comment]
There are callback actions placed on the rootNode that you must have missed.  The current version doesn't really have pause/resume/stop functionality.

There is new animation code that will facilitate this so you can simply pause the animation, this is coming very soon.

**Comment by carneirocarlos** [comment]
@cocojoe I just added this:

if ([node paused]) {
return;
}

in runAnimationsForSequenceId to solve temporarily my problem:

Then I stop like thins in the code:

[node setPaused:YES];
