### ISSUE TITLE
Nudge with arrow keys instead of cmd-arrow keys

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#39]
As the title says.

**Comment by jtwigg** [comment]
change it to shift-arrow.

**Comment by vlidholt** [comment]
Had to reopen this. Currently, using the arrow keys will nudge objects even when editing text fields etc. This isn't so good. I think that the keydowns need to be handled in the GL view (and only when it has the focus).

**Comment by jtwigg** [comment]
settled on Cmd-left and Shift-Cmd-Left.
Also, Sequencer outline view also retains firstResponder so you can navigate items with the keyboard.
