### ISSUE TITLE
Spritesheet squared dimensions

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#390]
We have a number of 4096x4096 spritesheets in Spritebuilder which can be reduced to 4096x2048 using TexturePacker and the like.

Is there a reason Spritebuilder only builds spritesheets with squared dimensions?

**Comment by NickyWeber** [comment]
No, the packing algorithm is just not that perfect.

**Comment by danielhaaser** [comment]
Hey Conor, this should fix it:

https://github.com/djh-/CocosBuilder/commit/20d6402fc4aa8b780cd1ad818612c006f82829ec

**Comment by ghost** [comment]
Awesome, thanks!
