### ISSUE TITLE
Add new user guide as part of SpriteBuilder

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#391]
There is a new user guide made by MGWU. We need to figure out how to make this part of the built in documentation. A first step could be to simply open it up in a web browser.

This should replace the old official user guide. We also need to make sure that the MGWU docs contains all parts that are currently in the old user guide (e.g. the section about how to create bitmap fonts and other important things that are currently not in there).

**Comment by NickyWeber** [comment]
+1 for a website!

**Comment by cocojoe** [comment]
+1 Browser, keep it simple.

On 23 April 2014 13:01, Nicky Weber notifications@github.com wrote:

> +1 for a website!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spritebuilder/SpriteBuilder/issues/391#issuecomment-41152489
> .

## 

Martin

**Comment by Ben-G** [comment]
@vlidholt , if you want me to use the old documentation for the parts that are currently missing I'm happy to transfer them to the new documentation today! Since both is in Markdown this should be very easy.
