### ISSUE TITLE
Test performance and memory leaks

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#392]
Need to do testing to see how SpriteBuilder performs with larger files with lots of nodes, physics bodies and joints.

Also check for potential memory leaks, etc.

**Comment by NickyWeber** [comment]
Haven't tested yet again but the CCRenderStateCache was increading memory after scene switches like 1.5 weeks ago. Not leaks just abandoned memory.

**Comment by vlidholt** [comment]
This may be tested enough for 1.1. I will move this forward to 1.2.
