### ISSUE TITLE
Numbers are not visible on the rulers

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#393]
As the CCLabelAtlas has been removed from Cocos2D 3.1 the numbers are no longer visible on the rulers. This needs to be fixed and there are a couple of possible solutions:
- Add an extra constructor to CCLabelBMFont that makes it work like CCLabelAtlas did
- Draw the text using individual sprites for each number
- Create a bitmap fnt file for the font (needs to use the current image though so the styling remains the same).

This needs to be compared with the 1.0.6 version so it looks the same.

**Comment by NickyWeber** [comment]
What's the name of the font used for the labels? Or was it drawn by hand?

**Comment by NickyWeber** [comment]
Fixed in https://github.com/spritebuilder/SpriteBuilder/pull/396.
Tried to get as close to the original font as possible.

**Comment by vlidholt** [comment]
The rulers are now looking ok but have a different color. Also the time markings in the timeline were removed in the process...

**Comment by vlidholt** [comment]
Fixed

**Comment by NickyWeber** [comment]
Sorry for those lost timeline markings, my bad.
