### ISSUE TITLE
Crash in CCBAnimationManager when Node is removed

### ISSUE THREAD

**Issue by MarcelBloemendaal** [spritebuilder/SpriteBuilder#399]
When a CCNode is removed that has a running timeline, it's CCBAnimationManager is not properly cleaned up and causes a crash when the timeline finishes.

Example can be found in repository:
https://github.com/MarcelBloemendaal/CCBAnimationManager-bug-example

Steps to reproduce:
1. Launch project
2. Press the 'TestScreen' button. This pushes the TestScene on the CCDirector
3. Within 8 seconds, press the 'Back' button. This pops the TestScene from the CCDirector again.
4. Wait. (8 seconds max) The app crashes.

Presumable cause:

The CCBAnimationManager related to the TestScene is not properly cleaned up, and keeps playing the Default Timeline of the scene, that no longer exists. When the timeline ends, it will try to call a function and crash.

**Comment by cocojoe** [comment]
Hey thanks for the sample project, will take a look at this right now.

**Comment by cocojoe** [comment]
Scheduler doesn't get released, I'll probably just change the object to sub class CCNode as that includes all of the scheduler functionality anyway and will cleanup correctly. (I just tested it).

**Comment by MarcelBloemendaal** [comment]
That could work. If you let me know when this is done, I can test in a bigger project if all problems are resolved. Thanks for the feedback!
