### ISSUE TITLE
Save window layout

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#40]
Save the window size and layout in-between sessions.

**Comment by xofneb** [comment]
+1

**Comment by vlidholt** [comment]
Pull request #457 may serve as a starting point for this feature.

**Comment by vlidholt** [comment]
Need to be tested when moving from different resolutions, with different screens plugged in etc.

**Comment by NickyWeber** [comment]
Created a new pull request, based my code on FahimF's.
