### ISSUE TITLE
CCBFile display name in timeline.

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#401]
If a an existing resource node is dragged into the time line and it has a custom class then this will be the name displayed in the timeline.  If it does not have a custom class it will simply be displayed as CCBFile which is not  very descriptive when you have a few.

It think it would be beneficial to display the name of the resource when a custom class is name is not available.

**Comment by GroundhogGrafix** [comment]
Actually I think it may be more beneficial to display the resource name only, just in case you have different objects using the same custom class.

**Comment by LearnCocos2D** [comment]
This is probably related: https://github.com/spritebuilder/SpriteBuilder/issues/461
