### ISSUE TITLE
CCBReader additional allocations (not released) in 3.1, not present in 3.0

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#402]
While debugging #399 I noticed that when loading a very basic scene it would init CCBAnimationManager twice.  This seemed a bit odd but just presumed that's how it was, so I backported the #399 fix to 3.0 and noticed that 3.0 would only init CCBAnimationManager once for the same scene (makes sense) and would correctly alloc/dealloc on scene replace etc

In 3.1 the second manager is never released and will keep growing each replace.

**Comment by cocojoe** [comment]
3.1
https://www.dropbox.com/s/msafrd7avj8vju7/simplescreen31.spritebuilder.zip

3.0
https://www.dropbox.com/s/xb78td3sh51h0oj/simplescene30.spritebuilder.zip

Both have updated code that fixes #399 to correctly dealloc CCBAnimationManager gracefully.

**Comment by the-old-one** [comment]
It working. Thanks!

**Comment by MarcelBloemendaal** [comment]
We are also still having problems that seem related to #399 / #402 / #372. We've tried using the cocos version from your fix (3.1) above, and also added all changes from your pull request (https://github.com/cocos2d/cocos2d-iphone/pull/721) but there are still some problems.

One problem:
In some cases, in CCScheduler -> InvokeMethods (line 85 or so) during the for loop, some CCSchedulerTargets can become invalid. More specifically: the for loop iterates through a copy of the methods array, during which some members of the original array are removed. The CCSchedulerTarget object remains in the copy, but it's target (a CCBAnimationManager object) becomes dealloced, even though the target var seems to be strong.

I hope my explanation is clear enough. I would post an example if I could, but this is part of a big project, and I haven't been able to isolate the case.

There also still seem to be problems with removing a ccnode from it's parent when it has an active CCBAnimationManager, but we are still looking into that.

**Comment by cocojoe** [comment]
Could do with a simple sample project please to investigate.  Ideally pull in latest cocos2d develop code.  Ideally just a single SpriteBuilder scene?

Thanks

**Comment by MarcelBloemendaal** [comment]
I am still working on a more isolated case for both problems, but I won't make that today. I'll try to get a sample project as soon as possible. We'll keep you posted!

**Comment by TimPelgrim** [comment]
I created an isolated case in which the problem mentioned by @MarcelBloemendaal occurs. It seems we could not reproduce the issue in a new project so we stripped down the project to just contain the issue.

https://github.com/TimPelgrim/Spritebuilder_issue_399

**Comment by cocojoe** [comment]
Thanks, will have a look when I can.

On Tuesday, 29 April 2014, TimPelgrim notifications@github.com wrote:

> I created an isolated case in which the problem mentioned by
> @MarcelBloemendaal https://github.com/MarcelBloemendaal occurs. It
> seems we could not reproduce the issue in a new project so we stripped down
> the project to just contain the issue.
> 
> https://github.com/TimPelgrim/Spritebuilder_issue_399
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spritebuilder/SpriteBuilder/issues/402#issuecomment-41667883
> .

## 

Martin

**Comment by TimPelgrim** [comment]
@cocojoe It seems our problem has to do with setting the target level to 7.0. With the Spritebuilder default target of 5.0 the problem does not exist.

**Comment by cocojoe** [comment]
What about with target level of iOS 5.1,6 or 6.1 etc? Just wondering at what point does iOS change to cause a problem.  Appreciate the feedback.

**Comment by MarcelBloemendaal** [comment]
It would seem that our (TimPelgrim and me) earlier conclusion that the target level matters is not correct. In any case, the simple example project crashes sometimes, but not always. However: when you use instruments (zombies) or turn on zombies in the diagnostics settings in the launch scheme in XCode, it will always register a zombie.
This zombie is always the CCBAnimationManager, released once too many. In the Example project we included, we also noticed that when you look at the retains / releases in instruments, a release of the CCBAnimationManager in CCActionSequence->update seems odd. (At the end of the list, in the screenshot)

![screen shot 2014-05-01 at 11 11 38](https://cloud.githubusercontent.com/assets/3262891/2851046/cd361264-d110-11e3-8acc-73c0ea427893.png)

I also tried to made the example even simpler: in the TestScene.m I now just create the remove action and run it on the node. This still causes a zombie on CCBAnimationManager, but this time the list in instruments looks like below, with a suspicious release in CCActionManager->update.

![screen shot 2014-05-01 at 09 49 29](https://cloud.githubusercontent.com/assets/3262891/2851089/948be2ee-d111-11e3-84d1-7310c8c83e54.png)

I have tried to find a problem in the ActionManager, or sequence, but I'm not sure exactly what happens in there.

**Comment by TimPelgrim** [comment]
Turns out the problem is very easy to reproduce and has nothing to do with target versions.

Create new project with empty scene, load custom CCB file using CCBReader in code and add to stage and run the remove action. This does not crash in all cases but it does message a zombie object in all cases, these become visible by enabling 'Zombie Objects' in your scheme. 

e.g.

```
CCNode *node = [CCBReader load:@"TestNode"];
[self node];
[node runAction:[CCActionRemove action]];
```

**Comment by slembcke** [comment]
O_o Not really sure how that can happen without a compiler bug in ARC. I don't see anything suspicious in the memory trace above.

Is it possible to cast retainable qualifiers in some unsafe way? Hmm. ARC makes debugging memory issues 10x harder. :(

**Comment by cocojoe** [comment]
I noticed that you havn't tried the full pull request as you still have the double CCBReader allocation issue in your project. 
https://github.com/cocos2d/cocos2d-iphone/pull/721

I just ran through this and added a little extra to the cleanup which fixed the issue in your sample project.

**Comment by MarcelBloemendaal** [comment]
We can NOT be THIS stupid... X_x

You are correct, we mixed up the changes from the earlier 3.1 zip file and the pull request, causing the obviously better changes of the pull request not to be completely implemented. After fully checking and replacing, everything works. In the sample project, as well as our much larger real project. Many thanks for looking into this cocojoe and slembcke.

**Comment by NickyWeber** [comment]
Is this issue still... an issue?

**Comment by cocojoe** [comment]
No
