### ISSUE TITLE
Categories and Masks Cleared When Saving

### ISSUE THREAD

**Issue by mikeytdan** [spritebuilder/SpriteBuilder#405]
Version: 2.x
Github: f9c62c3e00
Latest commit on the develop branch.

When ever I save after entering a category or mask into the properties inspector they are cleared/erased.

**Comment by mikeytdan** [comment]
Fixed, sent a pull request. :)

**Comment by sana20** [comment]
This issue is fixed.

Mac OS X: 10.10.1
XCode: 6.1.
SB Version: 1.4.7.
