### ISSUE TITLE
Update ccbi file format to use more efficient integer encoding

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#415]
Move to use variable length quantity encoding for integers. It will reduce the file size and loading speed significantly (20% smaller files, 2-3 times loading speed). Source code for this here:

https://gist.github.com/newnon/0b2a9141217383648a21

The version number of the file still needs to use the old encoding for backwards compatibility on error messages.

**Comment by vlidholt** [comment]
Also do some sort of performance test for this.

**Comment by jtwigg** [comment]
The  performance improvements are noticable, but  not massive.
FileSize: Before:10581bytes, after 9897:   = 6.5% file decrease.

Deserialization:
Before : Average TimeToRun on 6 runs of 100,000 plus throwing out largest: 1.319 Seconds
After    : Average TimeToRun on 6 runs of 100,000 plus throwing out largest: 1.122 Seconds
~= 15% speed increase.

**Comment by NickyWeber** [comment]
In the long run this will save millions of labor hours!

**Comment by vlidholt** [comment]
...and hard drives

**Comment by jtwigg** [comment]
Done.
