### ISSUE TITLE
"Sprite" CCB: can't animate anything besides spriteframe, opacity, color

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#442]
Bummer. In a CCB of type "Sprite" I can't seem to create a timeline for properties other than spriteframe, opacity and color.

I understand how position is going to be a problem, and perhaps scale, but rotation, skew (which I was looking for) and visible still ought to be animatable. Even if the end result may depend on settings in the CCBfile node and thus vary from what you see in SB.

**Comment by collidernyc** [comment]
I'll add to this, as it's probably related  - there is still no twirl down triangle when adding keyframes to a CCSprite. If I create a new Sprite CCB, click on CCSprite, right click on a frame sequence and "Create Sequence From Selection", the CCSprite keyframe editor remains closed and un-editable. Adding a single opacity keyframe will open the keyframe editor, but there is still no triangle to open/close in the future.

**Comment by cocojoe** [comment]
Fixed in 1.3.1-c.1
