### ISSUE TITLE
"Animation of physics bodies" message incorrect and overzealous

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#443]
When adding a keyframe to a timeline of a node which has physics enabled, I get this message:

![screen shot 2014-05-06 at 17 45 40](https://cloud.githubusercontent.com/assets/214599/2891717/98339540-d535-11e3-8da4-caf5c779cc3c.png)

However the message is the opposite of what happens. My body is already dynamic, and after clicking OK the node was set to a static body. Either the message text is wrong, or it has been triggered incorrectly and then it just negated the "dynamic" flag. 

If the node's physics body is already static when adding the first keyframe the message is not shown.

Furthermore this warning is a bit overzealous because what I wanted to animate was simply opacity, not any of the properties that I would expect to conflict with physics (position, scale, rotation, skew). Opacity, color, sprite frame and visible should still be animatable.

This was with today's develop version.

**Comment by vlidholt** [comment]
Message is not correct, the text has been swapped around. Keyframes are only allow don static bodies.
