### ISSUE TITLE
Moving node while animation not possible, flickers

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#451]
Create a timeline animation, two keyframes one at each end. Play back the animation with loop button checked. Add another node. Try to move the node by dragging.

It may seem to work okay the first time, but trying to drag the node (even if it has no keyframes/no animation at all) will make it flicker between current and original position while an animation is playing. If you let go, the node will snap back to its original location.

Workaround is to stop the animation before moving nodes.

**Comment by vlidholt** [comment]
Any operations should stop the playback in the timeline

**Comment by LearnCocos2D** [comment]
I also noticed while animations are playing you can't edit text boxes, possibly other controls too, as each frame advancing the animation seems to remove the focus from the edited control.

**Comment by vlidholt** [comment]
Yes, it's expected behavior to disable property editing/updating while the animation is playing back. (It's really slow to update the properties during playback, and editing changing values isn't exactly a good user experience anyway :P )

**Comment by vlidholt** [comment]
I can still edit things when the animations are playing. There are more cases when the animations needs to be stopped (may be more things than listed):
- Opening/Saving
- Clicking the canvas (can currently select an object and it's still playing)
- Switching documents

**Comment by NickyWeber** [comment]
- [x] Switching Documents
- [x] Opening/Saving
- [x] Selecting objects on stage
- [x] Publishing
- [x] Timelines: edit, change duration, change, create new, duplicate.
