### ISSUE TITLE
Default included Apportable project

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#47]
The default project created should include an Apportable project in addition to ccbproj and Xcode project. Also needs to test that it's all working and that the options that export options work with Android.

**Comment by vlidholt** [comment]
1. The Xcode projects created with SpriteBuilder are not parsed correctly. It’s because SpriteBuilder includes Cocos2d as a sub-project and Cocos2d in turn includes Chipmunk as a sub-project.
2. NSAttributedString doesn’t compile with Apportable. There is a different code path that Cocos2d can use that works without the NSAttributedString, but it would be nice if we at least had empty classes/methods so that it compiled.
3. Drawing shadows and outlines doesn’t work with Apportable. This would be a nice to have. Cocos2d is using Core Graphics to do this.
4. Cocos2d has new default settings for setting up the screen and OpenGL projection with different devices. There are two modes (fixed and flexible) and also portrait/landscape are supported. When compiling with Apportable, we should setup reasonable default settings for any device. If needed we can add code to Cocos2d to do this nicely (e.g. emulate iPhone/iPad resolutions).
5. SpriteBuilder has the ability to export a different set of resources for iOS and Android. E.g. caf & mp4 sounds for iOS and ogg for android. This goes for image resources too. On iOS the supported options are png, png-8, pvr, pvrtc and jpg. We need to figure out which of these to support on Android. I know this is a complex topic, and initially we may want to only support png & jpg. However, we need to make sure that the Android devices will load the correct set of resources. This essentially means swapping out a blue folder in Xcode when building with Apportable.
6. Provide correct approj files next to the xcodeproj so that it is super easy to get started with Apportable.

**Comment by vlidholt** [comment]
Done

**Comment by iWhacko** [comment]
I see this issue has been marked as closed. However with the current SpriteBuilder from the AppStore I cannot compile for android (NSattribtedString errors and others). 

If I build from source, there are some issues getting Chipmunk to link with cocos2d. Any tips on how to setup a working project?
