### ISSUE TITLE
Editing Anchor points of color node in properties inspector are inverted.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#479]
Description:
1. Launch SpriteBuilder.
2. Create a new layer, name it test.ccb, make it a type of layer.
3. Drag color node on the screen.
4. Edit "Anchor point" in properties inspector x from 0 to 1.

 -- Result: It moves the object in inverted direction, like moved object to -1 of x-axis. Same behavior is observed for y-axis.
    This happens 3/3 times.

Build version used: SpriteBuilder-1.1.0-beta.1

Note: Link to the video is given below.
https://drive.google.com/a/werplay.com/file/d/0B2b3lCCE3OwtLTlPNUdVekRKVDg/edit?usp=sharing

Used: MacBook Pro
Version: OS X 10.9.2(13C64).
Processor: 2.66 GHz Intel Core i7

**Comment by Kanoot** [comment]
Exactly same issue was found using "Gradient Node".

One more issue of gradient node is that while changing the blend of shades using vector axis, it shades the inverted sides. Screenshot is attached, you can see that the original color was black and it blended blue shade at the negative of x-axis while we typed a positive value.
![inverted shades](https://cloud.githubusercontent.com/assets/7566802/2961647/ecc7057c-dac8-11e3-83b2-f81291429365.png)

**Comment by vlidholt** [comment]
This is working as expected. Read up on anchor points in the _node_ section of the user guide: https://www.makegameswith.us/docs/
