### ISSUE TITLE
CCButton / CCLabelTTF

### ISSUE THREAD

**Issue by jsbeckham** [spritebuilder/SpriteBuilder#48]
Is it possible to anchor the CCLabelTTF in the CCButton control? I thought maybe the horizontal / vertical padding might do this but it doesn't seem to have an effect. 

Sorry - can't figure out how to move this to the question category.

**Comment by vlidholt** [comment]
Currently you cannot do this in SpriteBuilder. You can edit/position the label in code once your interface file has been loaded by accessing the buttons label property. E.g. myButton.label.position and myButton.label.positionType (default position type is CCPositionTypeNormalized).
