### ISSUE TITLE
Color node + - options on the color window are untappable, they are not working. 

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#481]
Description:
1. Launch SpriteBuilder.
2. Create a new layer, name it test.ccb, make it a type of layer.
3. Drag color node on the screen.
4. Tap color under CCNodeColor in properties inspector.

-- Result: Color node + - options on the color window are untappable, they are not working. Screenshot is attached.
![- options](https://cloud.githubusercontent.com/assets/7566802/2960205/81e0d368-daba-11e3-847b-fca4ef9e6a7f.png)

This happens 3/3 times.

Build version used: SpriteBuilder-1.1.0-beta.1

Used: MacBook Pro
Version: OS X 10.9.2(13C64).
Processor: 2.66 GHz Intel Core i7

**Comment by Kanoot** [comment]
Exactly same issue mentioned above was found using "Gradient Node".

**Comment by vlidholt** [comment]
This is the expected behavior. You will need to create your own color scheme to add colors to it (use the settings menu in the top right).
