### ISSUE TITLE
Include git ignore file in default project

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#482]
Include a git ignore file with sensible presets to the default SpriteBuilder projects. Would make it easier to get started with git.

**Comment by cocojoe** [comment]
Decent starting point, https://github.com/github/gitignore/blob/master/Objective-C.gitignore

**Comment by vlidholt** [comment]
Need to also exclude ppng files and published directories.

**Comment by vlidholt** [comment]
The git ignore file still doesn't include the following files:

Source/Resources/Published-iOS
Source/Resources/Published-Android
*.ppng

Perhaps the published dirs should have a more general form in case the user puts the whole SpriteBuilder project in a sub directory.
