### ISSUE TITLE
CCTextfield doesn't change the position even when we change position from property inspector

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#489]
1. Launch application.
2. Drag drop CCTextfield on the Mainscreen.ccb file.
3. Select CCTextfield.
4. Change the value of Position in the property inspector.
   
   -- Result: Position on main screen doesn't change whatever position we change it to.
      This happened 3/3 times.

![screen shot 2014-05-14 at 7 31 02 pm](https://cloud.githubusercontent.com/assets/7450007/2973010/942f8798-db79-11e3-8b64-814a902b0700.png)

Found on SpriteBuilder-1.1.0-beta.0.zip

Mac 10.9.2.
2.4 GHz Intel Core i7
8 GB 1333 MHz DDR3

**Comment by sana20** [comment]
This issue is fixed.

Build: SpriteBuilder-1.3.6.rc.1
Mac OS X: 10.9.5
XCode: 6.0
