### ISSUE TITLE
Looping

### ISSUE THREAD

**Issue by Myran** [spritebuilder/SpriteBuilder#49]
An option to loop current animation when pressing play button. This is needed when creating walking animations and similar.

An even better alternative would be an option to play the current chain of animations  when pressing play to view how different animations mesh together.

**Comment by vlidholt** [comment]
Should be implemented as an extra toggle button next to the playback controls. When on, the current sequence loops.

**Comment by jtwigg** [comment]
Possible looping buttons...

![image](https://f.cloud.github.com/assets/1237233/1604717/1fb10cda-53c4-11e3-8c0f-b1bc4357afab.png)

![image](https://f.cloud.github.com/assets/1237233/1604754/03ff680a-53c5-11e3-9d3e-813c2a10bd20.png)

**Comment by jtwigg** [comment]
submitted checkbox. Needs art.

**Comment by vlidholt** [comment]
I will drop in art on Monday!

**Comment by jtwigg** [comment]
You on Skype for a chat?

**Comment by Myran** [comment]
IMHO looping could be implemented as a toggle option below the play in animation menu.

This solution doesn't clutter the ui with another button and lets the user have the same hotkey for play in both cases. Also the use case for using both button is rare, most of the time its one or the other.

I implemented this solution in cocosbuilder and my graphics designer had no problem using it.

**Comment by vlidholt** [comment]
Fixed the artwork
