### ISSUE TITLE
Content size is not editable on "Text field", "Label TTF" and "Label BM-Font".

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#490]
1. Launch application.
2. Drag drop "Text field" on the Mainscreen.ccb file.
3. Select Text field.

-- Result: Content size is not editable on "Text field", "Label TTF" and "Label BM-Font". Screenshot is attached.
![content size](https://cloud.githubusercontent.com/assets/7566802/2973118/c51794bc-db7a-11e3-90d0-99726044c9d8.png)

This happens 3/3 times.

Build version used: SpriteBuilder-1.1.0-beta.1

Used: MacBook Pro
Version: OS X 10.9.2(13C64).
Processor: 2.66 GHz Intel Core i7

**Comment by vlidholt** [comment]
This is the correct behavior. You edit the labels size by setting it's dimensions (look further down in the property list).
