### ISSUE TITLE
Complete text is not displayed on the text box when run in Xcode.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#493]
1. Launch application.
2. Drag drop "Text field" on the Mainscreen.ccb file.
3. Check the user interaction enabled box in properties inspector.
4. Publish the project to make assets available in xcode.
5. Start typing on iOS Simulator.

-- Result: Complete text is not displayed on the text box when run in Xcode.

This happens 3/3 times.

Note: Video is attached here
https://drive.google.com/a/werplay.com/file/d/0B2b3lCCE3OwtUlFvQ1p2bGJaSzg/edit?usp=sharing

Build version used: SpriteBuilder-1.1.0-beta.1

Used: MacBook Pro
Version: OS X 10.9.2(13C64).
Processor: 2.66 GHz Intel Core i7

**Comment by khanbhai89** [comment]
This issue is fixed on SpriteBuilder 1.3 RC on:

Mac OS X: 10.9.5
XCode: 6.0.
