### ISSUE TITLE
Parent-relative-size does not work correctly on iPad

### ISSUE THREAD

**Issue by Ben-G** [spritebuilder/SpriteBuilder#5]
For a button I have selected a relative height and relative width of 25%. This works as expected on the iPhone. On the iPad the size turns out to be 50% instead of 25%. See attached screenshot.

Can be reproduced with SpriteBuilder 0.6b2, Xcode 5.0.1 and OS X 10.9.

<strong>iPhone</strong>
![ios simulator screen shot 28 oct 2013 16 17 20](https://f.cloud.github.com/assets/1423068/1424833/1e736076-4027-11e3-8777-31e7b6a8f93b.png)

<strong>iPad</strong>
![ios simulator screen shot 28 oct 2013 16 14 17](https://f.cloud.github.com/assets/1423068/1424813/b4f0954c-4026-11e3-92ba-a0e84c629fde.png)

**Comment by vlidholt** [comment]
Hi Ben, it looks like you also checked the scale box. Which will cause the component to be multiplied by the positionScaleFactor when drawn. You may want to have this option checked for the label text, but (usually) not for the complete button.

**Comment by Ben-G** [comment]
Thanks Viktor, this issue clearly was on my end.
