### ISSUE TITLE
Support Packages in SpriteBuilder

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#501]
A _package_ in SpriteBuilder would essentially be an extra resource folder with it's own set of publishing settings. The packages would replace the custom resource paths. A package can either be published to the main App or to a separate (zipped?) file.

There are multiple uses for packages:
- A package can be exported to a zipped file and sent to another user.
- A package can be uploaded to a server and downloaded from the game. This could be extra art resources or levels.
- A package can be downloaded from an asset store.

**Comment by NickyWeber** [comment]
Some thoughts so far...

**How can packages be valid in itself?**
Nodes depend on resources. The idea of projects: Share the same resources across node graphs(CCB files) 

To be portable a package needs/should be able to contain the resources along the ccb files.
1. Essentially resource sharing is an optimization for the bundle 
2. Using one resource instance to apply changes to all usges

The first could be obtained by using hashes to uniquely identify resources and find duplicates -> Publishing Process

Name collisions across packages have to be solved, maybe with namespaces. Again a package can be uniquely identified thus creating a namespace.

**Asorted**
- SpriteBuilder should be able to work on packages directly, without the whole project container around. In the end a package is a project. Project's should be able to contain multiple packages, maybe even work only with packages.
- Packages should be creatable without the XCode template project.
- A project file could be slimmed down and parts moved to packages. A project file could mainly contain the output directory for publishing. Or override local settings of a package.
- zip or other one file(tar) formats may be appropriate for transfer like server -> app or email it to a coworker.

**Comment by vlidholt** [comment]
### Visual Display of Packages

The main app and the different packages should be displayed in the resource manager. If there are no packages (just the main app) the 'package level' will not be displayed (this is how multiple resource directories currently work). The app is represented with a application 16x16 application icon, the packages have package icons.

### Creating / Deleting Packages

Packages can be created by right clicking the resource pane or by selecting _File > New > Package_. The new package appears in the resource browser with the package name selected – the same way as when a folder is created.

Delete packages by either right clicking them or selecting them and hitting the backspace or delete button.

### Referencing Resources

All resources share the same name space. It's possible to use resources across packages. If there are resources with the same names in multiple packages the publisher should produce a warning at publishing time. Which one of the equally named resources that is selected is not defined, but SpriteBuilder shouldn't crash.

### Project Settings

The project settings need to be changed to support packages. It's also a good time to bring the custom Android settings back.
- Remove the resource paths. (They will instead be used to internally handle the resources from packages.)
- Add the Android publishing settings back.

### Package Settings

Each package needs it's own settings. Access the settings pane by either right clicking a package and select _Package Settings..._ or select a package and choose _Package Settings..._ from the File menu (this option should be grayed out unless a package is selected). The package settings pane hase the following options:
- Select between _Publish to main app_ and _Publish to archive_.
- If _Publish to archive_ is selected, the user can choose publishing directories for iOS and Android.

The package settings are stored in a plist file inside the .sbpack folder (see directory structure below).

### Directory Structure

By default the packages are saved inside the .spritebuilder folder. This ensures that the packages are accessible through the sandbox.

```
MyProject.spritebuilder
  -> Source
  -> SpriteBuilder Resources
    -> Resource.png
    -> ...
  -> MyProject.ccbproj
  -> MyProject.xcodeproj
  -> Packages
    -> MyPackage1.sbpack
      -> SpriteBuilder Resources
        -> Resource.png
        -> ...
      sbpackprefs.plist
    -> MyPackage2.sbpack
      -> SpriteBuilder Resources
        -> Resource.png
        -> ...
      sbpackprefs.plist
  -> Published Packages
    -> Published-iOS
      -> MyPackage1.zip
      -> MyPackage2.zip
    -> Published-Android
      -> MyPackage1.zip
      -> MyPackage2.zip
```

### Importing / Exporting

SpriteBuilder automatically scans and adds all .sbpack folders in the Packages directory. A user can export a package by copying it from the Packages folder and import it into another project by pasting it into the Packages folder.

### Publishing

The packages are published using the project's publishing settings, except for the locations. By default they are published to the main app. The second option is to publish them to zip files, the default path is MyProject.spritebuilder/Published Packages/Published-iOS/. The path can be set explicitly.

**Comment by cocojoe** [comment]
Will there be options for content protection? It will be a question asked by some content creators.

Also will it be possible to have extensions to Cocos2D as packages? Perhaps some custom action sequences or effects, shaders etc

**Comment by NickyWeber** [comment]
### General steps to implement the feature for 1.2 release
- [x] 1. Create and add packages, new dialog option and saved as resource libs
  - [x] Create new packages with: File > New > Package... or plus button in left panel at the bottom
  - [x] Remove packages with right click menu in file view
  - [x] Drag and drop .sbpack folders to file view
- [x] 2. Renaming packages
- [x] 3. Packages folder, new packages go here, adding suffix, mixed state regarding 1.
  - [x] Create new packages in packages folder
  - [x] Import dragndrop: .sback packages are copied to packages folder within project folder
- [x] 4. Backwards compatibility: move resource libs to packages folder, hide resource libs in project settings
  - [x] Optional Migration
  - [x] Adjust project templates
- [x] 5. Publishing of Packages
- [ ] 6. Export to by dragging package into finder
- [ ] 7. Export packages as self contained resource: All resources referenced of contained ccbs will be copied as well. One namespace.

### Migration steps

```
Project opens | before normal open project code:
    check for packages/ folder
        YES: is found packages folder a resourcepath?
            YES: rename resourcepath to packages.user, create packages/ folder
            NO: create packages/ folder
        NO: nothing to do
    create packages folder if it does not exist yet
    check all resource paths do |resourcepath|
        is resourcepath in packages/ folder
            NO: check name collision: resourcepath == something within packages/ folder?
                YES: RENAME(logic?) then move on filesystem to packages folder
                NO: move on filesystem to packages folder
            YES: skip
        is resourcepath the special case packages.user
            YES: rename to packages
            NO: skip
        has resourcepath .sbpack suffix?
            NO: add suffix
            YES: skip
    update everything

continue with normal project open code 
```

**Comment by vlidholt** [comment]
Things left to do:
- [x] Project preferences. This is a rough draft for what I think would work (some options have been removed too as they are unused). Feel free to make it look better!

![project-settings](https://cloud.githubusercontent.com/assets/1539812/3682271/1d6a9888-12c8-11e4-80e0-b9dd20d29bc8.png)

Some other things with high priority:
- [x] Change the name of the “packages” folder to “Packages” (as the other folders uses capital letters & it feels a bit more friendly).
- [x] When creating a new package it should work the same way as when creating a new folder (it just creates it and highlights the name so it’s editable).

Lower priority:
- [x] Move publishing folders to cache folder
- [x] Remove or disable the Android settings on non-pro (we are still discussing if it should be hidden or disabled, will get back ASAP on this).
- [ ] Allow referenced packages (not in the project folder) for SB-pro.

**Comment by cocojoe** [comment]
What does audio quality '4' really mean to someone, could we replace these with human friendly labels?

**Comment by NickyWeber** [comment]
@cocojoe The dropdowns should give you a good hint what best and fastest is. I mean I am very open to suggestions on how to translate the range 1-8. 

![bildschirmfoto 2014-07-24 um 13 52 37](https://cloud.githubusercontent.com/assets/5259653/3687539/29214c92-1329-11e4-952a-3ba70f196050.png)

**Comment by cocojoe** [comment]
Do we need a range of 8? I've never really played with this, in terms of checking the actual output settings KHz,Stereo/Mono,bits etc Am curious now, will have a look.

**Comment by vlidholt** [comment]
Looks great so far! :) Some thing that needs to be done:

High prio:
- [x] New projects should be created with the new package structure.
- [x] Default settings for a package should be to only publish to the main project. This is the most common use case and will speed things up a bit.
- [x] Hide Android settings for non-pro in file inspector. (Images, sounds, and sprite sheets are affected).
- [x] Remove publishing option from the file view's context menu (as it's now supported through the project preferences). Let's discuss pros and cons on this one.

**Comment by vlidholt** [comment]
Complete for v 1.2, closing

**Comment by jonnyijapan** [comment]
I'm thinking off putting some assets on a server for dynamic download to app. Did anyone do this? Does it work? Should/can I publish a package to a zip file and upload that? I take uploading a package on its own is incorrect as no publishing process has been done yet.
