### ISSUE TITLE
Input focus on file manager even when editing keyframes

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#52]
Clicking/editing the keyframes doesn't remove input focus from the left side file manager. Reproduce by selecting a file on the left side, then select a couple of keyframes and hit the backspace key. SpriteBuilder will incorrectly ask you if you want to remove the selected file when in fact the keyframes should have been removed instead.

**Comment by jtwigg** [comment]
Fixed.
