### ISSUE TITLE
Zooming in to 100%+ displaces the root node

### ISSUE THREAD

**Issue by NickyWeber** [spritebuilder/SpriteBuilder#523]
**Zoom at 100%**
![bildschirmfoto 2014-05-20 um 12 21 30](https://cloud.githubusercontent.com/assets/5259653/3025673/8e541652-e008-11e3-89d4-b9f94edd71a3.png)

**Zoomed in one step**
![bildschirmfoto 2014-05-20 um 12 21 21](https://cloud.githubusercontent.com/assets/5259653/3025674/8fe00814-e008-11e3-992c-480b998ebc33.png)

**Comment by cocojoe** [comment]
Can you try with latest Cocos2D.

**Comment by NickyWeber** [comment]
I did, doesn't work. I am trying to debug this for a while. You're on it too?

**Comment by cocojoe** [comment]
Well I was, then I'm sure Scott said he tried it with latest Cocos2D and it worked fine. So presumed it was all good.

**Comment by NickyWeber** [comment]
Did a `git bisect` and the regression is introduced with commit 45530fdacea1403ba328c9df29217c1e72f4c2b6 which just updated cocos2d to revision https://github.com/cocos2d/cocos2d-iphone/commit/eaf9f4a8f8c5547b07214b29346763ba8e55522f

Digging there now.

**Comment by NickyWeber** [comment]
@jtwigg, we need your help here, there are many changes in that commit I don't actually fathom. Viktor mentioned that it is working with the most recent version of cocos2d/develop. I am not sure which version SB should point to as of stability, can you update SpriteBuilder's cocos2d submodule, please?

**Comment by jtwigg** [comment]
Ya: I noticed this and slipped it in with some other changes.

https://github.com/spritebuilder/SpriteBuilder/commit/80124b8c3067303be0d67214da158346ffee626b

Its been pushed.
