### ISSUE TITLE
Toggling between modes on pivot joint doesn't work

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#548]
It currently doesn't work to toggle between the different visual editing options on pivot joint. It gets stuck on two modes. Also, possibly related, sometimes the handles doesn't match the current editing mode.

**Comment by vlidholt** [comment]
![screen shot 2014-05-28 at 4 11 17 pm](https://cloud.githubusercontent.com/assets/1539812/3112375/4b21f73c-e6c0-11e3-9256-bd500f13dddd.png)

**Comment by jtwigg** [comment]
Fixed.

**Comment by jtwigg** [comment]
https://github.com/spritebuilder/SpriteBuilder/commit/48f4c737b39f966c66b668ec4c19e98136ddcf29
