### ISSUE TITLE
Update the message when joints cannot be edited

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#549]
Update the message to look like the following:

![screen shot 2014-05-28 at 4 34 03 pm](https://cloud.githubusercontent.com/assets/1539812/3112436/9795716a-e6c1-11e3-85cf-5a4ea45e2fb7.png)

**Comment by jtwigg** [comment]
Fixed: https://github.com/jtwigg/SpriteBuilder/commit/e230bde8f018ee3c31a2ec4ea1e407461ad33be5
