### ISSUE TITLE
Gray out checkbox in 'Edit timeline'

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#550]
The auto play option should be grayed out if there is a single timeline in a file (it shouldn't be possible to unclick this option).

Also, when deleting the auto play timeline, the top timeline should be marked as auto play. (Currently it's possible to not have a auto play timeline by removing it, which is not working with physics joints and other things.)

**Comment by NickyWeber** [comment]
Functionality alreay present: The dialog will validate the changes and prompt the user with an error message.
