### ISSUE TITLE
Possible memory leak in publisher

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#56]
_Needs verification_

Possible a large memory leak in the publisher causing SpriteBuilder to take several gigs of memory when publishing.

It's possible this is already fixed.

**Comment by jtwigg** [comment]
Memory Results on publishing SpriteBuilderFiles.ccbproj
Prior to 1st Publish:  104meg
After 1st Publish: 122megs
After 2nd Publish: 130Megs
After about 10 clean and publishs: 155megs

Not perfect but much better.
