### ISSUE TITLE
Crash in CCBXCocos2diPhoneWriter (treats callback selector as sound effect)

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#560]
I just pulled the latest dev branch (commit ..af456dc). I cleaned my SB project (this one: https://github.com/learnCocos2D/sbcc) and just published, that provokes the crash in:

```
- (void) writeChannelKeyframe:(NSDictionary*) kf
...
    else if (type == kCCBKeyframeTypeSoundEffects)
    {
        NSString* sound = [value objectAtIndex:0];
        float pitch = [[value objectAtIndex:1] floatValue];
        float pan = [[value objectAtIndex:2] floatValue];
```

It crashes on the "pan" line because `value` contains only two items.

I can see from the "sound" string that it is actually the name of a selector (playerDidExitLevel) that I have in the timeline.

I believe the crash is related to this commit: fa48655 (fixup CCControls and keyframe callbacks: @“” string selectors result in type=0 targets.)

**Comment by LearnCocos2D** [comment]
I rolled back to d574decb4a2fd42a8be9cf8d4dbbcb0578127961 (commit before https://github.com/spritebuilder/SpriteBuilder/commit/fa48655) and the crash is gone.

**Comment by jtwigg** [comment]
Fixed: https://github.com/spritebuilder/SpriteBuilder/pull/606
Very stupid of me. Apologies.

**Comment by LearnCocos2D** [comment]
Yup, this is fixed. Thanks!
