### ISSUE TITLE
Image preview of the the layer or sprite file in resource view is displayed vertically flipped

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#590]
1. Launch application.
2. Create a new layer file "Level1.ccb".
3. Drag and drop an image on it (e.g. Background.png).
4. Save changes.
5. Click on the layer file in the resource view.
   
   -- Result: The view of the layer is displayed as vertically flipped when user views it in resource viewer.
    This happened 3/3 times.

Found on Mac OS X 10.9.1 on SpriteBuilder-1.1.0-beta.2.zip.

![untitled2](https://cloud.githubusercontent.com/assets/7450007/3165213/d8297b92-eb51-11e3-9141-847266183780.png)

**Comment by cocojoe** [comment]
This is now fixed in latest.
