### ISSUE TITLE
Property fields and data validation

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#594]
Issue #591 has flagged up for me how annoying invalid data is in the property fields. If invalid you get a popup that allows you to discard value or press OK.  Ideally it would be nice to just ignore invalid character sets on input as most should just be numeric anyway. 

If not I would drop the popup (it's annoying) and just reset an invalid field to 0.

**Comment by NickyWeber** [comment]
Could make input's text color red, if there is space left show a contextual message about what's wrong or show the range of valid characters. There are many ways. Modal dialogs are pain.

**Comment by cocojoe** [comment]
Yeah I think turning red on bad input would be nice.
