### ISSUE TITLE
User is unable to select a keyframe when user paste it from another scene.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#596]
1. Launch application.
2. Open a scene.
3. Add a image.
4. Create a keyframe and animation against that image.
5. Create new scene.
6. Drag the same image added in previous scene.
7. Copy Paste keyframes from old scene into new scene.
   
   -- Result: User is unable to select the keyframes and no "pink lines are displayed.
     This happened 3/3 times.

Found on Mac OS X 10.9.1 on SpriteBuilder-1.1.0-beta.2.zip.

![screen shot 2014-06-04 at 7 36 20 am](https://cloud.githubusercontent.com/assets/7450007/3175350/8da67bc0-ebfa-11e3-918e-20067f3ab9d5.png)

**Comment by sana20** [comment]
This issue is re-occurring.

Mac OS X: 10.10.1
XCode: 6.1.
SBBuild: SB 1.4.8-rc.0
SBAndroid Build: SBAndroidPluginStarter-9ac08c84

**Comment by Shahidwerplay** [comment]
This issue fixed
SpriteBuilder-1.4.9-rc.0

Mac OS X: 10.10.
XCode: 6.1.

**Comment by sana20** [comment]
This issue fixed.

Latest Develop branch SB Version (2.0)
Mac OS X: 10.10.1.
XCode: 6.1.
