### ISSUE TITLE
Sprite builder Resources are not removable from the file view.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#597]
1. Launch application.
2. Add two Sprite builder Resources in resource path.
3. Ctrl+ S.
4. Publish.
5. Delete any one Sprite builder Resource.
   
   -- Result: Sprite builder Resources are not removable from the file view. Delete button doesn't work. In one resource delete option is tappable but doesn't work, in the other one it is not tappable.

This happens 3/3 times.

Video is attached here:
https://drive.google.com/a/werplay.com/file/d/0B2b3lCCE3OwtVHU2VUtqa09ic3c/edit?usp=sharing

Build version used: SpriteBuilder-1.1.0-beta.2

Used:
MacBook Pro
Version: OS X 10.9.2(13C64).
Processor: 2.66 GHz Intel Core i7

**Comment by jtwigg** [comment]
I removed the Delete modal for those directories.

https://github.com/jtwigg/SpriteBuilder/commit/8d897cf271885e10eaa2755b64a69d7642bd435e
