### ISSUE TITLE
Application crashes when user tries make Sprite builder Resources to "make smart sprite sheet".

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#599]
1. Launch application.
2. Tap ctrl+ ;
3. Add Sprite builder Resources in resource path.
4. In the file view select Sprite builder Resources.
5. Make smart sprite sheet.

-- Result: Application crashes when user tries make Sprite builder Resources to "make smart sprite sheet".

This happens 3/3 times.

Video is attached here:
https://drive.google.com/file/d/0B2b3lCCE3OwteENhOWcxQnJNLWM/edit?usp=sharing

Build version used: SpriteBuilder-1.1.0-beta.2

Used:
MacBook Pro
Version: OS X 10.9.2(13C64).
Processor: 2.66 GHz Intel Core i7

**Comment by jtwigg** [comment]
Fixed with:
https://github.com/spritebuilder/SpriteBuilder/pull/608

Nice Catch!
