### ISSUE TITLE
Add more right click options in project/file view

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#6]
When right clicking in the left hand file view (first tab) it should be possible to create a new interface file and to delete files.

**Comment by jtwigg** [comment]
Working
1) Create Interface.
2) Delete Interface file (Confirmation dialog pops up. Errors bubble up)
3) Create Folder

Possible extended behvarior:
1) Delete folder. Q1: What do we do with all the sub files? 
2) When create an interface/folder INSIDE a folder, is should APPEAR in the folder. Right now it gets created at the bottom of the list.

**Comment by vlidholt** [comment]
The behavior that is implemented is working and correct (I think). What I want to add is an addition to the context menu that pops up when right clicking the file view. To remove files it should invoke the already implemented method for removing files or directories (same as if you select the row and press the back button).

What would be super useful is if the files could be created (when right clicking) in the correct directory. There are methods in ResourseManager and ResourceManagerUtil that can convert a relative path to a full path. It's important to use those functions as the project can potentially contain several different resource directories.
