### ISSUE TITLE
Sound does not change when user increases gain value from settings

### ISSUE THREAD

**Issue by khizerjavaid** [spritebuilder/SpriteBuilder#600]
1. Launch application.
2. Add an element on stage and put animation to it.
3. Drag a wav sound file to resources.
4. Drag the sound file over newly added element.
5. Increase gain value of sound.
6. Tap Play.
   --Result : Sound does not change.
   This happened 3/3 times.

Found on SpriteBuilder-1.1.0-beta.2 on Mac OS 10.9

**Comment by jtwigg** [comment]
Can you clarify if you tried to set it greater than 1 and it didn't work?

If so: 
Fixed : https://github.com/spritebuilder/SpriteBuilder/pull/607
Gain is limited to between [0. 1] and if you exceed this, a warning is displayed.
