### ISSUE TITLE
Enhancement: menu command to "Open Xcode Project"

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#605]
As a new user you create a new cocos2d project in spritebuilder, publish it, and then ... what? A new user may not even be aware that Spritebuilder creates Xcode projects and wouldn't really know what to do at this point.

There's a connection missing here and that's the ability to open the associated Xcode project from within Spritebuilder. Perhaps this could be a two-fold Publish and Publish & Open in Xcode command. 

This request is sort of a "Play" version light, a lot easier to implement than this request (https://github.com/spritebuilder/SpriteBuilder/issues/211) but still very welcome for new users and starting new projects in general.

**Comment by cocojoe** [comment]
#211 Would be nice however just the association to be able to 'Open Xcode' would be very handy and a logical next step.

**Comment by NickyWeber** [comment]
I added something experimental a few weeks ago in https://github.com/NickyWeber/SpriteBuilder/tree/feature/run_in_xcode which will **open XCode with the project and run it**. Mainly helped me to debug something faster.

It uses AppleScript the generic commands which is a bit brittle with the hard coded menu selection, however XCode AppleScript support utterly broken. And I assume Apple is not going to change the menu layout every week.

**Comment by cocojoe** [comment]
Even something as simple as 'open mysbproject.xcodeproj' would help.

**Comment by NickyWeber** [comment]
First time users should be directed to a web site showing first steps and general description of the working environment. I don't know if something like that already exists for this purpose.

**Comment by christinakelly** [comment]
The menu option is a great idea - I think a button on the top bar next to the Publish button would be a great addition as well, so that it's really obvious on the UI for people who don't poke around in menus very often.  Thoughts?

**Comment by NickyWeber** [comment]
The toolbar in general is under-utilized. This should be much more flexible: Customizations.

**Comment by LearnCocos2D** [comment]
"open xcode project" menu command exists, so this can be closed?
