### ISSUE TITLE
Timeline animations get out of sync

### ISSUE THREAD

**Issue by misterHallodri** [spritebuilder/SpriteBuilder#609]
Please see linked example project:
https://www.dropbox.com/sh/al2cnjkiag5tot1/AAAOdFFkfMXh89KOqNMf-wPua

In SpriteBuilder the three animations are played as expected.
Running the code, there are pauses between the animations.

**Comment by cocojoe** [comment]
Had a quick look, a fix is to just insert a keyframe at position 0 for the nodes that currently do not start at 0.  Will look into the actual code shortly.

Thanks for spotting.

**Comment by misterHallodri** [comment]
Nice! Thanks for the quick response!

**Comment by cocojoe** [comment]
I had a look at code and general the logical expectation is that animations
start at zero timeline/keyframe. Not sure it was worth the trouble to work
around this.
The simplest way to fix this would be to ensure a zero time keyframe is
always created in a timeline (when the user creates their first keyframe).
@vlidholt https://github.com/vlidholt That seem acceptable?

On 6 June 2014 11:01, Svend Dutz notifications@github.com wrote:

> Nice! Thanks for the quick response!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spritebuilder/SpriteBuilder/issues/609#issuecomment-45321119
> .

## 

Martin

**Comment by vlidholt** [comment]
This is a bug introduced with the animation refactoring, so that where it should be fixed. Making hacks to fix stuff is never a good idea. This needs to be fixed in CCBReader/CCAnimationHandler.

**Comment by vlidholt** [comment]
This also needs to be tested with different timelines etc.

**Comment by jtwigg** [comment]
This is resolved by : https://github.com/jtwigg/cocos2d-iphone/commit/e2620774dfc0b079ebca1db153c04b821372380f

Waiting for pull request to be merged...

**Comment by jtwigg** [comment]
Further fixes with https://github.com/cocos2d/cocos2d-iphone/pull/836
Retested this project and its working well.

Closing.
