### ISSUE TITLE
The "Zoom when highlighted" option for CCButton has bug.

### ISSUE THREAD

**Issue by Horse888** [spritebuilder/SpriteBuilder#610]
The "Zoom when highlighted" option for CCButton is super handy. But seems button size will stay at the "zoom out" size if I tap (and release) very quickly.

**Comment by jtwigg** [comment]
Is this a bug in SpriteBuilder itself or in the cocos2d runtime, and it only occurs in the iphone simulator or on a device?

**Comment by jtwigg** [comment]
Runtime. Verifified. I'm moving this to cocos2d issues and closing this.
Cheers.

https://github.com/cocos2d/cocos2d-iphone/issues/822
