### ISSUE TITLE
v1.1 rc SpriteKit can only handle ccbi v8, but SpriteBuilder will publish v10

### ISSUE THREAD

**Issue by TheMadBug** [spritebuilder/SpriteBuilder#612]
To reproduce:
In v1.1-rc create a new SpriteKit SpriteBuilder project.
Publish from SpriteBuilder (if you don't publish it works, presumably with a pre-created v8 ccbi created in the new project)
Try to run the app from within XCode, you will be told
"CCBReader: Incompatible ccbi file version (file: 10 reader: 8)"

As of 10 June commit 57dd979 in the develop branch this looks like it's still a problem, CCBReader_Private.h in the SB+SpriteKit.xcode project has "#define kCCBVersion 8" but I have not built and tested it.

FYI, as you'd expect just changing that constant from 8 to 10 breaks as the code is written to parse version 8.

**Comment by NickyWeber** [comment]
CCBReader is not backwards compatible.
You need to update your cocos2d version in your project and then republish everything.

**Comment by TheMadBug** [comment]
Hi Nicky, thanks for the response but I'm not referring to updating an existing cocos2d SpriteBuilder project to 1.1rc.
I'm referring to using 1.1rc to create a from scratch SpriteKit SpriteBuilder project. e.g. "File -> New -> SpriteKit Project...", Publish. Then open the new XCode project and click Run. You then get the error about the ccbi file / reader mismatch.

The latest version of SB+SpriteKit.xcode/CCBReader can still only read version 8 ccbis but SpriteBuilder 1.1rc publishes version 10, so it looks like the SpriteKit.xcode/CCBReader has not been updated to be able to parse 10 yet. I imagine that the cocos2d/CCBReader works fine.

Hope that clears it up. Cheers.

**Comment by NickyWeber** [comment]
Heya @LearnCocos2D, can you help us with this? Thanks alot.

**Comment by LearnCocos2D** [comment]
I'm on it.

**Comment by LearnCocos2D** [comment]
Fixed when this pull request is merged:
 https://github.com/spritebuilder/SpriteBuilder/pull/618

Fixed in:
https://github.com/apportable/SpriteBuilder-SK/commit/2e1db3200ae0458a4fe27cba91683533a2e67f87

You can give it a try by pulling this repo https://github.com/apportable/SpriteBuilder-SK and update the corresponding files in the Spritebuilder repo if you can't wait for the pull request to be merged.

**Comment by NickyWeber** [comment]
Thanks alot!

**Comment by TheMadBug** [comment]
I can confirm that the branch fixes my issue. Thanks Steffen.

Off topic : Sorry to keep bugging you but there's one more semi-critical SpriteBuilder/SpriteKit implementation bug that I've came across, I've raised it here https://github.com/spritebuilder/SpriteBuilder/issues/622
