### ISSUE TITLE
Argument must be non-nil SIGABRT (1.1)

### ISSUE THREAD

**Issue by bchessin** [spritebuilder/SpriteBuilder#625]
I know this has probably been discussed before on here but I am having an issue with the latest version of SpriteBuilder (1.1) and Cocos2D 3.1.

Ever since I upgraded SpriteBuilder, I told it to upgrade my project as well to 3.1 and it said it worked. However when I upgraded there were a few errors referencing new 3.1 methods in CCBReader relating to CCPhysicsJoint so what I did was just download the latest Cocos2D 3.1 from https://github.com/cocos2d/cocos2d-iphone/tree/v3.1 and then I just replaced the entire "cocos2d" and "cocos2d-ui" folders with the new ones from that repo.

Now I added my "Published-iOS" folder to my project (since it was already created and I had to add SpriteBuilder to it) as a folder reference. Now, every time I try to load a file with load: or loadAsScene: it crashes with this message:
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Argument must be non-nil'

Is there any reason for this? Am I doing something wrong? In the past, it worked but now it suddenly doesn't work. If I add these file as a group and "copy" them to my project, it works though. I feel that is not the correct way to implement it though. Any ideas/help here?

Thanks!

**Comment by NickyWeber** [comment]
Hey @Objective-Zero,
I got a question first:

> If I add these file as a group and "copy" them to my project, it works though. I feel that is not the correct way to implement it though. Any ideas/help here?

These files are the cocos2d library files or your assets generated(publish) by Sprite Builder? By "copy" do you mean a blue(referenced) folder?

Cheers

**Comment by bchessin** [comment]
Yes, these files I'm talking about are the assets published by SpriteBuilder. When I mean "copy", I select the box saying "copy items if needed" and add the Published-iOS folder as a group to my project. Is this the correct way to do it? I guess what I am trying to clarify here (and perhaps might fix my issue) is how do I properly add ALL the published assets to a project ALREADY created (not made my SpriteBuilder)?

**Comment by NickyWeber** [comment]
The spritebuilder template projects contains that blue(referenced) folder, which is also in the copy bundle phase. This is important: just the folder is in the copy phase but the rest get just copied and the folder structure is maintained as is. So it is easy to add or remove new stuff without touching the copy bundle phase. One issue that comes along with this is accessing files. You have to search for files if they reside in deeper folders, as folder structure is kept.

So first step could be to check if your publish folder is in the copy bundle phase.
Next step: find out if the to be loaded file is in a folder within the publish folder.

**Comment by bchessin** [comment]
After looking at similar issues with loading files/CCBs in SpriteBuilder, it turns out it was a real simple fix. All you had to do was something like this:
CCNode *node = [CCBReader load:@"Published-iOS/CCBs/GUI/MainScene.ccbi" owner:mainScene];
Anyway, it's all fixed now!

**Comment by NickyWeber** [comment]
Sweet!
