### ISSUE TITLE
CCAnimationManager leaks and causes crashes if "cleanup" is not called

### ISSUE THREAD

**Issue by Ben-G** [spritebuilder/SpriteBuilder#638]
## Following test case can reproduce problem:
- Use CCBReader to load a CCB file
- **Don't** add the node to any parent node so that it gets released
## Result:
- Node will get deallocated, setting the reference to its `animationManager` to `nil`
- The `CCAnimationManager` will not be freed (because it is retained by the scheduler?)
- After 10 seconds the leaked `CCAnimationManager` will attempt to call a callback on the already released node (default timeline sequence completed) which will lead to a crash
## Workardound:

Calling the `CCAnimationManager` `cleanup` method in the `dealloc` method of `CCNode` fixes this problem, because after calling `cleanup` `CCAnimationManager` is no longer retained:

```
- (void) dealloc
{
  CCLOGINFO( @"cocos2d: deallocing %@", self);

  // children
    for (CCNode* child in _children)
    child.parent = nil;

  [self.animationManager performSelector:@selector(cleanup)];
}
```

This however isn't a solution for the actual problem.

I didn't look to closely into which object retains the `CCAnimationManager` because I'm not very familiar with that part of the codebase. If anyhow possible that responsible object should only hold a weak reference to the `CCAnimationManager` so that releasing the node also releases the animation manager.

Has anyone looked into this by any chance? Maybe somehow related to #402

**Comment by cocojoe** [comment]
More likely related to [cocos2d/#785](https://github.com/cocos2d/cocos2d-iphone/issues/785)

**Comment by cocojoe** [comment]
Ben would you  mind trying out the pull request above.  Thanks

**Comment by Ben-G** [comment]
@cocojoe Unfortunately this does not fix the issue. The node is hooked up with the `CCAnimationManager` when the `CCBReader` loads the file. The `CCAnimationManager` then creates an `CCActionSequence` with a duration of 10 seconds (representing the timeline). After ten seconds these lines in `CCActionSequence` cause the crash, while trying to call the `CCActionCallFunc` at the end of the timeline:

```
    // New action. Start it.
if( found != _last )
    [_actions[found] startWithTarget:_target];
```

The `CCActionSequence` is still storing a reference to the target (`unsafe__unretained`), that has already been released - and that causes the crash.

To fix the root cause, I assume the way how the `CCAnimationManager` is set up and retained would have to be changed. But as a side note, why are we still using `unsafe__unretained` instead of `weak`? `weak` is already used in some places in Cocos2D, so it can't be for backwards compatibility. Is it just legacy code? 

In the case of this issue turning `target` to be stored `weak` will fix the issue. On the other hand using `weak` will make it harder to spot such potential code design issues, so one could argue that using `unsafe__unretained` should be preferred. Has `weak` been considered for the `CCAction` `target`?

**Comment by cocojoe** [comment]
Did you also update CCActionInstant.h as per pull ? As this sets CCActionCallFun target to weak...

**Comment by Ben-G** [comment]
@cocojoe Yes, must have been something on my end. Double checked I imported the correct Cocos2D version and now the issue is resolved. Thanks!
