### ISSUE TITLE
Drag and drop into assets panel no longer works

### ISSUE THREAD

**Issue by kevinmkarol** [spritebuilder/SpriteBuilder#639]
But when I add assets to the SpriteBuilder Resources folder directly they appear in the panel

**Comment by NickyWeber** [comment]
Which version?
Will have a look.

**Comment by NickyWeber** [comment]
Cannot confirm this on 1.1 branch nor develop.
Can you give us some more details on how to reproduce this as well as the version used?

**Comment by kevinmkarol** [comment]
Built using the latest developer branch.  Also, it appears to work for image assets, but not for mp3s - I haven't tested with other audio formats.

**Comment by NickyWeber** [comment]
Ok, I am sorry to say, but SpriteBuilder only works with wave files. Wave files will be compressed to a target format depending on the platform(iOS only at the moment).
