### ISSUE TITLE
Improved transformations in editor

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#64]
Rotation – drag outside the transform points (current behavior requires user to hold down option key, which is not optimal)
Skew – drag along an edge

This should also have cursor indications. See for instance Photoshop transformations for reference.

**Comment by vlidholt** [comment]
Needs to be tested so it works correctly with all the different kinds of positioning types also.

**Comment by jtwigg** [comment]
- When setting both skew values and then resizing it flips out when setting a negative scale
- There need to be a cursor for the scale (when hovering a corner)
- Rotation works well with absolute positions, but acts up slightly if % is used (this is likely an old bug)
- Is it tested with different cases, such as having a parent node with negative scale etc?

**Comment by jtwigg** [comment]
It currently doesn't work with nodes that have a zero size (I say we can skip skew for those, but scale & rotation need to work).

**Comment by vlidholt** [comment]
It's pretty close now, but found some things.

When hovering the corners, the mouse pointer changes to the scale cursor, but the cursor doesn't always mach what happens when clicking and dragging. Sometimes it will move the object instead and sometimes it will select another object.

Transformations are not perfect with other types than absolute positions. Maybe there are some cases when positionInPoints and contentSizeInPoints are not used? For instance, in the default project rotating the 'Welcome to SpriteBuilder' text is a bit slow (unless you change the position type to points) and skewing the background gradient is super sensitive (it works correctly when changing the content size type to points though).

**Comment by jtwigg** [comment]
-When a parent has no content size, we need to scale and rotate and anchor
.

**Comment by jtwigg** [comment]
Should be done.

**Comment by vlidholt** [comment]
Added new images for the cursors. Also added an extra one. _select-move.png_. My thinking is that it would be nice if the mouse could turn into this when the user is about to move an object around.
