### ISSUE TITLE
Custom fonts don't work for TTF labels

### ISSUE THREAD

**Issue by jonnyijapan** [spritebuilder/SpriteBuilder#641]
I added a font into the SB project. Then I select the font in the dropdown list for a CCLabelTTF. However the font does not display on device.
Workaround is to set the font in code, like label.fontName = @"mycustomfont.ttf" etc.

**Comment by sana20** [comment]
This issue is fixed.

Mac OS X: 10.10.1
XCode: 6.1.
SB Version: 1.4.7.
