### ISSUE TITLE
Body's mass and moment must be positive to simulate. 

### ISSUE THREAD

**Issue by Trapper68** [spritebuilder/SpriteBuilder#668]
Hi, 
I had a working app which now fails on with 'Aborting due to Chipmunk error: Body's mass and moment must be positive to simulate' . Im guessing something to do with cocos2d updated . I've got latest Spritebuilder, updated cocos2d within the project and 'changed & saved' all CCB files . dont know where to turn to next .

**Comment by jpiabrantes** [comment]
I had the same problem. This error was being caused by a physical body that had polygon shape and a corner radius of 0 (I don't know why polygon shapes should have a radius), after I changed the radius to a positive value the body now had mass and the error was gone.

**Comment by slembcke** [comment]
It's a bug with upgrading 1.0 projects. https://github.com/spritebuilder/SpriteBuilder/issues/634 The workaround is to open up your physics object, make a throwaway change (like changing the corner radius, even to the same value) and resave.

The corner radius can be used to smooth out the corners of a polygon. Like a rounded rectangle, but more generic. It prevents sharp polygon corners from snagging on each other and also speeds up the collision detection slightly.
