### ISSUE TITLE
kCCBMaxTrackedDirectories is not big enough

### ISSUE THREAD

**Issue by kirillzuev** [spritebuilder/SpriteBuilder#671]
Right now `kCCBMaxTrackedDirectories` is defined as 50, and it's not enough for my project. I have to rebuild the tool from source code and send the binary to my teammates, which is inconvenient. Is there's a reason to have `kCCBMaxTrackedDirectories` set to 50 and not to, say, 1000?

**Comment by vlidholt** [comment]
The reason is that there is (possibly fixed) a but in OS X where tracking to many directories caused SB to crash. Will investigate if this is still an issue or if it has been fixed.

**Comment by ghost** [comment]
For one of our projects we have kCCBMaxTrackedDirectories set to 500 with about 450 actual directories in the project. Haven't noticed any crashing on 2011 Mac Pros.

**Comment by NickyWeber** [comment]
@vlidholt we could put those kind of values into a config file, what do you think?

**Comment by vlidholt** [comment]
Let's up this to 500.
