### ISSUE TITLE
SB publishing cache seems broken, performs full re-publish every time

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#672]
It seems SpriteBuilder currently performs a full re-publish every time. I just changed the visible property of a node a few times and it generates all the spritesheets anew every time. This leads me to believe that the caching mechanism is somehow broken. 

I originally noticed this when building from Xcode took a very long time due to the osascript telling SpriteBuilder to publish.

**Comment by LearnCocos2D** [comment]
I'm on this commit: ad184cb789bdf4ac917c40bf16c79f92c2bf9942
SB is launched from its Xcode project if that makes any difference.

**Comment by LearnCocos2D** [comment]
I rolled back to a 3 weeks old commit: 4304a08d75ddd8f0b31eba4744aecc91f1223611
It's still re-publishing all spritesheets every time I publish. I'm beginning to suspect this may not be a code issue but something machine- or project-specific.

**Comment by NickyWeber** [comment]
Are you publishing with release or develop?

**Comment by LearnCocos2D** [comment]
SpriteBuilder is built with release config but if you refer to SpriteBuilder's own Debug/Release dropdown in the toolbar I haven't touched that, so it should have been Debug publishing every time.

I also checked whether PVR vs PNG setting for sprite sheets made any difference, but no... it didn't.

**Comment by LearnCocos2D** [comment]
Okay, I synched back to the latest commit and since I've changed the sprite sheets to PNG I now see a optipng process at 100% CPU usage (that's one core of 4) and SB stuck at "optimizing xxx.png" for a veeeeeery long time (several minutes).

**Comment by NickyWeber** [comment]
Release publishing adds the optipng step to all(in Published-XXX folder) pngs. It will always to a clean publish, so it will always take longer than debug. optipng is slow, even for a handful of files.

**Comment by LearnCocos2D** [comment]
Even in "Develop" mode SB does a full re-publish every time.

**Comment by NickyWeber** [comment]
Should be fixed now.

**Comment by LearnCocos2D** [comment]
it is, muchmuchmuch faster!

**Comment by NickyWeber** [comment]
Sweet!
