### ISSUE TITLE
Stopping node actions doesn't stop animation

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#677]
Mentioned on forums, as CCAnimationManager schedule is separate from the node it will not get paused/stopped on node stopAllActions.  Makes sense to me to check of animationManager is present and pause in these methods.

**Comment by vlidholt** [comment]
Not exactly a bug, but we should probably change this behavior.

**Comment by cocojoe** [comment]
yeah agreed, didn't think I flagged it as a bug.

**Comment by vlidholt** [comment]
Quite alright :)

**Comment by NickyWeber** [comment]
Shame on me with that red tag :)
