### ISSUE TITLE
Sound Effects on Timeline preview don't stop on stop button

### ISSUE THREAD

**Issue by kevinmkarol** [spritebuilder/SpriteBuilder#694]
To stop a sound file that is started using the timeline preview you need to fully exit out of SpriteBuilder, which can be annoying for longer music files.

@jtwigg

**Comment by Shahidwerplay** [comment]
This issue is still reoccurring.
Sprite Builder latest develop branch SB Version (2.0)
Mac OS X: 10.10.0
XCode 6.1
