### ISSUE TITLE
UI handle scaling of a node behaves oddly when anchor is not 0.5,0.5

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#696]
Set anchor to say 0,0, move mouse close to bottom right of the node to initiate a handle scale.  Will not behave as expected.

**Comment by NickyWeber** [comment]
You mean scaling by dragging the handles?

**Comment by cocojoe** [comment]
Yeah

**Comment by NickyWeber** [comment]
Noticed that as well, very annoying.

**Comment by sana20** [comment]
This issue is re-occurring.

Mac OS X: 10.10.1
XCode: 6.1.
Latest Develop branch SB Version (2.0)
SB Revision: 02eedd1
