### ISSUE TITLE
Small images in sprite sheets causes crashes 

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#7]
When resizing images smaller than 3 pixels wide (sprite sheets only?) SpriteBuilder crashes.

**Comment by jtwigg** [comment]
The problem occurs when the image is scaled down to .25 of 3 pixel == 0.

  int wDst = wSrc \* scaleFactor; << where wSrc = 3, scaleFactor = .25
    int hDst = hSrc \* scaleFactor;

This results in the images failing to create, resulting in the CFRelease(0x0) which throws exception.

Possible Solutions:

BEST 
1) minimum size of width and height could be floored at 1. This would solve this problem but is mildly inconsistent as it results in round-up behavior in contrast to the normal round down behavior.

WORST
2) We could fail gracefully, and the image wouldn't appear in the spritesheet. Code would need to be fixed up elsewhere. Don't like this solution.

**Comment by vlidholt** [comment]
I think 1) would be the best solution here.
