### ISSUE TITLE
Exported PNG images much larger than original

### ISSUE THREAD

**Issue by iMobCoding** [spritebuilder/SpriteBuilder#702]
As title says. For example, image exported from photoshop is 7mb but after it goes through sprite builder publisher it has over 8mb. Some other examples are even more drastic. So can this PNG exporter be improved?

**Comment by NickyWeber** [comment]
Try to make a release publish and see if the files are still that big. SB runs optipng on every png file.

**Comment by iMobCoding** [comment]
Wow, you were right. Sizes are now almost identical to photoshop export. In some cases even smaller. Great... Btw, besides that, what other differences are between RELEASE/DEVELOP?

**Comment by NickyWeber** [comment]
Good to hear that, there are NO differences. 

I think we need to communicate these kind of changes much better. Maybe some tooltips as well.
