### ISSUE TITLE
HTML5 and javascript bindings 

### ISSUE THREAD

**Issue by justgook** [spritebuilder/SpriteBuilder#71]
in cocosBuilder was nice possibility to use js-bindings and cocosPlayer to debug cocos application in real-time.
as I'm javascript developer (by profession), i miss this feature in SpriteBuilder, it would be nice to have choose between what, an how i wont program, and also nice possibility to compile separate JS version of project, for example if i wont "post" my game in some social network (Facebook, or something else)

**Comment by vlidholt** [comment]
Currently there are no plans of supporting JavaScript in SpriteBuilder, sorry.
