### ISSUE TITLE
Smart Sprite Sheet Generation Rotation/Trim

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#714]
Issue with image jitter caused by rotation and/or trim combination.  

More information: 
http://forum.spritebuilder.com/t/jitter-in-animation-when-using-smart-sprite-sheet/882/21

Related:
https://github.com/spritebuilder/SpriteBuilder/issues/703

**Comment by cocojoe** [comment]
Have looked into this and don't believe there is a problem with rotation.  It is most likely the trim, this seems to work just fine for the most part however some users do have projects that they have already trimmed pixel perfect and if that image has any transparent lines adjacent to an edge it will get an extra trim, which modifies the rect size and hence jitter.

I did a quick hack to disable trim in sprite sheet creation for a couple of users to feedback on first.

https://www.dropbox.com/s/r4iy2xjie7bs5v0/SpriteBuilderNoTrim.zip

**Comment by NickyWeber** [comment]
Should be easy to turn this into a project setting if needed.

**Comment by cocojoe** [comment]
Linking in cocos2d/cocos2d-iphone#893 as some relevant discussion.

**Comment by vlidholt** [comment]
This is fixed now: https://github.com/spritebuilder/SpriteBuilder/commit/016679601e02c1d164c7cb5dad7c4cb9c8d2ca0a
