### ISSUE TITLE
Provide easier way to open Xcode project from SB

### ISSUE THREAD

**Issue by christinakelly** [spritebuilder/SpriteBuilder#717]
This is a feature request.

It would be great if there were an easier way to directly open a SpriteBuilder project's Xcode project in Xcode from the SB UI.  Right now you have to find the project folder in Finder and then double-click the .xcodeproj file, which is inconvenient for a frequently executed action.

**Comment by NickyWeber** [comment]
Possible duplicate of https://github.com/spritebuilder/SpriteBuilder/issues/605
