### ISSUE TITLE
Animation issue with instant easing and some sequence property types

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#723]
Issue came up with a retro style ccb animation, no tweening involved.  This works as expected for spriteFrames (typical use).  However this behaviour is not supported in most other properties  such as position and rotation.  The process of wrapping these as 'instant' means they get executed immediately and will be out if sync relative to spriteFrame keyframe sequence.

**Comment by cocojoe** [comment]
I have fixed this, just want to run some more tests before doing a pull.

**Comment by NoorFatima** [comment]
This issue is fixed.
Device: Mac OS X 10.9.5
SB Version: 1.4.7
