### ISSUE TITLE
Label TTF outline is drawn upside down

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#726]
A picture says it best:

![screen shot 2014-07-29 at 11 23 31](https://cloud.githubusercontent.com/assets/214599/3732868/098abc4c-1702-11e4-8b5a-e7eaca00ec70.png)

Currently on the develop head revision as of today. I also noticed this last week. I can't say when exactly it broke, it could have been weeks ago and gone unnoticed (or there's already a report on this, though I couldn't find any).

**Comment by NickyWeber** [comment]
My gut feeling tells me it's due to a cocos2d change. Could do a git bisect to find out.

**Comment by cocojoe** [comment]
Would imagine so, textures have been flipped a few times in develop.

**Comment by LearnCocos2D** [comment]
This may be related, bottom of texts cut off depending on font: https://github.com/spritebuilder/SpriteBuilder/issues/729

**Comment by vlidholt** [comment]
This works for me, anyone still having this issue? If so, please reopen.
