### ISSUE TITLE
Label TTF text is cut off at the bottom (with small font sizes)

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#729]
Following Label TTF is drawn with increasing point size (12, 16, 20, 24) and up to font size 20 the bottom is more or less noticably cut off:

![screen shot 2014-07-29 at 16 56 22](https://cloud.githubusercontent.com/assets/214599/3736753/9ad382d2-1730-11e4-8e22-e5ed39a9c09b.png)

The effect does not seem to appear with the default font Helvetica, and depending on the font the issue is more or less noticable in general.

Same shot again scaled up by factor 4:

![screen shot 2014-07-29 at 16 56 22](https://cloud.githubusercontent.com/assets/214599/3736802/080fbad2-1731-11e4-849d-1aae21ba4266.png)

**Comment by vlidholt** [comment]
Should have been fixed (rolled back CCLabelTTF change)
