### ISSUE TITLE
Spritesheets are re-published after merely selecting them

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#736]
Every time I simply click on a Spritesheet folder, SB will re-publish that particular spritesheet. Apparently merely the act of selecting the spritesheet folder flags the spritesheet as "dirty".

Note: selecting one of the images contained in the spritesheet does not cause a re-publish.

**Comment by NickyWeber** [comment]
I cannot reproduce this on develop (2201c04cac3373717d7b4b51d529cf182f845860) nor on 1.1 (App Store version). 

Did you select **Release** for publishing?

My steps:
- I created a clean project
- Publish mode is Develop
- Created a folder
- drag and dropped some good bunch of large images
- Turned that folder into a smart sprite sheet
- Project Settings: All resolutions are checked so publishing takes a noticeably long time
- Publish: takes some time
- Opened that sprite sheet folder selected an image inisde
- Publish: very fast
- Selected the Smar Sprite Sheet again
- Publish: very fast

**Comment by LearnCocos2D** [comment]
Try it with the LearnSpriteBuilder project here:
https://github.com/learnCocos2D/sbcc

I have develop mode selected in SB but I'm building the release configuration in Xcode. I can definitely reproduce it just by clicking on the spritesheets in the SpriteSheets folder.

Edit: also happens when I build debug config in Xcode, so that's not it.

**Comment by LearnCocos2D** [comment]
- Opened that sprite sheet folder selected an image inisde

Like I said, you have to select the spritesheet (folder) itself. Selecting images contained in the folder does not cause the issue. P

If you have just one spritesheet, be sure to select a different folder, then publish, then select the spritesheet folder again, and publish again to see if just clicking on the spritesheet causes a re-publish.

Though for me the following does provoke a re-publish so it may not be necessary to select something outside the spritesheet:
- select spritesheet folder
- publish (takes a while)
- select images contained in spritesheet
- publish (fast)
- select spritesheet folder again
- publish (takes a while)

**Comment by LearnCocos2D** [comment]
Also noticed that the re-publish occurs on the Tileless Editor View tab. Merely checking and unchecking the sprite sheet in the Filter Folders section at the bottom of the view causes a re-publish. This occurs for both checking and unchecking the sprite sheet.
