### ISSUE TITLE
Make Clean Cache more aggressive

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#742]
Is there any reason that 'clean cache' can't `rm -fr` the generated 'Published-iOS' directory? I ran into some issues making sprite sheet changes and often Xcode Clean/Simulator Clean/SpriteBuilder clean cache didn't help at all.  

However if I deleted the `Published-iOS` directory, then republished, I had the correct assets everytime.

**Comment by NickyWeber** [comment]
Here's how it works at the moment:
- The caches folder only 'hosts' the last sprite sheet processed and packages, this will be deleted on clean chache
- If you hit clean cache the output directories like Published-iOS should be removed on the **next** publish, **before** the actual publishing starts
- If you publish in Develop mode things can accumulate in the outpur directories, a bit like resources copied to an iOS bundle in the simulator
- A clean cache is always performed on Release publish
