### ISSUE TITLE
Problems with git and Iconr file

### ISSUE THREAD

**Issue by Ricardo1980** [spritebuilder/SpriteBuilder#745]
Hello!
It seems there is a special file inside the folder spritebuilder creates. It's called Iconr and when I try to upload it using BitBucket/SourceTree I receive this error:
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree rm -q -f -- src/Climate.spritebuilder/Iconr 
fatal: pathspec 'src/Climate.spritebuilder/Iconr' did not match any files
Completed with errors, see above
Does anyone how to fix it? I cannot upload that file.

**Comment by NickyWeber** [comment]
Have a look at this https://answers.atlassian.com/questions/167170/removing-invisible-icon-files-on-a-local-repository-on-a-mac

**Comment by Ricardo1980** [comment]
Solved adding Icon? to gitignore
