### ISSUE TITLE
Cut, paste, copy,copy as child and delete of "Edit" doesn't work on the resource panel.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#768]
1. Launch application.
2. Create project.
3. Create a folder.
4. Add file in this folder.
5. Select the above created file and from the edit at the top click delete.
   
   --Result: Cut, paste, copy,copy as child and delete of "Edit" doesn't work on the resource panel. Instead of Copy as child it paste CCNode in the timeline of that particular folder. Also gives pop-up on cut. 

Link to the video is attached:
https://drive.google.com/a/werplay.com/file/d/0B2b3lCCE3OwteU1XNlBNV3A1OGc/edit?usp=sharing

**Build:** SpriteBuilder-1.2.0-beta.2

**MAC OS X:** 10.9.0

**Comment by sana20** [comment]
This issue is still occurring.

Build: SpriteBuilderPro-sb-1.2.0-beta.7-dcf-release_3.0.0-alpha.0-f28e9cfda22d61aa5b784b7e7d25f5bae0fe1323_c45808d300864d44.dmg

Mac OS X: 10.9.0
Xcode: 5.0

**Comment by Kanoot** [comment]
This issue is fixed.

Build: SpriteBuilder 1.3 Beta

MAC OS: 10.9.0

**Comment by sana20** [comment]
+Hammad

Sana Shahzad
Quality Assurance Analyst _|_ we.R.play
_www.werplay.com http://www.werplay.com/_
