### ISSUE TITLE
The margins of the Sprite 9 slice are not working properly.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#769]
1. Launch the Sprite Builder 1.2
2. Tap File and make a new project.
3. Tap mainscene.ccb and drag and drop a sprite9 slice node under the ccnode.
4. Add a button from resources in the CCSprite menu "sprite frame".
5. Now change the margins of the ccsprite9slice.
6. Keep top and bottom 0.33 and see the change in the button shape.
7. Keep top and bottom 0.99 and 0 respectively and see the change in the button shape.
   
   -- Result : The margins are not working properly of the sprite 9 slice.

Video link for the issue is below
https://drive.google.com/file/d/0B23s5OMd3iivZFZkOE5va09CeFU/edit?usp=sharing

Mac OS X: 10.9.0
Xcode Version: 5.0
Build: SpriteBuilder-1.2.0-beta.2.zip

**Comment by sana20** [comment]
This issue is still occurring.

Build: SpriteBuilderPro-sb-1.2.0-beta.7-dcf-release_3.0.0-alpha.0-f28e9cfda22d61aa5b784b7e7d25f5bae0fe1323_c45808d300864d44.dmg

Mac OS X: 10.9.0
Xcode: 5.0

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilderAdHoc-sb-1.3.0-rc.1-d49d1950d11b5a27d61b6234761197522d03875a_d6d92a9f14495012

Mac OS X: 10.9.5
XCode: 6.0

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.3.6.rc.1.

Mac OS X: 10.9.5.
XCode: 6.0.

**Comment by sana20** [comment]
This issue is fixed.
Mac OS 10.10.1
SB version 1.4.7
XCode 6.1
