### ISSUE TITLE
Project is not opened when user is opened when user double click the project file.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#771]
1. Launch SpriteBuilder.
2. Create a new project.
3. Close the project.
4. Double click on the icon in finder for SpriteBuilder project.
   
   -- Result: Spritebuilder is opened but project is not opened when user opens it.

Mac OS X: 10.9.2.
XCode: 5.0.
Build: SpriteBuilder-1.2.0-beta.2

**Comment by NickyWeber** [comment]
It's a restriction issue of the sandbox mode. Wontfix.
