### ISSUE TITLE
Cant drag out sprites from a sprite sheet to a scene 

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#773]
I upgraded to SB 1.1.0.

I have a standard sprite sheet. Copied right from a cocos2d v2 projects i'm migrating to v3. 

The plist shows up in the sidebar in SB, and it collapses; I can see all the sprite names in the NSOutlineView. When I try to drag one out onto the scene in SB, drag and drop doesn't work.

My sprite sheet has format 3 in the metadata.

**Comment by ghost** [comment]
hmm.. I can use the sprites frames from a custom sheet if I drag out a blank "sprite" from the object library and then assign it to a sprite frame in the attributes inspector, but I can't drag out sprite frames from a custom sheet (plist) anymore when dragging from "File View".

Also, it appears that the CCBReader class no longer adds a custom sprite sheet's sprite frames to the sprite frame cache automatically when loading a CCBI. Before putting a scene on screen, I have to make sure I programmatically add the sprite sheet to the texture cache/frame cache before it comes on screen otherwise I'll get a bunch of logs: 
cocos2d: Warning: File not found: NameHere 

Is the dropping of this functionality intentional or is this a bug? Seems like a decent regression in functionality and flexibility for developers.

**Comment by NickyWeber** [comment]
Looking into it.

**Comment by NickyWeber** [comment]
This must be a migration issue. I tried SB 1.1 and smart sheets work as expected.
Without your project or an example project were this happens it's impossible to debug this, sorry.

**Comment by ghost** [comment]
Hey Nick,

Thanks for replying. Perhaps you misunderstood what I meant? I wasn't referring to smart sprite sheets, but a sprite sheet made with an external tool. I could send a sample sprite sheet if that helps (format 3 in the metadata).  If you drag it into a Spritebuilder project's resource folder, the issue should be reproduced.

This format is supported by Cocos2d, and drag and drop from the NSOutlineView use to work in Cocosbuilder (and I think SB). But now to set a sprite frame in SB using the sheet, I have to drag a blank sprite out to a scene or node and then assign the sprite frame after.

**Comment by NickyWeber** [comment]
Ah I understand. There is no support of "external" sprite sheets at the moment in SB. I am clearly in favor of this feature since SB is runnng with cocos2d so it should be natural to support it.

**Comment by ghost** [comment]
Ah, that is a bummer. Yeah, it should be easy to support (it actually works now but just not the drag and drop functionality from the NSOutlineView).

I haven't really used Smart sprite sheets before, does it actually just generate the plist or does SB introduce its own format? I like manually managing my own sprite sheets and resources and just have SB publish the CCBI files instead of exporting duplicate assets.

Hope the use of external sprite sheets gets added back in at some point, as it'll help keep Cocos2d's open reputation I think.

**Comment by NickyWeber** [comment]
The smart sprite sheets are not too bad.

Here are the format options you get. 

![bildschirmfoto 2014-08-21 um 21 05 54](https://cloud.githubusercontent.com/assets/5259653/4001755/40afd84e-2966-11e4-9d27-74657e3db43c.png)

The other benefit is that they are scaled depending on the resolutions you set. I think they are now even more space efficient regarding non pot 2 width and height. 

I would close thise issue then, ok?

**Comment by ghost** [comment]
Hey Nick,

Yeah, I wasn't trying to imply that smart sprite sheets are bad, but I just think SB should still support using sheets from external tools that use formats Cocos2d supports. 

Like I said, using an external sprite sheets works just not the drag and drop, but it's up to you if you want to close the bug or if you guys consider it to be intended behavior.

Thanks for the responses. I appreciate it.

**Comment by NickyWeber** [comment]
There should be already a ticket regarding external sprite sheet support.
