### ISSUE TITLE
Sprite sheets are not always published

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#779]
To reproduce. Create a sprite sheet, change a property on the sheet, clean the cache and publish. The sprite sheet isn't published. Hit publish button again and the sprite sheet gets published.

**Comment by NickyWeber** [comment]
This can be narrowed down to: 
- Create a new project, and turn CCBResources folder into a smart sprite sheet
- Clean cache 
- Publish in develop
- Clean cache
- Publish in develop

Sprite Sheets are not created upon second publish
