### ISSUE TITLE
SB project destroyed after opening it with an earlier SB version (App Store v1.1)

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#788]
I'm normally using the latest github develop branch of SpriteBuilder (currently the version from early this week).

I got a report for an issue and tried to reproduce it with the App Store version of SpriteBuilder (v1.1).

The projected opened correctly. I then clicked the "Publish" icon. The publish process was almost instantaneous, which was weird. Afterwards the File View was completely empty. I then looked at the project folder in Finder and all that was left was this:

![screen shot 2014-08-20 at 11 34 35](https://cloud.githubusercontent.com/assets/214599/3978856/87b3ac1c-284d-11e4-8d82-1082f16634de.png)

SpriteBuilder (v1.1) deleted almost every essential file in the project, including the .xcodeproj! :(

I can reproduce this 100% using the App Store build and the given project.
The project is available from google drive:
https://drive.google.com/file/d/0B0g1SgyD5RH2TVpnUVFXLWhyWHc/edit?usp=sharing

---

Regardless of what the problem in this instance may be, there must be some kind of version (mismatch) check which at least warns the user of the possibility of loss of data. Ideally opening a project in an earlier SpriteBuilder version should create a backup copy of the project. As a "quick fix" SB should simply deny any attempts of either opening or publishing (with a warning during open that the project is in "view-only" mode) a project that was saved by a later SB version.

**Comment by LearnCocos2D** [comment]
This is the SB version that's removing the project files upon publish (this ought to be the currently most up-to-date App Store build):
![screen shot 2014-08-20 at 11 57 05](https://cloud.githubusercontent.com/assets/214599/3979097/7100595e-2850-11e4-95bc-13b47de90418.png)

**Comment by cocojoe** [comment]
Thanks for reporting this one, it's came up a few times on the forum as the
mysterious 'SB ate my project' however no one would provide much
information to actually recreate it.

On 20 August 2014 10:58, Steffen Itterheim notifications@github.com wrote:

> This is the SB version that's removing the project files upon publish
> (this ought to be the currently most up-to-date App Store build):
> [image: screen shot 2014-08-20 at 11 57 05]
> https://cloud.githubusercontent.com/assets/214599/3979097/7100595e-2850-11e4-95bc-13b47de90418.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spritebuilder/SpriteBuilder/issues/788#issuecomment-52755736
> .

## 

Martin

**Comment by LearnCocos2D** [comment]
Maybe for the time being there should be a sticky note on the forum & github mentioning that there is currently no "going back" to an earlier version, therefore new SB versions should be tested in backups of the project. 

I can imagine how users commonly run into this issue. It's all too easy to launch the App Store build rather than the latest beta or dev branch, especially if they use the same app icons.

**Comment by cocojoe** [comment]
Yeah agree on the warning, not a bad idea for beta to use a different icon.

On 20 August 2014 11:08, Steffen Itterheim notifications@github.com wrote:

> Maybe for the time being there should be a sticky note on the forum &
> github mentioning that there is currently no "going back" to an earlier
> version, therefore new SB versions should be tested in backups of the
> project.
> 
> I can imagine how users commonly run into this issue. It's all too easy to
> launch the App Store build rather than the latest beta or dev branch,
> especially if they use the same app icons.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spritebuilder/SpriteBuilder/issues/788#issuecomment-52756636
> .

## 

Martin

**Comment by NickyWeber** [comment]
SB should not be able to open project file's that have been created with a newer version of SB.
