### ISSUE TITLE
Dragging multiple nodes can change their selection/draw order

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#789]
Assume you have three nodes in the timeline labelled node1, node2, node3. They appear in that order in the timeline.

Select all three nodes. Drag them onto a new node (let's call it 'container'). This should retain their sort order. Now with the 3 nodes still selected drag them out of the container or to another container node. They will likely reverse their sort order to node3, node2, node1.

Expectation: dragging multiple nodes (to a different parent node) should not change the sort order of the selected nodes.

**Comment by sana20** [comment]
This issue is fixed.
Mac OS 10.10.1
SB version 1.4.7
XCode 6.1
