### ISSUE TITLE
Xcode command line publish does not "unclear" SB cache

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#791]
Perform "clean build folder" in Xcode and "clean cache" in SpriteBuilder, then build the Xcode project. 

This will run the command line publishing for the SB project and probably will take a while. Once done go into SB and click publish. The publish process again takes the same time, publishes all resource files once more. This seems to indicate that the command line publish does not "fill" the caches and SB still considers the caches to be empty respectively all resources are still flagged for republish within SB.

**Comment by NickyWeber** [comment]
Is this still relevant? I think we disabled the extra Xcode script to publish with SB.

**Comment by LearnCocos2D** [comment]
In more recently created SB projects the osascript in the Run Script phase is commented out.

**Comment by NickyWeber** [comment]
Close or keep open?

**Comment by LearnCocos2D** [comment]
Close
