### ISSUE TITLE
One can easily lose edits to physics Categories, Masks and Collision type

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#793]
Somewhat in relation to issue #792 because this bug hinders understanding/debugging #792.
- create a CCB file
- enable physics on any node in the ccb
- save the ccb file
- edit the physics node's collision type, categories and/or masks properties
- observe how these edits do not mark the document as modified
- close the .ccb tab
- notice how user is not asked to save changes, losing the edits to categories/masks (confirm by reopening the ccb)

Also notice that File->Save All does not save the edits, but File->Save does. Depending on whether Publish observes the "modified" state of a document it too may not properly save the edits to categories/masks, causing the xcode project to behave differently than what the user would expect by observing the categories/masks in SB.

**Comment by LearnCocos2D** [comment]
Seems like I've already reported this earlier: https://github.com/spritebuilder/SpriteBuilder/issues/504 (see third comment)

**Comment by trojanfoe** [comment]
I am a newbie to using SpriteBuilder but I think I've seen child assets of the physics nodes go missing during the SB Edit -> Publish -> Xcode Edit cycle.  I think that is related to this bug.

**Comment by sana20** [comment]
This issue is fixed.
Mac OS 10.10.1.
SB version 1.4.7
XCode 6.1
