### ISSUE TITLE
Using Custom Properties with spritebuilder is not working (not showing correct value)

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#82]
when creating a custom proporty for a custom class a ccbfile , then adding this ccbfile as a sub ccb-file in another document and change the value of that custom property , at run time it still show the defualt value nut the new valu from the parnet document .

**Comment by NickyWeber** [comment]
This looks like  a duplicate of #171. I already have a fix ready, let's see when it gets merged.
