### ISSUE TITLE
Official Swift support

### ISSUE THREAD

**Issue by christinakelly** [spritebuilder/SpriteBuilder#822]
1. Add an option when creating a new project to create it as a Swift project.  This involves adding a new target to the template.
2. Documentation for using Swift with SB/CC.

**Comment by vlidholt** [comment]
This works, but autocompletion doesn't. May need additional additions to make the interface better for closures, etc. Awaiting bug fixes in Xcode, or if someone figures out how to get the autocomplete to work,
