### ISSUE TITLE
Android target support in templates

### ISSUE THREAD

**Issue by christinakelly** [spritebuilder/SpriteBuilder#824]
SpriteBuilder should automatically generate an empty Android target for Xcode that can build for Android devices with the installation of the right plugin.

If a user tries to build this target for an iOS device, Xcode should throw an error message that describes how to access the plugin (if the plugin is not installed) or how to build properly for Android (if the plugin is installed).

**Comment by vlidholt** [comment]
This is added, but still no good error message.
