### ISSUE TITLE
Greyscale colour channel image resource kills Sprite Builder

### ISSUE THREAD

**Issue by EnlightenedOne** [spritebuilder/SpriteBuilder#827]
Sprite Builder blows up when a sprite in a ccb scene uses a texture with a greyscale only colour channel, the same sprite with RGB works fine. The resource being included also causes publishing the project to fail. In both cases SpriteBuilder closes immediately (1.2.0).

Here is a sample to demonstrate:
![star](https://cloud.githubusercontent.com/assets/1945825/4179649/adb9fdea-36cf-11e4-9037-6c15984c08b0.png)

The preview of the image in the top left does not crash anything. Create an empty project add the resource to the generic ccbResources folder, try to make a sprite use the image in the initial scene and SpriteBuilder will violently close.

**Comment by Zammy** [comment]
I think I have found the same problem. It is present in 1.1 and 1.2.1. Any of the game-icons.net png resources crash SpriteBuilder. Here is a sample. http://game-icons.net/icons/delapouite/originals/png/rabbit.png

If I open them with pixelmator and resave them SpriteBuilder handles them perfectly.

**Comment by NickyWeber** [comment]
This should be fixed now in develop as of this writing.
