### ISSUE TITLE
Potential Bug?: Lion won't compile out of the box; screencast issues

### ISSUE THREAD

**Issue by asdn** [spritebuilder/SpriteBuilder#83]
hey all - not sure if this got lost in my application to the related google group, so i'm going to paste it below just to be sure. thanks!

i'm having an issue... i have mac osx lion 10.7.5 (xcode 4.5.2), and it (0.9.alpha) won't work. following the screencast at 58 seconds in, it's different for me. in the screencast, the left panel is divided into 2 parts, the bottom part has 2 items: ccbResources (folder), and MainScene.ccb

for me, it's EMPTY. i hit my plus sign to try to add my own folder that way, and it's still EMPTY. however, i did find out that in the finder in my project's folder (which is not on the desktop, not sure if that matters), i found TWO untitled folders... so basically, it correctly made the folders (when i clicked the plus sign), i just can't see any of it in that panel, and i can't follow the screencast anymore. (also it'd be nice if there was a place i could download those tutorial assets/images etc. so i can follow along... is there a download of that somewhere? could you please post it if possible?) 

i tried to run FlyingFeathers as-is to see if it could run completely, and xcode has 4 warnings (i realize this is a VERY early release, btw) and this error:   in CCNode.m, for this line:

[node wasRunning:wasRunning];

it says ARC Semantic issue:

(path to….) FlyingFeathers/Source/libs/cocos2d-iphone/cocos2d/CCNode.m:611:4: No visible @interface for 'CCNode' declares the selector 'wasRunning:'

i'm a newbie, but if i can be of any assistance, please let me know! 

thanks for your help and your hard work on this software!

**Comment by vlidholt** [comment]
SpriteBuilder only supports Mac OS X 10.8 or later.
