### ISSUE TITLE
Unable to select, move or delete spriteframe keyframes of a Sprite CCB's root node

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#840]
I created spriteframe keyframes for a Sprite CCB's root node by selecting image files in a sprite sheet and selecting Create Keyframes. Now I'm unable to select, move or delete those keyframes. I can only add new ones. This is what I get when I right-click a keyframe:

![screen shot 2014-09-11 at 18 01 25](https://cloud.githubusercontent.com/assets/214599/4237202/f4a291e0-39cc-11e4-904d-6a1f0ec53b43.png)

**Comment by LearnCocos2D** [comment]
I added a sprite to the root node and did the same steps. It looks like the main problem here is that the keyframes I see on the root node are only indicators that the node has keyframes, and normally I'm supposed to click the triangle button to unfold the various property timelines like for this sprite:

![screen shot 2014-09-11 at 18 06 08](https://cloud.githubusercontent.com/assets/214599/4237289/9598808c-39cd-11e4-809e-a58e122343cd.png)

However said triangle is missing from the root node (see above). I believe there was another issue mentioning exactly this problem.

**Comment by christinakelly** [comment]
Thanks for the report. Are you using SB 1.2.1 or a beta version (i.e. building from develop)?

**Comment by LearnCocos2D** [comment]
Unless mentioned explicitly I'm typically on one of the latest develop branches. In this case I synched on wednesday or thursday I believe, with the last commit dating 4-5 days back at the time, so that was the most recent version at the time.
