### ISSUE TITLE
No way to turn off packages on new SB projects? Only publish CCBI?

### ISSUE THREAD

**Issue by ghost** [spritebuilder/SpriteBuilder#848]
I have a couple of SB projects that I made before packages were added. I haven't upgraded them and they work as expected.

I just created a new SB project but there seems to be no way to turn packages off. Also the checkbox to "Only Publish CCBI" files is gone. I had a really nice workflow going. I'm sure packages are good but there isn't going to be an option to opt out? This seems like a pretty big regression? Seems a little too domineering?

**Comment by ghost** [comment]
So I ended up hacking it by opening the Spritebuilder project file in text edit and changing the keys. 

I'm actually creating this project to handle a case where sharing a single CCBI file for every device will not work, but there is a bug in Spritebuilder that sometimes displays a sprite frame from the wrong sheet if you have multiple sprite sheets that have a sprite frame with the same name. A lot of times I like managing my own sprite sheets manually for different devices (especially when designing scenes that have complex UIs). Scaling down from @4x doesn't always work. And sometimes (most of the time), it really doesn't make sense to republish all your resources into the publish folder if you are a developer who knows what you're doing. Why not allow me to publish only my ccbi files?

SB is a pretty great tool and it's free so I hate to sound like I'm hate, hate, hating...but it does seem like its taking too much control away from developers. While these features for designers to pass around resources on the web and in emails is great, I don't see why they can't be added into SB while keeping SB's integrity as a developer tool also? 

While hacking it works for now, I'm not confident it will be suitable in updates and I may have to consider dropping SB (which I really don't want to do because I think it's great overall). If I don't feel confident in the fact that my project structures won't just break every time a new version of Spritebuilder comes out, I may have to drop it though if it starts becoming more trouble than it's worth. 

Such forceful changes really changes my entire workflow in a way I don't think is superior to the way I manage my own projects. If developers can't feel confident in getting control and some longevity on the way they do things, I think they'll be reluctant to use the tool. The "What You See Is What You Get" factor will grab the inexperienced developers for sure though. 

I hope you guys will consider giving developers a little more control back in an update.

**Comment by NickyWeber** [comment]
It should be quite easy to turn off package.
A package is a former resource path. Just don't use packages but folders.
In project settings you can say if a package is included in the main project and if it should be published as a zip for every resolution: Just turn off everything and the package won't be touched during publishing.

The only ccb files option was rarely used so it was decided to no longer support it. In the end all you need is the ccb file right? 

If you have multiple issues, please open up more than one github issue. It's hard to keep focused.

**Comment by vlidholt** [comment]
Seems like the easy solution is to just put your ccb files in a package and the resources in another package that you don't publish. Then you can manually handle those resources any way you want. Or am I missing something?

**Comment by ghost** [comment]
After monkeying around a bit, if I do @vlidholt suggestion that is a way I can get Spritebuilder to only publish the CCBI files (having a separate package for resources, though setting a project up this way isn't obvious) There's some extra stuff in the publish folder I don't need but at least it's not republishing 1000 assets to another location unnecessarily. I never not used "Only Publish CCBI" so I guess it never felt like a rarely used feature to me. 

I'm not sure if I get the "Packages" though. I think it would be cool to export a folder as a package from within sprite builder to do the sharing stuff (and import it in another project). During development though say I have a bunch of photoshop files in the same directory as the png's for my sprite sheets because I may decide I want to change an image. So I open up a the photoshop file, make my changes and export the image as a PNG to overwrite the existing images. Now Xcode doesn't need to know about my photoshop source files but only the sprite sheets. Linking everything as a directory isn't the right way to do it. Now having it in a separate packages will fix it. But to get to my image source files, I now have to right click "Show package contents" and get to my stuff to open it in another program. I feel like this kind of gets in the way?

**Comment by NickyWeber** [comment]
There will be a menu option to open these common directories in finder, the terminal and maybe some more apps. I have some myself with the package state of an SB state, but that feature will make it easy to use. Just hang on for a while the feature is on my list.

**Comment by NickyWeber** [comment]
Menu options tracked here: https://github.com/spritebuilder/SpriteBuilder/issues/841.
