### ISSUE TITLE
Build notes in the readme are out of date

### ISSUE THREAD

**Issue by thayerandrews** [spritebuilder/SpriteBuilder#852]
The current build notes in the SpriteBuilder readme make reference to the following step:

```
./BuildDistribution.sh 1.x default
```

But BuildDistribution.sh is deprecated. Instead you should use:

```
./build_distribution.py --version 1.x
```

The readme should be updated to reflect this change.

**Comment by collinjackson** [comment]
I fixed this, please merge my pull request
