### ISSUE TITLE
Update Cocos2D Check

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#856]
How does SB check if the Cocos2D version requires updating, noticed this when creating a new project (develop).

![screen shot 2014-09-22 at 13 52 53](https://cloud.githubusercontent.com/assets/928115/4356289/a46652e6-4257-11e4-901b-e8e6549336d2.png)

**Comment by NickyWeber** [comment]
When SB is built with the script it looks into the used cocos2d lib folder and copies the version file to another place so it gets bundled with SB. During runtime that version file is read and compared with the version file that is within the project's cocos2d folder. The comparison has been enhanced as well to regard semantic versions, like -alpha. However I was not involved so there might be a bug in there.

At least that's the way it was before the build scripts were ported to python.

**Comment by NickyWeber** [comment]
Fixed by viktor.
