### ISSUE TITLE
CCEffect bloom/blur cause the contents to shrink / squeezed

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#867]
When using a bloom or blur effect on CCEffect it renders the contents at about half size, strangely squeezed and apparently only rendering one of the labels:

![screen shot 2014-09-24 at 16 53 58](https://cloud.githubusercontent.com/assets/214599/4390132/b1b21e18-43fa-11e4-835b-a6616081a2fa.png)

This is the same scene with no effect applied to the CCEffect node:

![screen shot 2014-09-24 at 16 53 46](https://cloud.githubusercontent.com/assets/214599/4390148/cbbee44e-43fa-11e4-81c9-ce36ba357185.png)

**Comment by LearnCocos2D** [comment]
Note: this only seems to happen if blur/bloom are used as the sole effects, adding another effect (ie Hue) first and then adding blur/bloom the problem goes away. It's still there if you reverse the effect order, ie blur/bloom first then adding Hue effect.

**Comment by vlidholt** [comment]
May have been fixed
