### ISSUE TITLE
CCEffect: be able to re-order effects via drag & drop

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#870]
I believe shader effects depend on one another, in some cases the order of effects may make a difference. Unless I'm mistaken with that thought, I think the UI should enable reordering of effects via drag & drop.

**Comment by vlidholt** [comment]
This definitely would be nice (although may not be a blocker for release)

**Comment by NickyWeber** [comment]
Working ticket is https://github.com/spritebuilder/SpriteBuilder/issues/1154 now.
