### ISSUE TITLE
CCEffect: can add the same effect multiple times (ie pixelate multiple times)

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#871]
Not sure if having multiple effects of the same type makes sense for specific effects. At least several effects really needn't be stacked, for instance I can't think of any reason why one would need two or more active Pixelate effects. Or multiple saturation, hue, contrast, brightness effects unless this is multipass rendering where you may want to blur with hue first, then pixelate with a different hue. I don't know, it kinda sounds like this may make sense sometime somewhere but I can't say for sure.

For effects that shouldn't be stacked, they should be grayed out in the add (+ button) context menu when the effect of the same type has already been added.

**Comment by vlidholt** [comment]
Or at least limit the number of effects to, say 5.

**Comment by vlidholt** [comment]
Talked with Thayer, limiting the effects to 5 should be a good solution. I don't think we necessarily need to stop users from doing stupid stuff. :P You can add as many redundant effects as you wish in for example PhotoShop.
