### ISSUE TITLE
CCBReader currently out of synch

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#873]
In order to test CCEffect I had to replace the project's cocos2d-iphone folder with the one found in SpriteBuilder/libs/cocos2d-iphone. I'm on this commit: 50eeead6774af63e84cbf25fe96e1e5d7d500c40

However the writer/reader streams seem to be out of synch, resulting in an assertion that I've added to verify that a physics body has joints (assert fails because joints list is empty). This issue occurs even without any CCEffectNode used in the project. If I dig deeper it has the typical hallmarks of previous "out of synch" occurances, where for example CCBReader tries to instantiate a class via NSClassFromString where the name is "name" or "player" (the name of a property or node).

Interestingly the CCEffectNode itself is working fine.

I performed a clean cache in SB, clean build folder in Xcode and removed the app from the device/simulator to remove any potential "leftovers" from the equation.

Here's the link to the project to test the issue with:
https://drive.google.com/a/apportable.com/file/d/0B0g1SgyD5RH2aExpZ2U4UGNUNWs/edit?usp=sharing

To reproduce:
- Build & run Xcode project
- Main menu with CCEffectNode should be working fine
- Click on PLAY and select the 1st level of the 1st world (may need to swipe left)
- Assertion in SpringBoard.m occurs on load (SpringBoard's physicsBody has no joints)

The error goes away if I rebuild the project with the old cocos2d-iphone version but of course effects aren't working in that case.

**Comment by vlidholt** [comment]
Seems to be fixed!
