### ISSUE TITLE
Changes to effects do not mark CCB document as modified

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#874]
**UPDATE:** See 2nd comment, issue is that changes to effects do not mark the CCB document as modified!

I have added a CCEffectNode to a scene and added every available CCEffect to it in order to see the available parameters. I published this version and well of course it kills the performance and draws only a black background.

I then removed most of the effects, leaving only hue, pixelate, brightness yet when I run the app it still draws the extremely slow black screen. Apparently the effects that were once added haven't been removed.

This issue persists even after Clean Cache (SB), Clean Build Folder (Xcode) and deleting app from device/simulator.

Can be reproduced in this project (same as the one in the previous issue report):
https://drive.google.com/a/apportable.com/file/d/0B0g1SgyD5RH2aExpZ2U4UGNUNWs/edit?usp=sharing

Open MainScene.ccb, select CCEffectNode, note that it has only a couple effects and they are working nicely. Publish and run the project and you'll find the launch scene having a black background running extremely slow.

**Comment by LearnCocos2D** [comment]
GOTCHA!

The problem here is that the effects will only be updated when the CCB is saved. However adding/removing effects from the list doesn't mark the document as modified, therefore publish will continue to publish the CCB on disk while any changes remain in memory (at least that's what I think happens).

Once you hit Cmd+S in the CCB with the effects they will be published properly. So the problem here is that changes to effects do not mark the CCB document as modified.

**Comment by vlidholt** [comment]
What needs to happen here is to monitor when:
1. Effects are added
2. Effects are removed
3. Effect properties are changed

Right before any of those happens the `saveUndoStateWillChangeProperty:` of the app delegate should be called. The property can be 'effect_added', 'effect_removed', or 'effect_propertyName'. Doing this will also fix undo/redo. It's possible that this is solvable with monitoring the effect properties with KVO, added/removed effects should be easy.

**Comment by vlidholt** [comment]
Fixed! :)
