### ISSUE TITLE
CCScrollView: Scrolling happens backwards

### ISSUE THREAD

**Issue by christinakelly** [spritebuilder/SpriteBuilder#883]
Scrolling by touching and dragging to the right scrolls to the left instead and vice versa.  See @LearnCocos2D's test project.  Breckin confirmed this on the NVidia Shield.

**Comment by Kanoot** [comment]
@christinakelly -- This issue is fixed, tested on android device.

**Build:** SpriteBuilder-1.3.0-beta.07.zip

MAC OS: 10.9.0
Android device: Sony Xperia Z/4.2.2
