### ISSUE TITLE
CCScrollView: Assets are not properly positioned

### ISSUE THREAD

**Issue by christinakelly** [spritebuilder/SpriteBuilder#884]
See @LearnCocos2D's sample project.  Assets on the world select screen and other screens are not properly sized and are too far down on the screen.  Tested by Breckin on the Nvidia Shield.

**Comment by LearnCocos2D** [comment]
It seems more like the position of the scroll view content is offset (I would say Y pos is reduced by about half the height of the content). The size itself seems to be okay.

**Comment by Kanoot** [comment]
@christinakelly -- This issue is fixed when tested on android device without changing the content size of the scroll view.

**Build:** SpriteBuilder-1.3.0-beta.07.zip

MAC OS: 10.9.0
Android device: Sony Xperia Z/4.2.2
