### ISSUE TITLE
Packages test needs NSURLProtocol on Android

### ISSUE THREAD

**Issue by christinakelly** [spritebuilder/SpriteBuilder#885]
The packages test in Cocos2D 3.3 beta uses NSURLProtocol, which is not implemented yet in the Android Plugin.  This needs to either be implemented or a workaround added.  Need to figure out whether it's just the test that uses it or the feature itself.

**Comment by itfische** [comment]
Only the tests appear to use NSURLProtocol.  Daniel is talking with Nicky about alternative ways to implement the tests so we can run them on Android.

**Comment by NickyWeber** [comment]
Added real download for ui tests. Unit tests however should work in isolation therefore without a real internet connection.

Ready for merge along with missing unit tests:
https://github.com/cocos2d/cocos2d-swift/pull/1010
