### ISSUE TITLE
Android: sound files can't be found

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#886]
Only on android a call like this raises a Java FileNotFoundException:

```
[audio playBg:@"Audio/menu-music.m4a" loop:YES];
```

I know that the files have been converted to .ogg so I tried .ogg as extension with the same result. I tried .wav as extension (same as source file in SpriteBuilder) and without any extension. Always the same result.

The same happens with playEffect and .caf files except they are only logged, they don't raise exceptions.

**Comment by ebrodzki** [comment]
So the issue here is that you are passing in a path that does not exist on Android. The way the project is set up it seems that it needs to have the Published-Android/ before the filename. Also, since the asset is an ogg not a m4a, that needs to be different as well.

[audio playBg:@"Published-Android/Audio/menu-music.ogg" loop:YES];
^ should fix it for you. Tested and had music playing in the menu.

**Comment by NickyWeber** [comment]
Maybe the filenamelookup is not working properly?

**Comment by LearnCocos2D** [comment]
Sounds like CCFileUtils needs an update? The "Published-Android" part of the path _ought_ to be taken care of by file lookup as is the case with "Published-iOS" on iOS. It would certainly be counter-productive having to use two different (#ifdef'ed) paths for the two platforms.

**Comment by ebrodzki** [comment]
It looks like the ObjectAL here does not go through the CCFileUtils to find the file, which is why it "needs" the Published-Android appended to the front. We can change it on that side to be correct as it is already under a __CC_PLATFORM_ANDROID #ifdef

**Comment by ebrodzki** [comment]
This is now fixed with the updated objectAL submodule

**Comment by LearnCocos2D** [comment]
Has this been tested with both playEffect and playBg methods of OALSimpleAudio? Because I can play sound with the .wav extension using playEffect but the music played via playBg remains silent on Android.

**Comment by LearnCocos2D** [comment]
Following audio (from the Bouncy Beast project) plays fine with playEffect but playBg doesn't play the music on Android:

```
    OALSimpleAudio* audio = [OALSimpleAudio sharedInstance];
    // doesn't play:
    [audio playBg:@"Audio/menu-music.wav" loop:YES];

    // this works:
    [audio playEffect:@"Audio/menu-music.wav" loop:YES];
```

**Comment by LearnCocos2D** [comment]
For now I helped myself by hacking playBg so it redirects to playEffect on Android:

```
- (bool) playBg:(NSString*) filePath loop:(bool) loop
{
#if __CC_PLATFORM_IOS
    if(nil == filePath)
    {
        OAL_LOG_ERROR(@"filePath was NULL");
        return NO;
    }
    return [backgroundTrack playFile:filePath loops:loop ? -1 : 0];
#elif __CC_PLATFORM_ANDROID
    return [self playEffect:filePath loop:loop];
#endif
}
```

**Comment by rkachowski** [comment]
This is fixed on current develop.
