### ISSUE TITLE
Android: NSWeakPointerArray causes app to freeze

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#887]
I have a NSWeakPointerArray. On Android, whenever execution hits the addPointer: line execution just freezes:

```
    triggers = [NSPointerArray weakObjectsPointerArray];
    [triggerArrays setObject:triggers forKey:_name];

    // add this trigger to the list
    [triggers addPointer:(void*)self];
```

self inherits from CCNode, it's a custom class assigned to nodes in SpriteBuilder
This code works perfectly fine on iOS.

**Comment by ebrodzki** [comment]
This is being fixed and will hopefully be in the next update
