### ISSUE TITLE
Improvements to template project

### ISSUE THREAD

**Issue by christinakelly** [spritebuilder/SpriteBuilder#888]
1.  Add a mac target
2.  Remove all targets except iOS, Android, and Mac
3.  Default target should either be iOS or Mac
4.  There should be a platforms folder with AppDelegates for each platform in the user's code which can be edited
5.  Refactor AppDelegate setup code to be consistent across platforms - the editable parts should probably live in the user's project for iOS, Android, and Mac; the rest can be in a single class in Cocos2D.
6.  Add Android targets to Chipmunk and Tremor so iOS devices don't show up on the Android target

**Comment by collinjackson** [comment]
#908 Fixes all but bullet 5. I will make a new issue for that.

**Comment by collinjackson** [comment]
Filed #912
