### ISSUE TITLE
Sprite 9 Slice Crashes Editor

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#897]
1) Add 'Sprite 9 Slice' to Scene
2) No properties are visible and you can'd do anything with it
3) Try and remove it with backspace (doesn't work)
4) Edit/Cut, crashes editor.

Tested Latest Develop

**Comment by Neophen** [comment]
ahhh
this is causing so many crashes for me :)

**Comment by NickyWeber** [comment]
Confirmed, this is a show stopper. I will take care of it after I finish some refactoring, beginning next week.
