### ISSUE TITLE
SpriteBuilder incorrectly overwrite files with specific publish settings

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#9]
SpriteBuilder incorrectly overwrite files if the project settings are set to "Publish to directory" = "." and "Only publish ccb-files" is checked.

These are the options used when using SpriteBuilder to only do the interface files, but not have it manage your resource files. Publish directories should only be overwritten (removed) when SpriteBuilder is managing the resources (this is the default option when creating new projects).

**Comment by jtwigg** [comment]
Status:
With "Only Public Checked". the Publish folder was being completely nuked. I've prevented this from occurring.
