### ISSUE TITLE
Cleanup cocos2d-iphone folder to reduce project size

### ISSUE THREAD

**Issue by LearnCocos2D** [spritebuilder/SpriteBuilder#915]
In projects created by SB the cocos2d-iphone folder contains folders that aren't needed for or during development of the project. The potential for reducing size is significant, around 30-40 MB.

Here are some files/folders that can be removed safely from a newly created SB project's `Source/libs/cocos2d-iphone` folder and have a noticeable size:

```
cocos2d-tests-android
cocos2d-tests-ios.xcodeproj
cocos2d-tests-ios
cocos2d-tests-osx.xcodeproj
cocos2d-ui-tests
Resources
Resources-iPad
Resources-Mac
tools
UnitTests
```

In the `external/Chipmunk` folder these folders can be removed safely:

```
Demo
doc
doc-src
msvc
xcode
```

In the `external/ObjectAL` folder these (sub)folders can be removed safely:

```
ObjectAL/diagrams
ObjectALDemo
Sample Code
```

By "safely" I mean that I used to remove all these folders from every project respectively after updating cocos2d-iphone and it never had any adverse effect on the project whatsoever. Any resources needed by the project are already provided by SB, so the resources folder in cocos2d are just duplicates and extraneous image, font, audio files for the tests mainly.

**Comment by cocojoe** [comment]
Awesome

**Comment by LearnCocos2D** [comment]
Just sent a pull request: https://github.com/spritebuilder/SpriteBuilder/pull/984

**Comment by LearnCocos2D** [comment]
Btw, this is what gets removed in this first version:

```
    NSString* cocosPath = @"Source/libs/cocos2d-iphone";
    NSArray* removeItems = @[@"build",
                             @"cocos2d-tests-android",
                             @"cocos2d-tests-ios.xcodeproj",
                             @"cocos2d-tests-android",
                             @"cocos2d-tests-osx.xcodeproj",
                             @"cocos2d-tests.xcodeproj",
                             @"cocos2d-ui-tests",
                             @"Resources",
                             @"Resources-iPad",
                             @"Resources-Mac",
                             @"tools",
                             @"UnitTests",
                             @"external/Chipmunk/Demo",
                             @"external/Chipmunk/doc",
                             @"external/Chipmunk/doc-src",
                             @"external/Chipmunk/msvc",
                             @"external/Chipmunk/xcode",
                             @"external/ObjectAL/ObjectAL/diagrams",
                             @"external/ObjectAL/ObjectALDemo",
                             @"external/ObjectAL/Sample Code",
                             ];
```

**Comment by LearnCocos2D** [comment]
Hmmm this also needs to run after every cocos2d update. I should probably move this to CCBFileUtil and call it from both CCBProjectCreator and Cocos2dUpdater.

**Comment by LearnCocos2D** [comment]
Updated pull request, cleanup now runs on cocos2d update as well as new project creation:
https://github.com/KoboldKit/SpriteBuilder/compare/develop-steffen?expand=1
