### ISSUE TITLE
Sprite Frame Selection Image Preview

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#917]
Would be nice to have a thumbnail preview when flicking through sprite frames.

![screen shot 2014-10-11 at 16 32 19](https://cloud.githubusercontent.com/assets/928115/4603100/cde49714-515b-11e4-84ce-ac91e9aca8ab.png)

**Comment by extrajordanary** [comment]
working on an implementation of this now

**Comment by extrajordanary** [comment]
Progress! 
I'll be cleaning up the code and creating a pull request tomorrow. 
![screen shot 2014-11-20 at 1](https://cloud.githubusercontent.com/assets/4017420/5137382/b4893bd4-70ec-11e4-90fd-6c43ed95721f.png)

**Comment by NickyWeber** [comment]
Cool. You may want to talk to Viktor: We coulde even add an image well to the inspector to drag drop a selection from the resource view.

**Comment by cocojoe** [comment]
Looks good, @vlidholt can you pass your eye over this one for UI impact please?

How does it decide upon the height of the selection window? Looks really tall e.g. taller than the app.  I'm trying to find a comparison in something like Xcode.

**Comment by extrajordanary** [comment]
@cocojoe Yeah, I think the menu defaults have it just make itself as big as possible. It does the same thing for the font selection menu which has a lot of items.
@NickyWeber Oh, an image well is an interesting option.

**Comment by cocojoe** [comment]
@extrajordanary feel free to make a pull request, be nice to see this one in action.
