### ISSUE TITLE
Remove private API calls

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#92]
Make sure that there are no private API calls happening anywhere.

**Comment by jtwigg** [comment]
These have been obfuscated. Is that sufficient?

**Comment by vlidholt** [comment]
The use of non-public APIs can lead to a poor user experience should these APIs change in the future, and is therefore not permitted. The app includes OBJC_IVAR_$_NSActionCell._controlView from the framework '/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit'.

Will try to fix this now!
