### ISSUE TITLE
Application crashes when user tries to save the project after deleting the joints.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#920]
1. Launch application.
2. Create a new project.
3. Drag and Drop 2 Physics Joint under Joint.
4. Select Joint in timeline.
5. Click delete.
   -- Observe: PhysicsJoints under the Joint select down are not deleted and PhysicsJoints become empty. (Un-expected)
6. Try to create a new project.
   -- Observe: Save project option is displayed. (Expected)
7. Click don't save.
   
   -- Result: Application crashes when user clicks don''t save.

Video: https://drive.google.com/file/d/0B5KeRaV3CWUaWGM1QTBYZmpsVVk/edit?usp=sharing

This happened 3/3 times.
Build: SpriteBuilder 1.3 Beta 07

Mac OS X: 10.9.2.
XCode: 5.0.

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder 1.3 RC on:

Mac OS X: 10.9.5
XCode: 6.0.

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.3.0-rc.1.zip on Mac OS X: 10.9.5. and XCode: 6.0.

**Comment by Kanoot** [comment]
This issue is reoccurring.

SpriteBuilder-1.3.4-rc.1

Device A:
Mac OS X: 10.9.5
XCode: 6.0

**Comment by cocojoe** [comment]
Fixing #919 will sort this.

**Comment by Kanoot** [comment]
This issue is reoccurring.

Build: SpriteBuilder-1.3.5-rc.2

MAC OS: 10.9.5
XCode: 6.0

**Comment by Kanoot** [comment]
This issue is reoccurring.

Build: SpriteBuilder-1.3.6.rc.1

Mac OS X: 10.9.5.
XCode: 6.0.

**Comment by Shahidwerplay** [comment]
This issue is reoccurring on SB 1.4.9.

Mac OS X: 10.10.0.
XCode: 6.2.

**Comment by Shahidwerplay** [comment]
This issue is reoccurring.

Mac OS X 10.10.0
SB Version latest develop branch (2.0)
SB Revision 4fd68fb 
XCode 6.1
