### ISSUE TITLE
'Visible' and 'Lock' button of default timeline doesn't work.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#923]
1. Launch SBP.
2. Create a new project.
3. Select MainScene.ccb.

--Result: 'Visible' and 'Lock' button of default timeline doesn't work. 

![doesn_t_work](https://cloud.githubusercontent.com/assets/7566802/4610831/961c667c-52b4-11e4-9bbe-eeb15abbebe0.png)

**Build:** SpriteBuilder 1.3 Beta 07

MAC OS: 10.9.0
XCode version: 5.0

**Comment by Kanoot** [comment]
This issue is still occurring.

Build: SpriteBuilder-1.3.0-rc.1.zip

MAC OS: 10.9.0
XCode: 5.0

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.3.4-rc.1 on:

Mac OS X: 10.10
XCode: 6.0.

**Comment by cocojoe** [comment]
I don't think this is a bug, just a miss understanding as the visible and lock icons beside the timeline title I thought were just column description headers?
