### ISSUE TITLE
SBP crashes when user creates another new package whilst the former new package wasn't named yet.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#924]
1. Launch application.
2. Create a new project.
3. Create new package.
4. Create another new project.
   
   --Result: SBP crashes when user creates another new package whilst the former new package wasn't named yet. 

For video see this ticket:
https://phabricator.apportable.com/T666

**Build:** SpriteBuilder 1.3 Beta 07

MAC OS: 10.9.0
XCode version: 5.0

**Comment by sana20** [comment]
This issue is fixed.

**Build:** SpriteBuilder-1.3.0-rc.1
**Mac OS X:** 10.9.0
**XCode:** 5.0

**Comment by sana20** [comment]
This issue is re-occurring.
Build: SpriteBuilder-1.3.6.rc.1
Mac OS X: 10.9.5
XCode: 6.0

**Comment by sana20** [comment]
This issue is fixed.
Build: SB Version: 1.4.0-beta.02
Mac OS X: 10.10.0
XCode: 6.0
