### ISSUE TITLE
SBP doesn't give any warnings when user tries to creates a Package within a Package 'Content' through the finder.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#926]
1. Launch application.
2. Create a new project.
3. Create a new package.
   -- Observe: 2 packages are created let we call the A and B for simplicity.
4. Right Click B package on the resource browser and select show in finder.
5. Copy package B.
6. Go the package A in finder and tap "show package content".
7. Paste the item (which is package B).
8. Likewise, copy package A inside Package B's content.
   
   -- Result: SBP doesn't give any warnings when user tries to creates a Package within a Package through the finder. Moreover you can make that package smart, this option is available for this case unexpectedly.

For video visit this ticket:
https://phabricator.apportable.com/T668

Build: SpriteBuilder 1.3 Beta 07

MAC OS: 10.9.0
XCode version: 5.0

**Comment by NickyWeber** [comment]
This can't be solved. Finder actions regarding packages are not supported.
