### ISSUE TITLE
Creating changes in the package in the finder don't sync with the SBP project not even in the settings.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#927]
1. Launch application.
2. Create a new project.
3. Create a new package.
4. Go into the finder.
5. Change the name of the packages in the finder. 
   
   -- Result: Creating changes (or delete packages in the finder or copy) in the package in the finder don't sync with the SBP project not even in the settings. 

For video view this ticket:
https://phabricator.apportable.com/maniphest/task/edit/669

**Build:** SpriteBuilder 1.3 Beta 07

MAC OS: 10.9.0
XCode version: 5.0

**Comment by NickyWeber** [comment]
This is expected behaviour. A user must not rename packages.
