### ISSUE TITLE
New file are not created in correct location when user changes path for ".zip" file in project settings.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#929]
1. Launch Application.
2. Create a new project and tap project settings.
3. Select "as zip file".
4. Change path "Custom directory for zip files" and tap done.
5. Create a new file.
   -- Observe: File is created in the resource viewer. (Expected)
6. Publish.
7. Open finder.
   
   -- Result: File is not found in the resource folder and in the changed path.

**Build:** SpriteBuilderPro-sb-1.2.0-beta.7-dcf-release_3.0.0-alpha.0-f28e9cfda22d61aa5b784b7e7d25f5bae0fe1323_c45808d300864d44.dmg

**MAC OS:** 10.9.2
**XCode Version:** 5.0

**Comment by NickyWeber** [comment]
I cannot even choose select. The project settings cannot be dismissed.

**Comment by NickyWeber** [comment]
Can you please elaborate what you mean by "2. Create a new project settings.".
Did you forget to publish?

**Comment by Kanoot** [comment]
@NickyWeber -- I have edited Bug description and now it has all the detail steps. 
Published the project after changing path of .zip files in the resource settings.  

One more thing tested this bug again on **SpriteBuilder 1.3 Beta 07**, SBP crashes when we tapped "select" button of "custom directory for zip files".

**Comment by NickyWeber** [comment]
@Kanoot
- Select bugfix is ready for merge and will be hopefully in the Beta 08 release for further testing: https://github.com/spritebuilder/SpriteBuilder/pull/999
- Bugfix for only checking "Custom directory for Zip files" without selecting a directory is also ready for merge: also in https://github.com/spritebuilder/SpriteBuilder/pull/999

**Comment by NickyWeber** [comment]
Bugfix is merged.

**Comment by Kanoot** [comment]
This issue is fixed.

Build: SpriteBuilder-1.3.0-rc.1.zip

MAC OS: 10.9.0
XCode: 5.0
