### ISSUE TITLE
Name property missing

### ISSUE THREAD

**Issue by vlidholt** [spritebuilder/SpriteBuilder#93]
The name property is missing in SpriteBuilder (since the tag was removed)

**Comment by jtwigg** [comment]
Do I do this by adding it to the CCBProperties.plist?

**Comment by jtwigg** [comment]
CCBReaderInternal
CCBWriterInternal
CCBReader in the cocos2d project
CCBWriter  
CCBXCocos2diPhone

**Comment by jtwigg** [comment]
Name property added.

1) Make node.name fields match the timeline.name field.

**Comment by jtwigg** [comment]
fixed.
