### ISSUE TITLE
Application crashes when user tries to bring two items to the front after each turn.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#931]
1. Launch SpriteBuilderPro.
2. Create New Project.
3. Open Mainscene.ccb.
4. Drag and drop a object named "first.png" on the stage.
5. Drag and drop another object named "second.png" on the stage.
6. Select first.png.
7. Select Object > Arrange > Bring to the front.
8. Select second.png.
9. Select Object > Arrange > Bring to the front.
   
   -- **Result:** Application crashes when user selects second object to bring to the front.

This happened 3/3 times.

**Build:** SpriteBuilder 1.3 Beta 07

**Mac OS X:** 10.9.2.

**XCode Version:** 5.0

Project File: https://drive.google.com/file/d/0B5KeRaV3CWUaaUI3a1JZUXNja0U/edit?usp=sharing

**Comment by NickyWeber** [comment]
Cannot confirm crash.

**Comment by Kanoot** [comment]
This issue is fixed.

Build: SpriteBuilder-1.3.0-rc.1.zip

MAC OS: 10.9.0
XCode: 5.0
