### ISSUE TITLE
Object name is changed to blank when user brings an object to the front.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#932]
1. Launch SpriteBuilderPro.
2. Create New Project.
3. Open Mainscene.ccb.
4. Drag and drop a object named "first.png" on the stage.
5. Select first.png.
6. Select Object > Arrange > Bring to the front.
   
   -- **Result:** Object is brought to the front but it's name is changed to a blank name.

This happened 3/3 times.

![untitled4 1](https://cloud.githubusercontent.com/assets/7566802/4612290/9fadadde-52c5-11e4-9ec8-575d8565acc9.png)

**Build:** SpriteBuilder 1.3 Beta 07

**Mac OS X:** 10.9.2.
**XCode Version:** 5.0

**Comment by khanbhai89** [comment]
This issue is fixed on SpriteBuilder-1.3.0-rc.1.zip

Mac OS X:10.9.5.
XCode: 6.0.
