### ISSUE TITLE
Enabling spring in the pivot joint doesn't have any effect on the pivot effect.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#934]
1. Launch Application.
2. Create a new empty project.
3. Add two color nodes to the stage.
4. Add a pivot joint between them.
5. Enable "Spring".
6. Publish the project.
7. Open XCode project file.
8. Build and Run the project.
   
   -- Result: Enabling spring and changing its value have no effect on the Pivot Joint.

This happened 3/3 times.

Build: SpriteBuilder-1.3.0-beta.07.zip

Mac OS X: 10.9.5.
XCode 6.0.

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilderAdHoc-sb-1.3.0-rc.1-d49d1950d11b5a27d61b6234761197522d03875a_d6d92a9f14495012

Mac OS X: 10.9.5
XCode: 6.0

**Comment by Kanoot** [comment]
This issue is reoccurring.

Build: SpriteBuilder-1.3.5-rc.2

MAC OS: 10.9.5
XCode: 6.0

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.3.6.rc.1.

Mac OS X: 10.9.5.
XCode: 6.0.

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.4.0-rc.0.zip

Mac OS X:10.9.5
XCode: 6.0.

**Comment by sana20** [comment]
This issue is re-occurring on SpriteBuilder-1.4.8-rc.0 with SBAndroid Indie (SBAndroidPluginIndie-sbandroid-indie-704bb7c4b3507f7e).

Mac OS X: 10.10.1
XCode: 6.1.
Device: Note 2/4.1.1.

**Comment by Shahidwerplay** [comment]
This issue is fixed. 

Mac OS X 10.10.0
SB Version latest develop branch (2.0)
SB Revision 4fd68fb 
XCode 6.1

**Comment by sana20** [comment]
This issue is fixed.

Mac OS X: 10.10.1
XCode: 6.1.
Latest Develop branch SB Version (2.0)
SB Revision: 02eedd1
