### ISSUE TITLE
Clean Cache menu doesn't work when user clicks it.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#941]
Launch SBP.
Start building project angry birds: https://docs.google.com/a/werplay.com/spreadsheet/ccc?key=0AlGPsIAiDQWLdG5WWTBuLXd6b1FRcktSWFp3eHoxRHc#gid=9
Publish project.
Click Clean Cache button.
Result:*\* Nothing happens when user clicks "clean cache" button.
Build: SpriteBuilder 1.3 Beta 07

MAC OS: 10.9.2

XCode: 5.0

**Comment by NickyWeber** [comment]
Dupicate of https://github.com/spritebuilder/SpriteBuilder/issues/945

**Comment by sana20** [comment]
+Hammad

Sana Shahzad
Quality Assurance Analyst _|_ we.R.play
_www.werplay.com http://www.werplay.com/_
