### ISSUE TITLE
"Transparent", "Opaque" and "None" are displayed same on the stage.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#944]
1. Launch application.
2. Create a new project.
3. Select Document > Stage Border > Select "Transparent", "Opaque" or "none" as borders.
   Result: All the borders are displayed same on the stage.
   Build: SpriteBuilder 1.3 Beta 07

Mac OSX: 10.9.2.

**Comment by rkachowski** [comment]
This feature works as designed, the visible appearance will only appear different when you have a stage object that is partially occluded by the border of the stage.

i.e. the only visible difference is for sprites that are outside of the stage.
