### ISSUE TITLE
Clean Cache menu doesn't work when user clicks it.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#945]
1. Launch SBP.
2. Start building project angry birds: https://docs.google.com/a/werplay.com/spreadsheet/ccc?key=0AlGPsIAiDQWLdG5WWTBuLXd6b1FRcktSWFp3eHoxRHc#gid=9
3. Publish project.
4. Click Clean Cache button.
   
   **-- Result:** Nothing happens when user clicks "clean cache" button.

**Build:** SpriteBuilder 1.3 Beta 07

**MAC OS:** 10.9.2

**XCode:** 5.0

**Comment by NickyWeber** [comment]
Clean Cache is working two ways:
- The caches directory is deleted.
- Publishing next time will do a full publish.

What behaviour is expected?

**Comment by sana20** [comment]
+Hammad

Sana Shahzad
Quality Assurance Analyst _|_ we.R.play
_www.werplay.com http://www.werplay.com/_

**Comment by Shahidwerplay** [comment]
This issue is fixed.
Mac OS 10.10.0
SB version 1.4.7
XCode 6.1
