### ISSUE TITLE
"No Invisible @interface 'UITouch' declares the selector 'LocationInNode:'" error is displayed when user tries to Implement shooting by dragging the catapult arm.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#946]
1. Launch SBP.
2. Follow the Peeved Penguins demo till 'Putting it into code' in "Implement shooting by dragging the catapult arm", by this link:
   https://www.makegameswith.us/tutorials/getting-started-with-spritebuilder/spritebuilder-physics/
3. Run the project.
   
   **--Result:** "No Invisible @interface 'UITouch' declares the selector 'LocationInNode:'" error is displayed when user tries to Implement shooting by dragging the catapult arm.

**Project Link:**
https://drive.google.com/file/d/0B2b3lCCE3OwtUFF3N3lTWl93dnM/edit?usp=sharing

![failed](https://cloud.githubusercontent.com/assets/7450007/4614003/c0f0a684-52db-11e4-8e4a-c60fe953862e.png)

**Build:** SpriteBuilderPro-beta-cb90765ab8f9aaad4b92a2908c36c92f95f47c47_03785ccf1eca39d6.dmg

**MAC OS:** 10.9.0

**XCode:** 5.0

**Comment by cocojoe** [comment]
This is covered in http://www.spritebuilder.com/update/ although it's not super obvious as people tend not to read such things.
