### ISSUE TITLE
Start colour doesn't go to it's original state when user re-selects the template

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#947]
1. Launch application.
2. Create new project.
3. Create new file  > Type particles.
4. Create new template through Particle effect template button.
5. Select your template > Change the start colour of your template through property inspector.
6. Re-select your template.
   -- Observe: The template remains the same. (Expected)
7. Go to property inspector > Start colour.
   
   -- Result: Start colour doesn't go to it's original state when user re-selects the template.

Build: SpriteBuilderPro-sb-pro-1.3.0-beta.02-dcf-release_3.0.0-alpha.4-c54e1bc047184ee7634cd5166540a12b50e8ffa4_78169aaaa715dff1

Mac OS Version: 10.9.4.
XCode: 5.0
Video: https://phabricator.apportable.com/T761

**Comment by nickbit** [comment]
Maybe it is the same bug:
Trying to alter the start or end color variance, changes the start or end color.
