### ISSUE TITLE
BoxLayout layer vanishes when user drags it under an image in the timeline view.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#951]
1. Launch application.
2. Create new empty project.
3. Open MainScene.ccb.
4. Drag and Drop BoxLayout Node on the stage.
5. Add 2-3 Color nodes as it's child.
6. Drag an image to stage under Root Node.
7. Drag the BoxLayout Node under the image dragged above.
   
   -- Result: BoxLayout layer vanishes from the stage. (Please See the video attached)

Build: SpriteBuilder-1.3.0-beta.07.zip

Mac OS X: 10.9.5.
XCode: 6.0.

**Comment by NickyWeber** [comment]
There is no video attached, please add link.

**Comment by khanbhai89** [comment]
This issue is fixed on SpriteBuilderPublicBeta-sb-1.3.0-beta.10-dcf-release_3.0.0-alpha.8-1796a6195bb752e59cffb5248f53ae39ca6fe441_3c4f284919369e12.dmg on Mac OS X: 10.9.5. on XCode: 6.0.

We can close it.
