### ISSUE TITLE
Portrait project doesn't work in Xcode 6

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#954]
Changing project settings to 'Portrait' in SB and deploying is not setting deployment info correctly in Xcode 6.  Landscape options need to be changed to portrait as illustrated.

Note: Works fine in Xcode 5.

![screen shot 2014-10-13 at 17 06 59](https://cloud.githubusercontent.com/assets/928115/4616382/16a91d42-52f3-11e4-9c6f-1b469640945c.png)

**Comment by Shahidwerplay** [comment]
This issue is fixed.
Mac OS 10.10.0
SB version 1.4.7
XCode 6.1
