### ISSUE TITLE
Image expands and distorts when user added some effect to the CCEffectNode and tries to change to its area.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#962]
1. Launch application.
2. Create a new project.
3. Drag flurryfeathers image folder and make it smart sheet after removing ground and background from the folder.
4. On MainScreen.ccb delete gradient node and label
5. On MainScreen.ccb add CCEffectNode.
6. Drag gradient node as child under CCEffectNode.
7. Drag bird image as child under CCEffectNode.
8. Add blur effect to the CCEffectNode.
   
   --Result: Image expands and distorts when user added some effect to the CCEffectNode and tries to change to its area. When we change the area of the CCEffect node, bird image expands and changes its size accordingly. Video is attached.

Video Link: https://phabricator.apportable.com/T726

**Build:** SpriteBuilder 1.3 Beta 07

MAC OS: 10.9.0
XCode version: 5.0

**Comment by thayerandrews** [comment]
I'm no longer able to reproduce this issue. 

Adding a gradient and bird image as children of CCEffectNode behaves as expected. Applying the blur effect to the CCEffectNode does not result in the gradient disappearing and the bird expanding unexpectedly as it did before. Resizing the CCEffectNode still results in the gradient and bird resizing as expected.

Here is a test project that demonstrates this with the current develop branch of SB:

https://drive.google.com/file/d/0B7uVFeTINinAQjdmajc5b3Y3RXM/view?usp=sharing

**Comment by sana20** [comment]
This issue is fixed.

Mac OS X: 10.10.1
XCode: 6.1.
Latest Develop branch SB Version (2.0)
SB Revision: 02eedd1
