### ISSUE TITLE
All the previous files/folders deleted from the system of the targeted folder which is as path used for zip files of sprite builder resources.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#967]
1. Create new folder on the desktop and drag few random images and folders.
2. Launch SBP.
3. Create new project.
4. Tap cmd+;.
5. Select Sprite Builder resources from the left panel.
6. Check "as zip file" box.
7. Check "custom directory for zip files" and give the path of #1 point.
8. Open the folder which is created in pint#1.
9. Tap done.
10. Publish project.
    
    --Result: All the previous files/folders deleted from the system of the targeted folder which is as path used for zip files of sprite builder resources.

**Note:** Deleted files/folders are not even in the trash.

**Build:** SpriteBuilder 1.3 Beta 07

**Mac OS:** 10.9.0.

**Comment by NickyWeber** [comment]
This is exptected behaviour. This can't be resolved directly. Have a look at https://github.com/spritebuilder/SpriteBuilder/issues/864 and
https://github.com/spritebuilder/SpriteBuilder/issues/865

**Comment by sana20** [comment]
+Hammad

Sana Shahzad
Quality Assurance Analyst _|_ we.R.play
_www.werplay.com http://www.werplay.com/_
