### ISSUE TITLE
CCEffect in SB does not match Device/Simulator

### ISSUE THREAD

**Issue by cocojoe** [spritebuilder/SpriteBuilder#969]
When applying Effects to Sprites the output on device/simulator does not match the preview in SpriteBuilder.  Project linked at end. In this case the sprite vanishes.

Imagine this is either a bug or limitation in CCEffects as it only happens when using a Sprite Sheet.

*SB
![screen shot 2014-10-14 at 11 39 57](https://cloud.githubusercontent.com/assets/928115/4628022/e5a06fb2-5391-11e4-9536-dbad1fe68993.png)

*iOS
![ios simulator screen shot 14 oct 2014 11 40 17](https://cloud.githubusercontent.com/assets/928115/4628026/f24b7842-5391-11e4-9270-9f720df432b9.png)

https://www.dropbox.com/s/4n1jni1yh2kzgq4/effectissue.spritebuilder.zip?dl=0
SB 1.3B7
Xcode 5/6

**Comment by thayerandrews** [comment]
Thank you for the helpful test case Martin. You're correct that this is a problem with the interaction between CCEffects and sprite sheets. I'm debugging it now.

**Comment by vlidholt** [comment]
Needs verification

**Comment by cocojoe** [comment]
Will do a quick retest

**Comment by cocojoe** [comment]
Fixed
