### ISSUE TITLE
AngryBird demo project crashes on launch when we tried to run project on Nexus 10.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#972]
1. Launch SBP.
2. Create AngryBirds demo project.
3. Run in XCode and check on iOS Simulator. 
   -- Observe: Project run perfectly fine on iOS simulator. (Expected)
4. Attach Android device.
5. Select “yourAppName” and then select the Android device and Run. 
   
   -- Result: AngryBird demo project crashes on launch when we tried to run project on Nexus 10.

Target: AngryBirdsKanoot Android > Samsung mantaray R32D100Y5JM (armv7a-neon)

**Build:** SpriteBuilder-1.3.0-beta.07.zip

MAC OS: 10.9.5
XCode version: 6.0
Android device: Nexus 10/4.2.2.

**Comment by cocojoe** [comment]
Any logs for this?
I don't have device to validate.

**Comment by khanbhai89** [comment]
You can find console here: https://drive.google.com/file/d/0B5KeRaV3CWUaNWhWcFV3Y21qWUU/view?usp=sharing

**Comment by khanbhai89** [comment]
This issue can be closed with reference to issue reported here: https://github.com/spritebuilder/SpriteBuilder/issues/977
