### ISSUE TITLE
"Failed to publish file" warnings and "missing texture" is displayed on the stage when user selects no path for zip files of sprite builder resources.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#973]
1. Create new folder on the desktop and drag few random images and folders.
2. Launch SBP.
3. Create new project.
4. Create sprite named bird.
5. Tap cmd+;.
6. Select Sprite Builder resources from the left panel.
7. Check "as zip file" box.
8. Check "custom directory for zip files" and give desktop path.
   --Observe: This path "../" is displayed. 
9. Tap done.
10. Publish project.
    
    --Result: "Failed to publish file" warnings and "missing texture" is displayed on the stage when user selects no path for zip files of sprite builder resources. Screenshot is attached named "Screen Shot 2014-08-04 at 7.09.32 pm".

**Important Note:** While testing selecting same path through different ways gives different results i-e selecting desktop from user>home>desktop, ".." path is displayed on the SPB custom path. Screenshot of warnings (files) and path (path.png) is attached. 

![path](https://cloud.githubusercontent.com/assets/8393830/4629077/0bbe215e-53a0-11e4-9021-da49844aeef4.png)
![files](https://cloud.githubusercontent.com/assets/8393830/4629078/0d82fef6-53a0-11e4-8297-2db353d7669f.png)
![screen_shot_2014-08-04_at_7 09 32_pm](https://cloud.githubusercontent.com/assets/8393830/4629079/0f2446d4-53a0-11e4-8f02-8f779cee7718.png)

**Build:** SpriteBuilder 1.3 Beta 07

**Mac OS:** 10.9.0.

**Comment by cocojoe** [comment]
I tried to replicate this bug and for me, just clicking on `select` in the `Custom directory for zip files` crashes SpriteBuilder.

**Comment by NickyWeber** [comment]
It doesn't crash in my case but this is related to: https://github.com/spritebuilder/SpriteBuilder/issues/929

**Comment by NickyWeber** [comment]
@cocojoe This is also fixed in my pull request #999

**Comment by sana20** [comment]
This issue is fixed.
Build: SpriteBuilder-1.3.0-rc.1
MAC OS: 10.9.0
XCode: 5.0
