### ISSUE TITLE
Background is not displayed and images are displayed broken when we tried to run AngryBirds demo project on Samsung Tab 2 7'.

### ISSUE THREAD

**Issue by sana20** [spritebuilder/SpriteBuilder#974]
1. Launch SBP.
2. Create AngryBirds demo project.
3. Run in XCode and check on iOS Simulator.
   --Observe: Project run perfectly fine on iOS simulator. (Expected)
4. Attach Android device.
5. Select “yourAppName” and then select the Android device and Run. 
   
   --Result: Background is not displayed and images are displayed broken when we tried to run AngryBirds demo project on Samsung Tab 2 7'.

Target: AngryBirdsKanoot Android > Samsung espressorfxx c0808f27403ea40 (armv7a-neon)

![tab2](https://cloud.githubusercontent.com/assets/8393830/4629218/e411b0ba-53a1-11e4-837a-69a529c11f34.png)

**Build:**  SpriteBuilder 1.3 Beta 07

**AngryBirdsKanoot Project:**

Video Link: https://phabricator.apportable.com/T734

**Important Note:** This project runs perfectly fine on HTC One Mini/4.2.2.

MAC OS: 10.9.0
XCode version: 5.0
Android device: Samsung Tab 2 7'/4.0.4

**Comment by Shahidwerplay** [comment]
This issue is fixed.
Mac OS 10.10.0
SB version 1.4.7
XCode 6.1
