### ISSUE TITLE
Application freezes when user runs a project in simulator after adding a callback through timeline.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#979]
1. Launch Application.
2. Create angry birds demo using document here: https://docs.google.com/a/werplay.com/spreadsheet/ccc?key=0Am3s5OMd3iivdGxGd3lYcDhyTVo1cFhsQW9Jei14ZUE#gid=9
3. Add Callback function on 1 sec mark "launch:" or "launchBird:".
4. Publish project.
5. Open XCode Project file.
6. Add "launch:" function in MainScene.m file.
7. Run Project.
   
   -- Result: Memory problem is generated and application freezes.

This happened 3/3 times.

Build: SpriteBuilder-1.3.0-beta.07.zip

Mac OS X: 10.9.2.
XCode: 5.0.

Images:
![screen_shot_2014-08-29_at_10 19 57_pm](https://cloud.githubusercontent.com/assets/7450007/4633123/1c70fd9a-53c4-11e4-8382-39039f3f3589.png)

**Comment by Kanoot** [comment]
This issue is fixed.

Build: SpriteBuilder-1.3.0-rc.1.zip

Mac OS X: 10.9.0
XCode: 5.0
Android device: SGS4/4.4.2
Android device: Google Nexus /4.2.1
