### ISSUE TITLE
Refracted images keeps on changing its place when user zooms into the stage.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#980]
1. Launch Application.
2. Drag and drop a CCEffectNode on to the stage.
3. Drag and Drop bear image on the stage.
4. Add Refraction Effect in Effect Manager.
5. Select Environment as bear image you just dragged.
6. Zoom into the stage.
   
   -- Result: Refracted images keeps on changing its place when user zooms into the stage.

This happened 3/3 times.
**Build:** SpriteBuilderPro-sb-pro-1.3.0-beta.01-dcf-release_3.0.0-alpha.3-bc0e69e3b53af734369910d4fc43b65be0a4c9ea_54c01dda4a075050.dmg

Mac OS X: 10.9.2.

**Comment by khanbhai89** [comment]
Couldn't verify these issues on SpriteBuilder-1.3.0-beta.07.zip on Mac OS X: 10.9.5. because of the issues here: https://github.com/spritebuilder/SpriteBuilder/issues/960

**Comment by thayerandrews** [comment]
This should have been fixed in https://github.com/cocos2d/cocos2d-swift/pull/997

**Comment by khanbhai89** [comment]
This issue is fixed on SpriteBuilder 1.4.7. (Appstore) on Mac OS X 10.9.5.
