### ISSUE TITLE
Normal Map doesn't return to it's default state when user changes it back to "NULL" after changing it once before.

### ISSUE THREAD

**Issue by khanbhai89** [spritebuilder/SpriteBuilder#981]
1. Launch Application.
2. Drag and drop a CCEffectNode on to the stage.
3. Drag and Drop bear image on the stage.
4. Add Reflection Effect in Effect Manager.
5. Select Environment as bear image you just dragged.
   -- Observe: Effect is completely placed on whole CCEffectNode panel. (Observe)
6. Change Normal Map from Null to Bear Image.
   -- Observe: Reflection is rightly align itself against the bear image.
7. Select NULL as Normal Map.
   
   -- Result: Reflection effect vanishes when user changes it back to NULL.
   
   This happened 3/3 times.

**Build:** SpriteBuilderPro-sb-pro-1.3.0-beta.01-dcf-release_3.0.0-alpha.3-bc0e69e3b53af734369910d4fc43b65be0a4c9ea_54c01dda4a075050.dmg

Mac OS X: 10.9.2.

**Comment by khanbhai89** [comment]
Couldn't verify this issue because of the issue reported here: https://github.com/spritebuilder/SpriteBuilder/issues/960

**Comment by Shahidwerplay** [comment]
This issue is still occurring on SpriteBuilder-1.4.8-rc.0 with SBAndroidPluginIndie-9ac08c84
MAC OS X: 10.10.
XCode: 6.1.

**Comment by khanbhai89** [comment]
This issue is fixed on SpriteBuilder 1.4.7. (Appstore) on Mac OS X 10.9.5.
