### ISSUE TITLE
No android option is given to generate build in XCode after upgrading project from SB to SBP.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#990]
1. Launch SB.
2. Create a new Empty project.
3. Publish project.
4. Open above project in SBP.
   -- Observe: Pop-up to upgrade project is given. (Expected)
5. Upgrade project.
6. Publish project.
7. Open XCode project file.
   
   -- Result: There is no Android target to select from to transfer it to android device.

Build: SpriteBuilderPro-sb-pro-1.2.0-beta.10-dcf-release_3.0.0-alpha.0-ad06e8b20a169402ccb8760a00993d0f654d5dac_b6eea3314af10879.dmg

Mac OS X: 10.9.2.
XCode: 5.0.
Device: SGS4/4.4.2.

Image: 
![screen_shot_2014-08-29_at_8 51 51_pm](https://cloud.githubusercontent.com/assets/7566802/4641639/be190d88-543a-11e4-9956-18beda605685.png)

**Comment by khanbhai89** [comment]
This issue is still occurring on SpriteBuilder-1.3.0-rc.1.zip on Mac OS X: 10.9.5. and XCode: 6.0.

**Comment by NickyWeber** [comment]
I guess we can close this as there is no SBP anymore.

**Comment by Kanoot** [comment]
This issue reoccurring, upgraded from SB 1.2 to SB 1.3. 

Build: SpriteBuilder-1.3.6.rc.1

Mac OS X: 10.9.5.
XCode: 6.0.
