### ISSUE TITLE
The Xcode and IOS Simulator still displays the previous mainscene file as it is even if you delete the ccbResources and mainscene.ccb from the sprite builder pro.

### ISSUE THREAD

**Issue by Kanoot** [spritebuilder/SpriteBuilder#991]
1. Launch the sprite builder pro.
2. Drag and drop a button and some particle effects on a layer.
3. Add this layer to mainscene.ccb
4. Publish the project.
5. Run the project through Xcode.
6. Now delete everything from the project in spritebuilder pro .
7. Again publish the project.
8. Run the project through Xcode file.
   
   -- Result: The mainscene still displays the previous images like button and particle you added.

Build: SpriteBuilderPro-sb-1.2.0-beta.7-dcf-release_3.0.0-alpha.0-f28e9cfda22d61aa5b784b7e7d25f5bae0fe1323_c45808d300864d44.dmg

Link to video: https://drive.google.com/file/d/0B23s5OMd3iivcUZkM25ZTERjaGM/edit?usp=sharing

**Comment by NickyWeber** [comment]
That's actually an issue of the Simulator, it will eventually update modified files. However deleted files remain on the sim.
